packages/strapi-design-system/src/Divider/Divider.js
packages/strapi-design-system/src/Divider/Divider.stories.mdx
packages/strapi-design-system/src/Divider/__tests__/Divider.e2e.js
packages/strapi-design-system/src/Divider/__tests__/Divider.spec.js
packages/strapi-design-system/src/Divider/index.js

This PRs adds a divider component (which is a line of 1px height with a neutral150 background color)
https://design-system-git-divider-strapijs.vercel.app/?path=/story/divider--base

Add divider component

---

examples/app/package.json
examples/app/yarn.lock
packages/strapi-design-system/yarn.lock
packages/strapi-icons/yarn.lock
yarn.lock

Force local package install

---

packages/strapi-design-system/src/Row/Row.js
packages/strapi-design-system/src/Row/Row.stories.mdx
packages/strapi-design-system/src/Row/__tests__/Row.e2e.js
packages/strapi-design-system/src/Row/__tests__/Row.spec.js
packages/strapi-design-system/src/Row/index.js

Add a row layout component.
I'm not a huge fan of this one since it may break responsiveness in the future. But since I don't find any good solutions to handle row base layout, I'm opening this one.
It only contains a minimalist set of CSS rules. If we feel the need to add more, let's add them in another pr 😊

Add Row layout

---

.github/workflows/playwright-ci.yml
packages/strapi-design-system/.storybook/main.js
packages/strapi-design-system/package.json
packages/strapi-design-system/src/Checkbox/__tests__/Checkbox.spec.js
packages/strapi-design-system/src/Field/Field.js
packages/strapi-design-system/src/Field/Field.stories.mdx
packages/strapi-design-system/src/Field/FieldAction.js
packages/strapi-design-system/src/Field/FieldContext.js
packages/strapi-design-system/src/Field/FieldError.js
packages/strapi-design-system/src/Field/FieldHint.js
packages/strapi-design-system/src/Field/FieldInput.js
packages/strapi-design-system/src/Field/FieldLabel.js
packages/strapi-design-system/src/Field/__tests__/Field.e2e.js
packages/strapi-design-system/src/Field/__tests__/Field.spec.js
packages/strapi-design-system/src/Field/index.js
packages/strapi-design-system/src/Radio/__tests__/Radio.spec.js
packages/strapi-design-system/src/Text/__tests__/Text.spec.js
packages/strapi-design-system/src/Text/index.js
packages/strapi-design-system/src/ThemeProvider/ThemeProvider.js
packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.js

Storybook available on https://design-system-git-base-field-strapijs.vercel.app/?path=/story/field--default-story
These components aim to be building blocks for higher-level components such as `TextInput` but also the select, textarea, dropdown etc...
Most simple case
```jsx
<Field name="email">
<Stack size={1}>
<FieldLabel>Email</FieldLabel>
<FieldInput type="text" placeholder="Placeholder" value={value} onChange={(e) => setText(e.target.value)} />
</Stack>
</Field>
```
Most complex case
```jsx
<Field name="password" hint="Description line" error={email.length > 5 ? 'Email is too short' : undefined}>
<Stack size={1}>
<Grid cols="auto auto 1fr" gap={1}>
<FieldLabel>Password</FieldLabel>
<Tooltip content="Content of the tooltip">
<button
style={{ border: 'none', padding: 0, background: …
```

Base field

---

packages/strapi-design-system/src/Field/Field.stories.mdx
packages/strapi-design-system/src/Field/FieldAction.js
packages/strapi-design-system/src/Field/FieldInput.js
packages/strapi-design-system/src/Field/__tests__/Field.spec.js

In order to create components such as the Search bar that has actions on both sides

Allow to pass rightAction and leftAction for the base field

---

packages/strapi-design-system/src/Tag/Tag.js
packages/strapi-design-system/src/Tag/Tag.stories.mdx
packages/strapi-design-system/src/Tag/__tests__/Tag.e2e.js
packages/strapi-design-system/src/Tag/__tests__/Tag.spec.js
packages/strapi-design-system/src/Tag/index.js

Add a Tag component
Example: https://design-system-git-add-tag-strapijs.vercel.app/?path=/story/tag--base
```jsx
<Tag icon={<HelpIcon aria-hidden={true} />}>Hello world</Tag>
```

Add Tag component

---

packages/strapi-design-system/src/Divider/Divider.js
packages/strapi-design-system/src/Divider/__tests__/Divider.spec.js

Make divider "hr" instead of "div"

---

packages/strapi-design-system/src/Field/FieldInput.js
packages/strapi-design-system/src/Field/__tests__/Field.spec.js

The red border was not showing anymore since the move to to the wrapper 🤦🏻

Fixing input border

---

packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.stories.mdx
packages/strapi-design-system/src/BaseRadio/BaseRadio.stories.mdx
packages/strapi-design-system/src/Button/Button.stories.mdx
packages/strapi-design-system/src/Checkbox/Checkbox.stories.mdx
packages/strapi-design-system/src/Divider/Divider.stories.mdx
packages/strapi-design-system/src/Radio/Radio.stories.mdx

Remove figma url

---

packages/strapi-design-system/src/Pagination/Pagination.js
packages/strapi-design-system/src/Pagination/Pagination.stories.mdx
packages/strapi-design-system/src/Pagination/PaginationContext.js
packages/strapi-design-system/src/Pagination/__tests__/Pagination.spec.js
packages/strapi-design-system/src/Pagination/components.js

Example: https://design-system-git-fix-pagination-strapijs.vercel.app/iframe.html?id=pagination--base&viewMode=story

Fix pagination

---

packages/strapi-design-system/src/Field/FieldInput.js
packages/strapi-design-system/src/Field/__tests__/Field.spec.js
packages/strapi-design-system/src/Field/index.js
packages/strapi-design-system/src/Searchbar/SearchForm.js
packages/strapi-design-system/src/Searchbar/Searchbar.js
packages/strapi-design-system/src/Searchbar/Searchbar.stories.mdx
packages/strapi-design-system/src/Searchbar/__tests__/Searchbar.e2e.js
packages/strapi-design-system/src/Searchbar/__tests__/Searchbar.spec.js
packages/strapi-design-system/src/Searchbar/index.js
packages/strapi-design-system/src/ThemeProvider/ThemeProvider.js
packages/strapi-design-system/yarn.lock

Add a Searchbar component
Example:  https://design-system-git-add-searchbar-strapijs.vercel.app/?path=/story/searchbar--base
```jsx
<SearchForm>
<Searchbar
name="searchbar"
onClear={() => setValue('')}
value={value}
onChange={(e) => setValue(e.target.value)}
clearLabel="Clearing the plugin search"
placeholder="e.g: strapi-plugin-abcd"
>
Searching for a plugin
</Searchbar>
</SearchForm>
```

Adding searchbar component

---

packages/strapi-design-system/src/Popover/Popover.js
packages/strapi-design-system/src/Popover/Popover.stories.mdx
packages/strapi-design-system/src/Popover/__tests__/Popover.e2e.js
packages/strapi-design-system/src/Popover/__tests__/Popover.spec.js
packages/strapi-design-system/src/Popover/index.js

Popover is a component that aims to show the visible part of a "dropdown".
⚠️ it does not manage the logic (that will go in a hook later)

Preparing Popover

---

packages/strapi-design-system/src/Popover/Popover.js
packages/strapi-design-system/src/Popover/__tests__/Popover.spec.js

Fix popover tests

---

packages/strapi-design-system/src/BaseButton/BaseButton.js
packages/strapi-design-system/src/BaseButton/BaseButton.stories.mdx
packages/strapi-design-system/src/BaseButton/__tests__/BaseButton.e2e.js
packages/strapi-design-system/src/BaseButton/__tests__/BaseButton.spec.js
packages/strapi-design-system/src/BaseButton/index.js
packages/strapi-design-system/src/Box/Box.js
packages/strapi-design-system/src/Button/Button.js
packages/strapi-design-system/src/Button/__tests__/Button.spec.js
packages/strapi-design-system/src/Button/utils.js
packages/strapi-design-system/src/Field/Field.stories.mdx
packages/strapi-design-system/src/Grid/Grid.js
packages/strapi-design-system/src/IconButton/IconButton.js
packages/strapi-design-system/src/IconButton/IconButton.stories.mdx
packages/strapi-design-system/src/IconButton/__tests__/IconButton.e2e.js
packages/strapi-design-system/src/IconButton/__tests__/IconButton.spec.js
packages/strapi-design-system/src/IconButton/index.js
packages/strapi-design-system/src/Tooltip/Tooltip.js
packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.js
packages/strapi-design-system/src/Tooltip/utils/positionTooltip.js

Add a icon button component
Example on: https://design-system-git-icon-button-strapijs.vercel.app/?path=/story/iconbutton--base
```jsx
import { EditIcon } from '@strapi/icons';
 
<IconButton title="Edit">
<EditIcon />
</IconButton>
```

Add icon button

---

packages/strapi-design-system/src/Switch/Switch.js
packages/strapi-design-system/src/Switch/Switch.stories.mdx
packages/strapi-design-system/src/Switch/__tests__/Switch.e2e.js
packages/strapi-design-system/src/Switch/__tests__/Switch.spec.js
packages/strapi-design-system/src/Switch/index.js

Add a switch component
[api details]
```jsx
<Switch label="Activate the microphone" selected={checked} onSwitch={setChecked} visibleLabels />;
```

Add switch

---

packages/strapi-design-system/src/Field/Field.stories.mdx
packages/strapi-design-system/src/Textarea/Textarea.js
packages/strapi-design-system/src/Textarea/Textarea.stories.mdx
packages/strapi-design-system/src/Textarea/__tests__/Textarea.e2e.js
packages/strapi-design-system/src/Textarea/__tests__/Textarea.spec.js
packages/strapi-design-system/src/Textarea/index.js

Add a Textarea component
Example on : https://design-system-3zod03upf-strapijs.vercel.app/?path=/story/textarea--base
[api details]
```jsx
<Textarea
placeholder="This is a content placeholder"
label="Content"
name="content"
hint="Description line"
error={content.length < 5 ? 'Content is too short' : undefined}
onChange={(e) => setContent(e.target.value)}
action={<span>Put tooltip here</span>}
>
Content of the textarea
</Textarea>
```
N/A

Add textarea component

---

packages/strapi-design-system/src/Field/Field.stories.mdx
packages/strapi-design-system/src/Field/FieldAction.js
packages/strapi-design-system/src/Field/__tests__/Field.spec.js
packages/strapi-design-system/src/Searchbar/Searchbar.js
packages/strapi-design-system/src/Searchbar/__tests__/Searchbar.spec.js
packages/strapi-design-system/src/TextInput/TextInput.js
packages/strapi-design-system/src/TextInput/TextInput.stories.mdx
packages/strapi-design-system/src/TextInput/__tests__/TextInput.e2e.js
packages/strapi-design-system/src/TextInput/__tests__/TextInput.spec.js
packages/strapi-design-system/src/TextInput/index.js
packages/strapi-design-system/src/Textarea/Textarea.js
packages/strapi-design-system/src/Textarea/Textarea.stories.mdx
packages/strapi-design-system/src/Textarea/__tests__/Textarea.spec.js

Higher level component for displaying a textinput on the screen.
NOTE: the Link component is not part of the API since it does not exist yet in the DS document
Example on : https://design-system-git-add-text-input-strapijs.vercel.app/?path=/story/textinput--base
```jsx
<TextInput
placeholder="This is a content placeholder"
label="Content"
name="content"
hint="Description line"
error={undefined}
onChange={(e) => {}}
value={'content'}
action={<span>Hello world</span>}
/>
```

Add text input

---

packages/strapi-icons/package.json
packages/strapi-icons/webpack.config.js
packages/strapi-icons/yarn.lock

Add the same bundle analyzer as the design system directory, but for the icons one

Add bundle analyzer for icons

---

packages/strapi-design-system/src/Table/Cell.js
packages/strapi-design-system/src/Table/Table.js
packages/strapi-design-system/src/Table/Tr.js
packages/strapi-design-system/src/Table/__tests__/Table.e2e.js
packages/strapi-design-system/src/Table/focusFocusable.js

This PR improves the Td focus when they own focusable elements such as anchor and button. instead of focusing the cell and then having to tab to focus the anchor/button, the anchor/button is directly focused.

Improve table focus

---

packages/strapi-design-system/src/Field/FieldInput.js
packages/strapi-design-system/src/Field/__tests__/Field.spec.js
packages/strapi-design-system/src/Searchbar/__tests__/Searchbar.spec.js
packages/strapi-design-system/src/TextInput/__tests__/TextInput.spec.js
packages/strapi-design-system/src/Textarea/Textarea.js
packages/strapi-design-system/src/Textarea/TextareaInput.js
packages/strapi-design-system/src/Textarea/__tests__/Textarea.spec.js

Fix textarea comment from @maevalienard on https://github.com/strapi/design-system-experiments/pull/84#issuecomment-847101591
>    Will the placeholder style be implemented later? cc @mfrachet
It's supposed to be done here
>    Does the description/error line changes?
Not sure to understand?
>    I think there's a bug with the area opener pointer, when I moved it (probably on the left), it stayed there
Yep, good catch, fixed in this one 👍🏻 

Fix textarea

---

packages/strapi-design-system/src/AssetTag/index.js
packages/strapi-design-system/src/Badge/Badge.js
packages/strapi-design-system/src/Badge/Badge.stories.mdx
packages/strapi-design-system/src/Badge/__tests__/AssetTag.e2e.js
packages/strapi-design-system/src/Badge/__tests__/AssetTag.spec.js
packages/strapi-design-system/src/Badge/index.js
packages/strapi-design-system/src/index.js

All in the title. Nothing more

Renaming AssetTag to Badge

---

packages/strapi-design-system/src/Popover/Popover.js
packages/strapi-design-system/src/Popover/Popover.stories.mdx

Allows popover to receive a spacing for positioning from the top

Allows popover to receive a spacing for positioning from the top

---

packages/strapi-design-system/src/Avatar/Avatar.js
packages/strapi-design-system/src/Avatar/Avatar.stories.mdx
packages/strapi-design-system/src/Avatar/__tests__/Avatar.e2e.js
packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.js
packages/strapi-design-system/src/Avatar/index.js
packages/strapi-design-system/src/MainNav/MainNav.js
packages/strapi-design-system/src/MainNav/MainNav.stories.mdx
packages/strapi-design-system/src/MainNav/NavCondense.js
packages/strapi-design-system/src/MainNav/NavSections.js
packages/strapi-design-system/src/MainNav/NavUser.js
packages/strapi-design-system/src/MainNav/__tests__/MainNav.spec.js
packages/strapi-design-system/src/MainNav/index.js
packages/strapi-design-system/src/index.js

Add a NavUser component and the NavCondense button

Main nav round 2

---

example/src/shared/GenericInput/__tests__/GenericInput.spec.js
example/yarn.lock
packages/strapi-design-system/src/Accordion/Accordion.js
packages/strapi-design-system/src/Accordion/Accordion.stories.mdx
packages/strapi-design-system/src/Accordion/AccordionContent.js
packages/strapi-design-system/src/Accordion/AccordionContext.js
packages/strapi-design-system/src/Accordion/AccordionToggle.js
packages/strapi-design-system/src/Accordion/DropdownIconWrapper.js
packages/strapi-design-system/src/Accordion/__tests__/Accordion.e2e.js
packages/strapi-design-system/src/Accordion/__tests__/Accordion.spec.js
packages/strapi-design-system/src/Accordion/index.js

An  accordion component
The most simple:
```jsx
<Accordion expanded={expanded} toggle={() => setExpanded((s) => !s)} id="acc-1">
<AccordionToggle
title="User informations"
description="The following contains information about the current user"
/>
<AccordionContent>
<Box padding={3}>My name is John Duff</Box>
</AccordionContent>
</Accordion>
```
The most complex:
```jsx
<Accordion expanded={expanded} toggle={() => setExpanded((s) => !s)} id="acc-4">
<AccordionToggle
variant="secondary"
togglePosition="left"
title="User informations 4"
description="The following contains information about the current user 3"
action={
<IconButton onClick={() => console.log('edit')} title="Edit">
<EditIcon />
</IconButton>
}
/>
<AccordionContent>
<Box padding={3}>My name is …
```

Add accordion

---

packages/strapi-design-system/src/Tabs/Tabs.js
packages/strapi-design-system/src/Tabs/__tests__/Tabs.spec.js

Fix Tabs border radius

---

example/src/shared/GenericInput/__tests__/GenericInput.spec.js
packages/strapi-design-system/src/Checkbox/Checkbox.js
packages/strapi-design-system/src/Checkbox/Checkbox.stories.mdx
packages/strapi-design-system/src/Checkbox/CheckboxLabel.js
packages/strapi-design-system/src/Checkbox/__tests__/Checkbox.e2e.js
packages/strapi-design-system/src/Checkbox/__tests__/Checkbox.spec.js
packages/strapi-design-system/src/Field/Field.stories.mdx

This adds a description line and error line on the checkbox

Add description line to checkbox

---

packages/strapi-design-system/src/Select/Select.js

Mandatory prop types for placeholder

---

packages/strapi-design-system/src/Popover/Popover.js
packages/strapi-design-system/src/Popover/Popover.stories.mdx
packages/strapi-design-system/src/Popover/__tests__/Popover.e2e.js
packages/strapi-design-system/src/Select/Select.js
packages/strapi-design-system/src/Select/Select.stories.mdx
packages/strapi-design-system/src/Select/__tests__/Select.spec.js
packages/strapi-design-system/src/helpers/useIntersection.js

It should trigger only when the container is scrollable

Add onReachEnd on popover

---

example/src/ContentManager/EditView/SideAction.js
example/src/pages/EditViewPage.js
packages/strapi-design-system/src/Button/Button.js
packages/strapi-design-system/src/Button/Button.stories.mdx
packages/strapi-design-system/src/DatePicker/DatePicker.js
packages/strapi-design-system/src/Field/Field.stories.mdx
packages/strapi-design-system/src/Field/FieldInput.js
packages/strapi-design-system/src/Field/__tests__/Field.spec.js
packages/strapi-design-system/src/Link/Link.js
packages/strapi-design-system/src/Link/Link.stories.mdx
packages/strapi-design-system/src/Link/__tests__/Link.spec.js
packages/strapi-design-system/src/Searchbar/Searchbar.js
packages/strapi-design-system/src/TextButton/TextButton.js
packages/strapi-design-system/src/TextButton/TextButton.stories.mdx
packages/strapi-design-system/src/TextButton/__tests__/TextButton.spec.js
packages/strapi-design-system/src/TextInput/TextInput.js
packages/strapi-design-system/src/Textarea/Textarea.js

Moving `leftIcon` to `startIcon`, `rightIcon` to `endIcon`, `leftAction` to `startAction` and `rightAction` to `endAction`

Left right to start end

---

packages/strapi-design-system/src/Checkbox/Checkbox.js
packages/strapi-design-system/src/Select/Select.js
packages/strapi-design-system/src/Select/Select.stories.mdx
packages/strapi-design-system/src/Select/SelectButton.js
packages/strapi-design-system/src/Select/__tests__/Select.spec.js
packages/strapi-design-system/src/TimePicker/TimePicker.js
packages/strapi-design-system/src/TimePicker/TimePicker.stories.mdx
packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.e2e.js
packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-design-system/src/TimePicker/index.js
packages/strapi-design-system/src/helpers/escapeSelector.js
packages/strapi-design-system/src/index.js

Add a TimePicker component which is basically a "Select" with a bunch of computation on dates.
```jsx
<TimePicker
label={'Choose a time'}
disabled={false}
error={undefined}
hint={'Description line'}
id={'tp-1'}
onClear={() => setValue(undefined)}
onChange={setValue}
value={value}
clearLabel={'Clear the selected time picker value'}
step={15} // number of minutes to count, default is 15 
/>
```

Time picker

---

example/src/App.test.js
example/src/shared/GenericInput/__tests__/GenericInput.spec.js
packages/strapi-design-system/src/Box/Box.js
packages/strapi-design-system/src/Status/Status.js
packages/strapi-design-system/src/Status/Status.stories.mdx
packages/strapi-design-system/src/Status/__tests__/Status.e2e.js
packages/strapi-design-system/src/Status/__tests__/Status.spec.js
packages/strapi-design-system/src/Status/index.js

Add a Status component
Example on : https://design-system-git-add-status-strapijs.vercel.app/?path=/story/design-system-atoms-status--base
```jsx
<Status variant="success">
<Text>
Hello world{' '}
<Text as="span" highlighted>
thing happens
</Text>
</Text>
</Status>
```

Add Status component

---

packages/strapi-design-system/src/Avatar/Avatar.js
packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.js

Add height and width HTML attribute on Avatar in order to reduce CLS
https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/

Setting height and width on Avatar

---

packages/strapi-design-system/src/Accordion/Accordion.stories.mdx
packages/strapi-design-system/src/Accordion/AccordionGroup.js
packages/strapi-design-system/src/Accordion/AccordionToggle.js
packages/strapi-design-system/src/Accordion/__tests__/Accordion.spec.js
packages/strapi-design-system/src/Accordion/__tests__/AccordionGroup.e2e.js
packages/strapi-design-system/src/Accordion/index.js

Allow keyboard navigation between a group of accordions
Example on : https://design-system-git-grouping-accordions-strapijs.vercel.app/?path=/story/design-system-molecules-accordion--group

Grouping accordions

---

example/src/CM/index.js
example/src/layouts/OneBlockLayout.js
packages/strapi-design-system/src/Grid/Grid.stories.mdx
packages/strapi-design-system/src/Grid/GridItem.js
packages/strapi-design-system/src/Grid/__tests__/Grid.spec.js
packages/strapi-design-system/src/themes/light-theme.js

Add `s` (for tablet) and `xs` (for mobile) props to the grid item component

Add responsive props to grid

---

example/src/CM/index.js
example/src/layouts/OneBlockLayout.js
packages/strapi-design-system/src/Box/Box.js
packages/strapi-design-system/src/Box/Box.stories.mdx
packages/strapi-design-system/src/Grid/Grid.js
packages/strapi-design-system/src/Grid/Grid.stories.mdx
packages/strapi-design-system/src/Grid/__tests__/Grid.spec.js
packages/strapi-design-system/src/helpers/handleResponsiveSpacing.js

Responsive padding and grid gap

---

packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.js
packages/strapi-design-system/src/BaseCheckbox/__tests__/BaseCheckbox.spec.js
packages/strapi-design-system/src/Checkbox/__tests__/Checkbox.spec.js
packages/strapi-design-system/src/IconButton/IconButton.js
packages/strapi-design-system/src/RawTable/RawCell.js
packages/strapi-design-system/src/Table/Cell.js
packages/strapi-design-system/src/Table/Table.js
packages/strapi-design-system/src/Table/Table.stories.mdx
packages/strapi-design-system/src/Table/Tbody.js
packages/strapi-design-system/src/Table/Thead.js
packages/strapi-design-system/src/Table/Tr.js
packages/strapi-design-system/src/Table/__tests__/Table.e2e.js
packages/strapi-design-system/src/Table/__tests__/Table.spec.js
packages/strapi-design-system/src/Table/index.js
packages/strapi-design-system/src/index.js

Implement the UI part of the Table component
Example on : https://design-system-git-table-strapijs.vercel.app/?path=/story/design-system-organisms-table--base
```jsx
<Table colCount={COL_COUNT} rowCount={ROW_COUNT}>
<Thead>
<Tr>
<Th>
<BaseCheckbox aria-label="Select all entries" />
</Th>
<Th>
<TableLabel as="span">ID</TableLabel>
</Th>
<Th>
<TableLabel as="span">Cover</TableLabel>
</Th>
<Th>
<TableLabel as="span">Description</TableLabel>
</Th>
<Th>
<TableLabel as="span">Categories</TableLabel>
</Th>
<Th>
<TableLabel as="span">Contact</TableLabel>
</Th>
<Th>
<VisuallyHidden>Actions</VisuallyHidden>
</Th>
</Tr>
</Thead>
<Tbody>
{entries.map((entry) => (
<Tr key={entry.id}>
<Td>
<BaseCheckbox aria-label={`Select ${entry.name}`} />
</Td>
<Td>
<Text textColor="neutral600" as="span">
{entry.id} …
```

Prepare the Table component (UI)

---

packages/strapi-design-system/src/Card/Card.js
packages/strapi-design-system/src/Card/Card.stories.mdx
packages/strapi-design-system/src/Card/Cards.js
packages/strapi-design-system/src/Card/__tests__/Card.e2e.js

Navigable asset card

---

packages/strapi-design-system/src/Card/Card.stories.mdx
packages/strapi-design-system/src/Card/CardAsset.js
packages/strapi-design-system/src/Card/CardHeader.js
packages/strapi-design-system/src/Card/CardTimer.js
packages/strapi-design-system/src/Card/__tests__/Card.spec.js

- height of the image is 88px height
- the timer background is neutral800

Add card asset background

---

packages/strapi-design-system/src/RawTable/RawCell.js
packages/strapi-design-system/src/Table/TFooter.js
packages/strapi-design-system/src/Table/Table.js
packages/strapi-design-system/src/Table/Table.stories.mdx
packages/strapi-design-system/src/Table/__tests__/Table.spec.js
packages/strapi-design-system/src/Table/index.js

Add Table footer component

---

packages/strapi-design-system/src/Accordion/__tests__/Accordion.spec.js
packages/strapi-design-system/src/EmptyStateLayout/__tests__/EmptyStateLayout.spec.js
packages/strapi-design-system/src/Text/__tests__/Text.spec.js
packages/strapi-design-system/src/Text/index.js

Make H3 semi bold (500)

---

packages/strapi-design-system/src/OneBlockLayout/OneBlockLayout.js
packages/strapi-design-system/src/OneBlockLayout/OneBlockLayout.stories.mdx
packages/strapi-design-system/src/OneBlockLayout/__tests__/OneBlockLayout.e2e.js
packages/strapi-design-system/src/OneBlockLayout/index.js
packages/strapi-design-system/src/index.js

https://design-system-git-one-block-layout-strapijs.vercel.app/?path=/story/design-system-layouts-oneblocklayout--base
```jsx
<OneBlockLayout
header={
<HeaderLayout
primaryAction={<Button startIcon={<AddIcon />}>Add an entry</Button>}
secondaryAction={
<Button variant="tertiary" withShadow startIcon={<EditIcon />}>
Edit
</Button>
}
title="Other CT"
subtitle="36 entries found"
as="h2"
/>
}
startActions={
<>
<Button variant="tertiary" withShadow>
Search
</Button>
<Button variant="tertiary" withShadow>
Filter
</Button>
</>
}
endActions={
<>
<Button variant="tertiary" withShadow>
Settings
</Button>
</>
}
>
<Box padding={4}>hello world</Box>
</OneBlockLayout>
```

One block layout

---

packages/strapi-design-system/src/TwoColsLayout/TwoColsLayout.js
packages/strapi-design-system/src/TwoColsLayout/TwoColsLayout.stories.mdx
packages/strapi-design-system/src/TwoColsLayout/__tests__/TwoColsLayout.e2e.js
packages/strapi-design-system/src/TwoColsLayout/index.js
packages/strapi-design-system/src/index.js

```jsx
<TwoColsLayout
header={
<HeaderLayout
primaryAction={<Button startIcon={<AddIcon />}>Add an entry</Button>}
secondaryAction={
<Button variant="tertiary" startIcon={<EditIcon />}>
Edit
</Button>
}
title="Other CT"
subtitle="36 entries found"
as="h2"
/>
}
startActions={
<>
<Button variant="tertiary">Search</Button>
<Button variant="tertiary">Filter</Button>
</>
}
endActions={
<>
<Button variant="tertiary">Settings</Button>
</>
}
startCol={<Box padding={4}>Hello world</Box>}
endCol={<Box padding={4}>Hello world</Box>}
/>
```

Two columns layout

---

packages/strapi-design-system/src/GridLayout/GridLayout.js
packages/strapi-design-system/src/GridLayout/GridLayout.stories.mdx
packages/strapi-design-system/src/GridLayout/__tests__/GridLayout.e2e.js
packages/strapi-design-system/src/GridLayout/index.js
packages/strapi-design-system/src/index.js

```jsx
<GridLayout
header={
<HeaderLayout
primaryAction={<Button startIcon={<AddIcon />}>Add an entry</Button>}
secondaryAction={
<Button variant="tertiary" startIcon={<EditIcon />}>
Edit
</Button>
}
title="Other CT"
subtitle="36 entries found"
as="h2"
/>
}
startActions={
<>
<Button variant="tertiary">Search</Button>
<Button variant="tertiary">Filter</Button>
</>
}
endActions={
<>
<Button variant="tertiary">Settings</Button>
</>
}
>
{Array(12)
.fill(null)
.map((_, idx) => (
<Box padding={4} hasRadius background="neutral0" padding={4} key={`box-${idx}`} shadow="tableShadow">
hello world
</Box>
))}
</GridLayout>
```

Add GridLayout

---

example/src/App.js
example/src/layouts/AppLayout.js
example/src/pages/SettingsPage.js
example/src/shared/SettingsNav/index.js
example/src/shared/SideNav/index.js
example/src/shared/SideNav/utils/menu.js
packages/strapi-design-system/src/MainNav/MainNav.stories.mdx
packages/strapi-design-system/src/MainNav/NavCondense.js
packages/strapi-design-system/src/MainNav/NavUser.js
packages/strapi-design-system/src/SubNav/SubNav.js
packages/strapi-design-system/src/SubNav/SubNav.stories.mdx
packages/strapi-design-system/src/SubNav/SubNavLink.js
packages/strapi-design-system/src/SubNav/__tests__/SubNav.spec.js

- Make sub nav bar aware of react-router-dom
- Add a border to the sub nav bar
- Add a pages in the CRA example

Make sub nav bar aware of react-router-dom

---

packages/strapi-design-system/.storybook/preview.js
packages/strapi-design-system/src/Alert/Alert.stories.mdx
packages/strapi-design-system/src/Link/Link.js
packages/strapi-design-system/src/Link/Link.stories.mdx
packages/strapi-design-system/src/Link/__tests__/Link.spec.js
packages/strapi-design-system/src/Main/SkipToContent.js
packages/strapi-design-system/src/MainNav/MainNav.stories.mdx
packages/strapi-design-system/src/Pagination/Pagination.stories.mdx
packages/strapi-design-system/src/Pagination/__tests__/Pagination.spec.js
packages/strapi-design-system/src/Pagination/components.js
packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js
packages/strapi-design-system/src/SimpleMenu/SimpleMenu.stories.mdx
packages/strapi-design-system/src/SubNav/SubNav.stories.mdx

Basically moves from the `<a>` tag to the `<NavLink>` react-router-dom component (and adjust the according tests)

Replace all HTML links by react-router-dom links

---

example/src/layouts/AppLayout.js
example/src/pages/SettingsPage.js

Just for demo purpose and adding stuff in the CRA, added a settings page

Create a settings page example

---

example/src/pages/MediaLibraryPage.js
packages/strapi-design-system/src/ModalLayout/ModalLayout.js
packages/strapi-design-system/src/ModalLayout/ModalLayout.stories.mdx
packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js

The ModalLayout was showing below the overlay in the CRA app because the modal content was set as a sibling of the modal background
Before:
After:

Fix modal layout

---

packages/strapi-design-system/src/Select/Select.js
packages/strapi-design-system/src/Select/Select.stories.mdx

Add a small size to the Select component.

Add small size Select

---

packages/strapi-design-system/jest.e2e.js
packages/strapi-design-system/src/DatePicker/DatePicker.js
packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx
packages/strapi-design-system/src/DatePicker/DatePickerCalendar.js
packages/strapi-design-system/src/DatePicker/DatePickerTd.js
packages/strapi-design-system/src/DatePicker/DatePickerTh.js
packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.e2e.js
packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.js
packages/strapi-design-system/src/DatePicker/components.js
packages/strapi-design-system/src/DatePicker/utils/formatDate.js
packages/strapi-design-system/src/DatePicker/utils/index.js
packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js
packages/strapi-design-system/src/Table/Cell.js
packages/strapi-design-system/src/Table/__tests__/Table.spec.js
packages/strapi-design-system/src/Text/Text.stories.mdx
packages/strapi-design-system/src/TextInput/TextInput.js

- Take into consideration the QA from @maevalienard 
- Split the file in multiple for clarity
- Added some E2E tests to keep the basic behaviour

Fix DatePicker QA / Refactoring

---

packages/strapi-design-system/package.json
packages/strapi-design-system/src/Field/__tests__/Field.spec.js
packages/strapi-design-system/src/MainNav/__tests__/MainNav.spec.js
packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
packages/strapi-design-system/src/Searchbar/__tests__/Searchbar.spec.js
packages/strapi-design-system/src/SimpleMenu/__tests__/SimpleMenu.spec.js
packages/strapi-design-system/src/TextInput/__tests__/TextInput.spec.js
packages/strapi-design-system/src/Textarea/__tests__/Textarea.spec.js
packages/strapi-design-system/src/helpers/genId.js

- Move uuid to static increment

Move genId to simple increments

---

packages/strapi-parts/src/Alert/Alert.stories.mdx
packages/strapi-parts/src/Alert/__tests__/Alert.e2e.js
packages/strapi-parts/src/Button/Button.stories.mdx
packages/strapi-parts/src/Checkbox/Checkbox.stories.mdx
packages/strapi-parts/src/SimpleMenu/SimpleMenu.stories.mdx

Initialize the docs for some components

Init docs (SimpleMenu, Checkbox, Alert)

---

packages/strapi-parts/src/GridLayout/GridLayout.js
packages/strapi-parts/src/OneBlockLayout/OneBlockLayout.js
packages/strapi-parts/src/TwoColsLayout/TwoColsLayout.js

Fix layout overflow because of table

---

packages/strapi-parts/src/Badge/__tests__/Badge.spec.js
packages/strapi-parts/src/Breadcrumbs/__tests__/Breadcrumbs.spec.js
packages/strapi-parts/src/Button/__tests__/Button.spec.js
packages/strapi-parts/src/Card/__tests__/Card.spec.js
packages/strapi-parts/src/EmptyStateLayout/__tests__/EmptyStateLayout.spec.js
packages/strapi-parts/src/HeaderLayout/__tests__/HeaderLayout.spec.js
packages/strapi-parts/src/MainNav/__tests__/MainNav.spec.js
packages/strapi-parts/src/Pagination/__tests__/Pagination.spec.js
packages/strapi-parts/src/SimpleMenu/__tests__/SimpleMenu.spec.js
packages/strapi-parts/src/Status/__tests__/Status.spec.js
packages/strapi-parts/src/SubNav/__tests__/SubNav.spec.js
packages/strapi-parts/src/Table/__tests__/Table.spec.js
packages/strapi-parts/src/Tag/__tests__/Tag.spec.js
packages/strapi-parts/src/Text/__tests__/Text.spec.js
packages/strapi-parts/src/Text/index.js

Fix default text color

---

packages/strapi-parts/src/IconButton/IconButton.js
packages/strapi-parts/src/IconButton/IconButton.stories.mdx

created IconButtonGroup wrapper

---

packages/strapi-parts/src/Button/Button.js
packages/strapi-parts/src/Button/Button.stories.mdx
packages/strapi-parts/src/IconButton/IconButton.js
packages/strapi-parts/src/IconButton/IconButton.stories.mdx
packages/strapi-parts/src/IconButton/__tests__/IconButton.spec.js
packages/strapi-parts/src/ModalLayout/__tests__/ModalLayout.spec.js
packages/strapi-parts/src/SubNav/__tests__/SubNav.spec.js
packages/strapi-parts/src/Table/__tests__/Table.spec.js

- Style for IconButtonGroup updated
- Style for IconButton disabled created
- onClick event does nothing if disabled state (for IconButton && Button compo)
- DS documentation synchro
- To prevent onClick event to fire when using keyboard
StoryBook!

IconButton state style && disabled state onClick handled (+Button compo)

---

packages/strapi-parts/package.json
packages/strapi-parts/test-bundler.js
packages/strapi-parts/yarn.lock

Make sure to run the tests in en (even when the computer locales is in another language)

Attempt to fix Intl based date

---

example/src/setupTests.js
example/src/shared/Wysiwyg/Editor.js
example/src/shared/Wysiwyg/WysiwygNav.js
example/src/shared/Wysiwyg/WysiwygStyles.js
example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
example/src/shared/Wysiwyg/index.js
example/src/shared/Wysiwyg/utils/continueList.js
example/src/shared/Wysiwyg/utils/utils.js

Main markdowns (bold, italic, etc)
List markdowns (bullet, number)
Title markdowns (h1, h2, h3, etc)

Wysiwyg markdown

---

packages/strapi-parts/src/Popover/Popover.js
packages/strapi-parts/src/Popover/Popover.stories.mdx
packages/strapi-parts/src/Popover/__tests__/Popover.spec.js
packages/strapi-parts/src/Select/__tests__/Select.spec.js
packages/strapi-parts/src/TimePicker/__tests__/TimePicker.spec.js

- Added centered props to popover
- Added centered behavior when centered props
- Added test to popover with centered props
- Added fix if popover overflow left

Popover centered

---

packages/strapi-parts/src/BaseButton/BaseButton.js
packages/strapi-parts/src/BaseButton/__tests__/BaseButton.spec.js
packages/strapi-parts/src/Button/__tests__/Button.spec.js
packages/strapi-parts/src/DatePicker/DatePicker.js
packages/strapi-parts/src/DatePicker/DatePickerTd.js
packages/strapi-parts/src/DatePicker/__tests__/DatePicker.spec.js
packages/strapi-parts/src/EmptyStateLayout/__tests__/EmptyStateLayout.spec.js
packages/strapi-parts/src/Field/FieldAction.js
packages/strapi-parts/src/Field/__tests__/Field.spec.js
packages/strapi-parts/src/IconButton/__tests__/IconButton.spec.js
packages/strapi-parts/src/ModalLayout/__tests__/ModalLayout.spec.js
packages/strapi-parts/src/Searchbar/__tests__/Searchbar.spec.js
packages/strapi-parts/src/Select/SelectButton.js
packages/strapi-parts/src/Select/__tests__/Select.spec.js
packages/strapi-parts/src/SimpleMenu/SimpleMenu.js
packages/strapi-parts/src/SimpleMenu/__tests__/SimpleMenu.spec.js
packages/strapi-parts/src/SubNav/__tests__/SubNav.spec.js
packages/strapi-parts/src/Switch/Switch.js
packages/strapi-parts/src/Switch/__tests__/Switch.spec.js
packages/strapi-parts/src/Table/__tests__/Table.spec.js
packages/strapi-parts/src/TimePicker/__tests__/TimePicker.spec.js

Make sure the button used forms are of type "button"

Fixing the button types

---

packages/strapi-parts/src/Button/Button.js
packages/strapi-parts/src/IconButton/IconButton.js

Make sure we have onclick before calling it

---

packages/strapi-parts/src/Card/Card.stories.mdx
packages/strapi-parts/src/Carousel/Carousel.stories.mdx
packages/strapi-parts/src/Table/Table.stories.mdx

Multiple stories were using the old way to use the IconButton component. This PRs replace them with the new API instead

Fix icon button stories

---

packages/strapi-parts/src/Table/Cell.js
packages/strapi-parts/src/Table/Table.stories.mdx
packages/strapi-parts/src/Table/__tests__/Table.spec.js

Add an `action` prop to the `Th` component for consistently positionning the filter action
```diff
<Th 
+ action={<IconButton label="Hello moto" icon={<HelloMotoIcon />} />}
/>
```

Adding action to th

---

packages/strapi-parts/src/Stack/Stack.js
packages/strapi-parts/src/Stack/Stack.stories.mdx
packages/strapi-parts/src/Stack/__tests__/Stack.spec.js

Add an horizontal prop to the stack component
Example on : https://design-system-git-stack-horizontal-strapijs.vercel.app/?path=/story/design-system-atoms-stack--horizontal
```diff
<Stack
size={4}
+ horizontal
>
<div>First</div>
<div>Second</div>
<div>Third</div>
</Stack>
```

Add horizontal stack

---

packages/strapi-parts/src/Table/Cell.js
packages/strapi-parts/src/Table/__tests__/Table.spec.js

The SVG size applied for the filters on the TH elements was also applied to the TD elements... Actions were a bit soo small in tables 😓

Fix SVG size for TH and not TD

---

lerna.json
package.json
packages/strapi-icons/package.json
packages/strapi-parts/package.json

A better release command

---

packages/strapi-parts/src/Badge/Badge.stories.mdx
packages/strapi-parts/src/Breadcrumbs/Breadcrumbs.stories.mdx

Badge & Breadcrumbs usage documentation
Example on : See link below 👇

Docs Badge & Breadcrumbs

---

packages/strapi-parts/src/Card/Card.stories.mdx

Signed-off-by: Maeva Lienard <maeva.lienard@strapi.io>
Card usage documentation + props

Card documentation

---

packages/strapi-parts/src/Avatar/Avatar.stories.mdx

Documentation Avatar 

---

packages/strapi-parts/src/Accordion/Accordion.stories.mdx

Signed-off-by: Maeva Lienard <maeva.lienard@strapi.io>
Hello, I added some doc for the Accordion compo. 

Doc Accordion

---

packages/strapi-parts/src/Layout/HeaderLayout.js
packages/strapi-parts/src/Layout/HeaderLayout.stories.mdx
packages/strapi-parts/src/Layout/__tests__/HeaderLayout.e2e.js
packages/strapi-parts/src/Stack/Stack.js
packages/strapi-parts/src/helpers/useElementOnScreen.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Adds a container to display the headerlayout in sticky / non-sticky mode depending on the scroll position of the document
https://user-images.githubusercontent.com/3509412/129327747-83fec94d-6897-4fe4-ac12-0334901ba54a.mp4

Add dynamic header layout

---

packages/strapi-parts/src/BaseCheckbox/BaseCheckbox.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Fix checkbox min width

---

packages/strapi-parts/src/TextInput/TextInput.js
packages/strapi-parts/src/TextInput/TextInput.stories.mdx
packages/strapi-parts/src/TextInput/__tests__/TextInput.e2e.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

- Add more stories to text input
- Make sure the `labelAction` has its SVGs being `neutral300`

Add more stories to input

---

packages/strapi-parts/src/Box/Box.js
packages/strapi-parts/src/Row/Row.js
packages/strapi-parts/src/Select/__tests__/Select.spec.js
packages/strapi-parts/src/Stack/Stack.js
packages/strapi-parts/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

- Row component now inherits from Box
- Stack component is now flex column by default, to avoid wrapping inline child component with Box
- Fix flex horizontal css prop

Enhance row and stack components

---

packages/strapi-parts/src/Tabs/Tabs.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Preventing Tab from submitting forms

---

packages/strapi-parts/src/Button/Button.js
packages/strapi-parts/src/Button/Button.stories.mdx
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Add a loading state to the `<Button>` component
Example on : https://design-system-git-loading-button-strapijs.vercel.app/?path=/story/design-system-molecules-button--icons
Adding a `loading` prop that take precedence over the `startIcon`
```diff
<Button
+ loading
>
</Button>
```

Add a loading state to the button

---

packages/strapi-parts/src/LiveRegions/LiveRegions.js
packages/strapi-parts/src/LiveRegions/LiveRegions.stories.mdx
packages/strapi-parts/src/LiveRegions/__tests__/LiveRegions.spec.js
packages/strapi-parts/src/LiveRegions/constants.js
packages/strapi-parts/src/LiveRegions/helpers.js
packages/strapi-parts/src/LiveRegions/index.js
packages/strapi-parts/src/Popover/__tests__/Popover.spec.js
packages/strapi-parts/src/Select/__tests__/Select.spec.js
packages/strapi-parts/src/ThemeProvider/ThemeProvider.js
packages/strapi-parts/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-parts/src/Tooltip/__tests__/Tooltip.spec.js
packages/strapi-parts/src/index.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Adds a way to notify for changes (like loading status) using an imperative API
```js
notifyLog(message: string);
notifyStatus(message: string);
notifyAlert(message: string);
```

Live regions and notify

---

packages/strapi-parts/src/Field/Field.stories.mdx

Docs field

---

packages/strapi-parts/src/LinkButton/LinkButton.js
packages/strapi-parts/src/LinkButton/LinkButton.stories.mdx
packages/strapi-parts/src/LinkButton/__tests__/LinkButton.e2e.js
packages/strapi-parts/src/LinkButton/index.js
packages/strapi-parts/src/index.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Example on : https://design-system-git-link-button-strapijs.vercel.app/?path=/story/design-system-molecules-linkbutton--base
Same as the Button one except that it accepts a `href` or a `to` prop. `href` is for external usages

Add a semantic link that looks like a button

---

example/src/shared/Wysiwyg/MediaLibrary.js
example/src/shared/Wysiwyg/WysiwygNav.js
example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
example/src/shared/Wysiwyg/index.js
example/src/shared/Wysiwyg/utils/utils.js

Created fake MediaLib component to insert images as link markdown
Do not merge before Wysiwyg Layout && Preview PR is merged

Wysiwyg MediaLibrary (to merge after Wysiwyg Layout && Preview PR)

---

packages/strapi-parts/src/Accordion/AccordionToggle.js

Add type="button" to avoid form submit

AccordionToggle is of type button

---

packages/strapi-parts/src/Carousel/Carousel.stories.mdx

Carousel documentation (usage + props). 

Carousel documentation

---

example/src/shared/PreviewWysiwyg/Wrapper.js
example/src/shared/Wysiwyg/WysiwygNav.js
example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
example/src/shared/Wysiwyg/index.js
example/src/shared/Wysiwyg/utils/utils.js

if Code or Quote + content in current line : go to next line before inserting markdown text

Code && Quote markdown create new line

---

package.json
packages/strapi-parts/src/Select/MultiSelectNested.js
packages/strapi-parts/src/Select/OptGroup.js
packages/strapi-parts/src/Select/Option.js
packages/strapi-parts/src/Select/Select.js
packages/strapi-parts/src/Select/Select.stories.mdx
packages/strapi-parts/src/Select/SelectList.js
packages/strapi-parts/src/Select/__tests__/Select.spec.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
yarn.lock

Multi select nested

---

packages/strapi-parts/src/ToggleInput/ToggleInput.js
packages/strapi-parts/src/ToggleInput/ToggleInput.stories.mdx
packages/strapi-parts/src/ToggleInput/__tests__/ToggleInput.e2e.js
packages/strapi-parts/src/ToggleInput/index.js
packages/strapi-parts/src/index.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

ToggleInput component => ToggleCheckbox component + Fields components to add description, labels, error etc

ToggleInput component

---

packages/strapi-parts/src/BaseButton/BaseButton.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Add the  disabled props on BaseButton

Fix disabled props on basebutton

---

packages/strapi-parts/src/TextButton/TextButton.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Text button type button

---

packages/strapi-parts/src/MainNav/MainNav.stories.mdx
packages/strapi-parts/src/MainNav/NavLink.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Added notifications props to MainNav/NavLink

MainNav notifications

---

packages/strapi-parts/src/Dialog/Dialog.js
packages/strapi-parts/src/Dialog/Dialog.stories.mdx
packages/strapi-parts/src/Dialog/__tests__/Dialog.spec.js
packages/strapi-parts/src/ModalLayout/ModalLayout.js
packages/strapi-parts/src/ThemeProvider/ThemeProvider.js
packages/strapi-parts/src/helpers/useLockScroll.js

Let Dialog component deal with being open or not with a prop
Updated useEffect overflow and tests

Dialog isOpen props

---

packages/strapi-parts/src/IconButton/IconButton.stories.mdx
packages/strapi-parts/src/Layout/HeaderLayout.stories.mdx

Docs - HeaderLayout and IconButton + props and import for each.

Docs - HeaderLayout and IconButton

---

packages/strapi-parts/src/Radio/Radio.stories.mdx
packages/strapi-parts/src/Searchbar/Searchbar.stories.mdx

Docs for the Radio button and the SearchBar + props for each

Docs - Radio & SearchBar

---

packages/strapi-parts/src/Status/Status.stories.mdx
packages/strapi-parts/src/SubNav/SubNav.stories.mdx

Docs - Status & SubNav and props for each

Docs - Status & SubNav

---

packages/strapi-parts/src/MainNav/MainNav.stories.mdx
packages/strapi-parts/src/Switch/Switch.stories.mdx

MainNavigation & Switch docs and props for each. 

Docs - MainNavigation & Switch

---

packages/strapi-parts/src/Table/Table.stories.mdx
packages/strapi-parts/src/Tabs/Tabs.stories.mdx

Table and Tabs documentation and props for each. 

Docs table tabs

---

packages/strapi-parts/src/Tag/Tag.stories.mdx
packages/strapi-parts/src/TextButton/TextButton.stories.mdx
packages/strapi-parts/src/ToggleCheckbox/ToggleCheckbox.stories.mdx

Tag, TextButton & Toggle docs, and props for each.

Docs - Tag, TextButton & Toggle

---

packages/strapi-parts/src/BaseButton/BaseButton.stories.mdx

Attempt to document the BaseButton Component. Not sure this is enough info.

Docs - Basebutton

---

packages/strapi-parts/webpack.config.js

Add devtools

---

packages/strapi-parts/src/Select/Option.js
packages/strapi-parts/src/Select/Select.js

Fix some prop-types

---

packages/strapi-parts/src/Box/Box.js
packages/strapi-parts/src/Field/FieldInput.js
packages/strapi-parts/src/Layout/ActionLayout.js
packages/strapi-parts/src/Layout/Layout.stories.mdx
packages/strapi-parts/src/Searchbar/Searchbar.js
packages/strapi-parts/src/Searchbar/Searchbar.stories.mdx
packages/strapi-parts/src/Textarea/TextareaInput.js
packages/strapi-parts/src/ToggleInput/ToggleInput.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

- Box can now have a children of string
- Outline is well offsetted on input elements
- ToggleInput receives the destructured name attribute
- ActionLayout wrap

Minor fixes on component props and outline

---

packages/strapi-parts/src/Avatar/Avatar.js
packages/strapi-parts/src/Avatar/Avatar.stories.mdx
packages/strapi-parts/src/Avatar/AvatarGroup.js
packages/strapi-parts/src/Avatar/__tests__/Avatar.spec.js
packages/strapi-parts/src/Avatar/constants.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Add `<AvatarGroup>` component
```jsx
<AvatarGroup>
<Avatar src="https://avatars.githubusercontent.com/u/3874873?v=4" alt="marvin frachet" preview />
<Avatar src="https://avatars.githubusercontent.com/u/3874873?v=4" alt="marvin frachet" preview />
<Avatar src="https://avatars.githubusercontent.com/u/3874873?v=4" alt="marvin frachet" preview />
</AvatarGroup>
```

Avatar group

---

example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
example/yarn.lock
packages/strapi-parts/src/Card/Card.stories.mdx
packages/strapi-parts/src/Card/CardAsset.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Add a children to `CardAsset` to pass icons instead of images when necessary
```jsx
<CardAsset>
<Icon />
</CardAsset>
```
or 
```jsx
<CardAsset src="url" />
```

CardAsset with a children

---

example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
packages/strapi-parts/src/Field/FieldInput.js
packages/strapi-parts/src/TextInput/TextInput.stories.mdx
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Rely on aria-disabled so that the element is still focusable

Fix input disabled for ATs

---

packages/strapi-parts/src/Carousel/Carousel.js
packages/strapi-parts/src/Combobox/Combobox.js
packages/strapi-parts/src/Combobox/Combobox.stories.mdx
packages/strapi-parts/src/Combobox/ComboboxOption.js
packages/strapi-parts/src/Combobox/__tests__/Combobox.e2e.js
packages/strapi-parts/src/Combobox/components.js
packages/strapi-parts/src/Combobox/index.js
packages/strapi-parts/src/Combobox/utils.js
packages/strapi-parts/src/KeyboardNavigable/KeyboardNavigable.js
packages/strapi-parts/src/Loader/Loader.js
packages/strapi-parts/src/RawTable/RawTable.js
packages/strapi-parts/src/Tabs/Tabs.js
packages/strapi-parts/src/helpers/keyboardKeys.js

From 
https://www.24a11y.com/2019/select-your-poison/
https://www.24a11y.com/2019/select-your-poison-part-2/

Add combobox

---

packages/strapi-parts/src/Combobox/index.js
packages/strapi-parts/src/ModalLayout/ModalBody.js
packages/strapi-parts/src/ModalLayout/ModalLayout.js
packages/strapi-parts/src/ModalLayout/ModalLayout.stories.mdx
packages/strapi-parts/src/index.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Fix modal content that can't be scrollable when it's too big

Fix modal scroll

---

packages/strapi-parts/src/Card/Card.stories.mdx

the DS documentation import was wrong so it's fixed

Fix Card import

---

packages/strapi-parts/src/Select/Option.js
packages/strapi-parts/src/Select/Select.stories.mdx

Add icon to option
https://design-system-git-add-icons-to-option-strapijs.vercel.app/?path=/story/design-system-molecules-select--base

Add startIcon to option

---

packages/strapi-parts/src/MainNav/MainNav.js
packages/strapi-parts/src/MainNav/MainNav.stories.mdx
packages/strapi-parts/src/MainNav/NavCondense.js
packages/strapi-parts/src/MainNav/NavLink.js
packages/strapi-parts/src/Table/Table.stories.mdx
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Fix main nav

---

example/src/CM/Inputs.js
example/src/shared/Wysiwyg/Editor.js
example/src/shared/Wysiwyg/WysiwygStyles.js
example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
example/src/shared/Wysiwyg/index.js

Added error state to WYSIWYG + test

Wysiwyg error state

---

example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
packages/strapi-parts/src/IconButton/IconButton.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Fixed IconButton size to 32px instead of 30px

IconButton size

---

packages/strapi-parts/src/Card/CardBadge.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Added flex-shrink 0 to CardBadge wrapper

CardBadge skrink issue

---

packages/strapi-parts/src/Layout/ActionLayout.js
packages/strapi-parts/src/Layout/Layout.stories.mdx
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Fixed actions layout:
- Added flex-start
- Removed Wrap for endActions

Action layout endActions fix

---

packages/strapi-parts/src/Button/Button.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Added align center to align Button and Icon everytime if not alignment seems random
Main app
CTB aligned
CM not aligned

Button align center

---

.github/workflows/playwright-ci.yml
example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
packages/strapi-parts/src/Avatar/Avatar.js
packages/strapi-parts/src/Avatar/Avatar.stories.mdx
packages/strapi-parts/src/MainNav/MainNav.stories.mdx
packages/strapi-parts/src/MainNav/NavUser.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Added new behavior for NavUser with NavUserInitials => 
need to be clickable and not a NavLink
need to attach a ref for future popover

NavUserInitials

---

packages/strapi-parts/src/Table/Tr.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

To prevent jumps when the caret appears

Fix the height of the TH elements

---

example/src/CM/index.js
packages/strapi-parts/src/Dialog/Dialog.js
packages/strapi-parts/src/Layout/HeaderLayout.js
packages/strapi-parts/src/Layout/HeaderLayout.stories.mdx
packages/strapi-parts/src/ModalLayout/ModalLayout.js
packages/strapi-parts/src/Popover/Popover.js
packages/strapi-parts/src/Popover/__tests__/Popover.spec.js
packages/strapi-parts/src/Select/__tests__/Select.spec.js
packages/strapi-parts/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-parts/src/Tooltip/Tooltip.js
packages/strapi-parts/src/Tooltip/__tests__/Tooltip.spec.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Should eventually fix the zIndex problem + shadows

---

packages/strapi-parts/src/Layout/ActionLayout.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Added flex-shrink 0 to end actions in action layout to prevent components to skrink

Action Layout skrink fix

---

packages/strapi-parts/src/MainNav/MainNav.stories.mdx
packages/strapi-parts/src/MainNav/NavSections.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Fix the right padding of the main nav so that the CTB name fits in one line

Fix main nav padding

---

packages/strapi-parts/src/Accordion/Accordion.stories.mdx
packages/strapi-parts/src/BaseCheckbox/BaseCheckbox.stories.mdx
packages/strapi-parts/src/BaseRadio/BaseRadio.stories.mdx
packages/strapi-parts/src/Box/Box.stories.mdx
packages/strapi-parts/src/Box/BoxProps.js
packages/strapi-parts/src/Combobox/Combobox.stories.mdx
packages/strapi-parts/src/IconButton/IconButton.stories.mdx
packages/strapi-parts/src/Row/Row.stories.mdx
packages/strapi-parts/src/Row/RowProps.js
packages/strapi-parts/src/themes/Theme.stories.mdx

Add ArgsTable for Box and Row components
[api details]
```jsx
```

Made some improvements

---

packages/strapi-parts/src/Grid/GridItem.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Fixed break-all behavior in GridItem

Break-all Fixed

---

packages/strapi-parts/src/Dialog/Dialog.js
packages/strapi-parts/src/ModalLayout/ModalLayout.js
packages/strapi-parts/src/helpers/useClickAwayListener.js

Fix modal position & click away to close

---

packages/strapi-parts/src/Combobox/components.js
packages/strapi-parts/src/DatePicker/DatePicker.js
packages/strapi-parts/src/DatePicker/DatePicker.stories.mdx
packages/strapi-parts/src/Field/Field.stories.mdx
packages/strapi-parts/src/Field/FieldInput.js
packages/strapi-parts/src/NumberInput/NumberInput.js
packages/strapi-parts/src/NumberInput/NumberInput.stories.mdx
packages/strapi-parts/src/Searchbar/Searchbar.js
packages/strapi-parts/src/Searchbar/Searchbar.stories.mdx
packages/strapi-parts/src/Select/Select.js
packages/strapi-parts/src/Select/Select.stories.mdx
packages/strapi-parts/src/Select/__tests__/Select.spec.js
packages/strapi-parts/src/Select/components.js
packages/strapi-parts/src/SubNav/SubNavHeader.js
packages/strapi-parts/src/TextInput/TextInput.js
packages/strapi-parts/src/TextInput/TextInput.stories.mdx
packages/strapi-parts/src/ThemeProvider/ThemeProvider.js
packages/strapi-parts/src/TimePicker/TimePicker.js
packages/strapi-parts/src/TimePicker/TimePicker.stories.mdx
packages/strapi-parts/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-parts/src/ToggleCheckbox/ToggleCheckbox.js
packages/strapi-parts/src/ToggleCheckbox/ToggleCheckbox.stories.mdx
packages/strapi-parts/src/ToggleInput/ToggleInput.js
packages/strapi-parts/src/ToggleInput/ToggleInput.stories.mdx
packages/strapi-parts/src/themes/__tests__/extendTheme.spec.js
packages/strapi-parts/src/themes/light-theme.js
packages/strapi-parts/src/themes/sizes.js
packages/strapi-parts/src/themes/utils.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Integrated theme sizes to have a homogeneous way to deal with inputs/buttons height
- DatePicker
- FieldInput
- NumberInput
- SearchBar
- Select
- SubNavHeader (SearchBar)
- TextInput
- TimePicker
- ToggleCheckbox
- ToggleInput
=> https://design-system-git-theme-sizes-strapijs.vercel.app

Theme sizes

---

packages/strapi-parts/src/Alert/Alert.js
packages/strapi-parts/src/BaseButton/BaseButton.js
packages/strapi-parts/src/Field/FieldInput.js
packages/strapi-parts/src/Link/Link.js
packages/strapi-parts/src/Pagination/components.js
packages/strapi-parts/src/Searchbar/Searchbar.js
packages/strapi-parts/src/Select/__tests__/Select.spec.js
packages/strapi-parts/src/Select/components.js
packages/strapi-parts/src/TextButton/TextButton.js
packages/strapi-parts/src/Textarea/Textarea.js
packages/strapi-parts/src/Textarea/TextareaInput.js
packages/strapi-parts/src/ThemeProvider/ThemeProvider.js
packages/strapi-parts/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-parts/src/ToggleCheckbox/ToggleCheckbox.js
packages/strapi-parts/src/themes/index.js
packages/strapi-parts/src/themes/utils.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Adjusting focus styles

---

packages/strapi-parts/src/Box/Box.js
packages/strapi-parts/src/Box/Box.stories.mdx
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Add
- borderStyle
- borderWidth
- borderColor
props to the box component

Box border

---

packages/strapi-parts/src/Table/Table.js
packages/strapi-parts/src/Table/Table.stories.mdx
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

- https://design-system-git-fix-table-radius-strapijs.vercel.app/?path=/story/design-system-components-table--base
- https://design-system-git-fix-table-radius-strapijs.vercel.app/?path=/story/design-system-components-table--base-without-footer

Fix table radius

---

packages/strapi-parts/src/Tabs/Tabs.js
packages/strapi-parts/src/Tabs/Tabs.stories.mdx

Add onClick event to tab

---

packages/strapi-parts/src/Accordion/AccordionContent.js
packages/strapi-parts/src/Box/Box.js
packages/strapi-parts/src/Icon/Icon.js
packages/strapi-parts/src/Icon/index.js
packages/strapi-parts/src/RawTable/RawCell.js
packages/strapi-parts/src/RawTable/RawTr.js
packages/strapi-parts/src/index.js
packages/strapi-parts/src/themes/Theme.stories.mdx
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

- Improve box component adding more properties for positionning
- Add Icon component and ways to override its internal colors

Improve box and icon

---

packages/strapi-parts/src/Combobox/Combobox.js
packages/strapi-parts/src/Combobox/Combobox.stories.mdx
packages/strapi-parts/src/Combobox/ComboboxList.js
packages/strapi-parts/src/Combobox/__tests__/Combobox.e2e.js
packages/strapi-parts/src/Combobox/components.js
packages/strapi-parts/src/Combobox/utils.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Combobox creatable

---

packages/strapi-parts/src/TimePicker/TimePicker.js
packages/strapi-parts/src/TimePicker/TimePicker.stories.mdx
packages/strapi-parts/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap

Temporary fix: Select the closest value in the list to support initial value with seconds

Fix TimePicker

---

packages/strapi-design-system/src/Field/FieldLabel.js
packages/strapi-design-system/src/TimePicker/TimePicker.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Some fix on the timepicker component

Fix time picker

---

example/src/shared/SideNav/utils/menu.js
packages/strapi-design-system/src/Table/Table.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Fixed table inner shadow => checked with design
The shadow was too strong

Table inner shadow fixed

---

packages/strapi-design-system/src/SubNav/SubNav.stories.mdx
packages/strapi-design-system/src/SubNav/SubNavHeader.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Fixed alignment between Label and Search button
QA request: when Label takes 2 lines the alignment should not be centered but flex-start
before
after

QA/ Subnav Header alignment

---

packages/strapi-design-system/src/Select/Select.js
packages/strapi-design-system/src/Select/__tests__/Select.spec.js
packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Fix select placeholder

---

packages/strapi-design-system/src/Tabs/TabGroup.js
packages/strapi-design-system/src/Tabs/Tabs.stories.mdx
packages/strapi-design-system/src/Tabs/__tests__/Tabs.e2e.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Add ability to choose which tab is initially selected

---

packages/strapi-design-system/src/Button/Button.js

Fix button proptypes

---

packages/strapi-design-system/src/Typography/Typography.stories.mdx
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Added a detailed story for Typography component based on figma design tokens

Detailed story for Typography

---

packages/strapi-design-system/src/Accordion/Accordion.js
packages/strapi-design-system/src/Accordion/Accordion.stories.mdx
packages/strapi-design-system/src/Accordion/AccordionGroup.js
packages/strapi-design-system/src/Accordion/AccordionToggle.js

Accordion and AccordionGroup error state
If only Accordion, it applies border and error message
If AccordionGroup, AccordionGroup applies error message and Accordion applies border

Accordion error state

---

packages/strapi-design-system/src/Select/__tests__/Select.spec.js
packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-design-system/src/Typography/Typography.stories.mdx
packages/strapi-design-system/src/Typography/utils.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Fixed Typography ellipsis (needed display block)
Added ellipsis example in Typography stories

Typography ellipsis fix

---

packages/strapi-design-system/src/Select/SelectTags.js
packages/strapi-design-system/src/Tag/Tag.js
packages/strapi-design-system/src/Tag/Tag.stories.mdx
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Add disabled look to the Tag component (repercuted on the Select with tags)
https://design-system-git-select-tag-disabled-strapijs.vercel.app/?path=/story/design-system-components-tag--disabled

Disable style on Select tags

---

packages/strapi-design-system/src/Tabs/TabGroup.js

Add ref to TabGroup

---

packages/strapi-design-system/src/NumberInput/NumberInput.js
packages/strapi-design-system/src/NumberInput/NumberInput.stories.mdx
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Added required props to NumberInput

NumberInput required

---

packages/strapi-design-system/src/Textarea/Textarea.stories.mdx
packages/strapi-design-system/src/Textarea/TextareaInput.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Fixed Textarea disabled state UI 
Before
After

Textarea disabled UI

---

packages/strapi-design-system/src/Select/SelectTags.js

Fixed removing a tag from select multi tags causing bug

Select multi tags / Remove a tag issue

---

packages/strapi-design-system/src/Field/FieldLabel.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Attempt to fix inputs alignment when required field next to not required field
before
after

Input alignment required issue

---

packages/strapi-design-system/src/NumberInput/NumberInput.js
packages/strapi-design-system/src/NumberInput/NumberInput.stories.mdx
packages/strapi-design-system/src/NumberInput/__tests__/NumberInput.e2e.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Fixed NumberInput not activating onValueChange when clicking on arrows up/down
Added disabled state 
Added tests
Click on arrows to change the value
The value should update immediately (not on blur)

NumberInput arrow click issue

---

packages/strapi-design-system/src/NumberInput/NumberInput.js

Fixing the number input delanoche

Fix number input

---

packages/strapi-design-system/src/MainNav/MainNav.stories.mdx
packages/strapi-design-system/src/MainNav/NavUser.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Added ellipsis for NavUser name

[QA] Nav user name ellipsis

---

packages/strapi-design-system/src/Layout/HeaderLayout.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Fixed HeaderLayout padding bottom too big
Fixed HeaderLayout padding with or without nagivation link 
Fixed padding between title and navigation link

[QA] Header padding

---

CONTRIBUTING.md
lerna.json
package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json

- Init the contributing guide
- Upgrade version
- Update the root package.json scripts

Init contributing guide

---

packages/strapi-design-system/src/Carousel/Carousel.js
packages/strapi-design-system/src/Carousel/Carousel.stories.mdx
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Add a secondary label to the carousel

Add secondary label to the carousel component

---

packages/strapi-design-system/package.json
packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.e2e.js
packages/strapi-design-system/yarn.lock

Bump playwright to ^1.17.0
Previous version was crashing e2e tests on M1

Bump playwright to ^1.17.0

---

packages/strapi-design-system/src/CarouselInput/index.js

Fix export for CarouselInput 🥲

Fix - Export for CarouselInput

---

CONTRIBUTING.md

This makes the contribution part a bit more explicit about which parts shouldn't be edited.

Docs: improve wording of contributing guide

---

packages/strapi-design-system/src/Card/CardAction.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

This allows `CardActions`s to contain more than one child. By using the `Stack` component, multiple children will be shown properly.
Refs: https://github.com/strapi/strapi/pull/12428

Card: Properly handle multiple children in CardAction 

---

website/pages/_document.js

Added google tag manager and cookie bot
Example on: https://design-system-website-git-add-google-analytics-strapijs.vercel.app/

add google tag manager

---

packages/strapi-design-system/src/Select/Select.js
packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Specify `type="button"` to select clear button

Fix - Select clear button type

---

packages/strapi-design-system/src/Icon/Icon.stories.mdx
packages/strapi-design-system/src/Icon/__tests__/Icon.e2e.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Icon component story, e2e test + snapshot

Icon story + tests

---

packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx
packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.e2e.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Fixed Datepicker story using text without theme that broke Datepicker e2e tests in dark mode

Datepicker e2e tests

---

packages/strapi-design-system/src/Table/Table.stories.mdx

A single line has been added in Table component to let the users know about the use of the EmptyStatelayout.

Added information about the EmptyState in Table component

---

.github/workflows/playwright-ci.yml
packages/strapi-design-system/package.json

Fix the playwright version for the CI

Fix e2e test & CI

---

packages/strapi-design-system/src/Select/__tests__/Select.spec.js
packages/strapi-design-system/src/Stack/Stack.js
packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Move vertical stack from Box to Flex with direction set to column
Align-items set to stretch to keep previous UI behavior
See DS Jira ticket DS-14
Will allow StackV to handle flex props (align-items, justify-content)
Remove some needs to customize Stack with styled-props

Move vertical stack from Box to Flex with direction set to column

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/pull_request_template.md

Keep the same github issue & PR templates we have in the Strapi repo.

Add ISSUE_TEMPLATE and improve PULL_REQUEST_TEMPLATE

---

packages/strapi-design-system/src/Combobox/Combobox.js
packages/strapi-design-system/src/Select/Select.js
packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js
packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.js

Prevent default on click event.
Fix Select usage on React 18 projects

Fix click for React 18

---

lerna.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json

Releasing 1.2.0

---

packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js
packages/strapi-design-system/src/ToggleInput/ToggleInput.stories.mdx
packages/strapi-design-system/src/ToggleInput/__tests__/ToggleInput.e2e.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Steps to reproduce:
- Set the default value of ToggleCheckbox as true
- Clear the value
- Change/toggle value
- Value will be set to false
- Clicking when value is null should change the value to true
- Fixed `Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen` error message
fix #645

Fix ToggleCheckbox value

---

packages/strapi-design-system/src/SubNav/SubNavLink.js
packages/strapi-design-system/src/v2/SubNav/SubNav.stories.mdx
packages/strapi-design-system/src/v2/SubNav/SubNavLink.js
packages/strapi-design-system/src/v2/SubNav/SubNavLinkSection.js
packages/strapi-design-system/src/v2/SubNav/SubNavSection.js
packages/strapi-design-system/src/v2/SubNav/SubNavSectionLabel.js
packages/strapi-design-system/src/v2/SubNav/SubNavSections.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Applies all changes from https://github.com/strapi/design-system/pull/635 to the v2 version of the component.
To be in sync between v1 and v2.

Subnav (v2): Improve styling of child links

---

packages/strapi-design-system/src/Grid/Grid.stories.mdx
packages/strapi-design-system/src/Link/Link.stories.mdx
packages/strapi-design-system/src/themes/Theme.stories.mdx

This PR is meant to update some documentation in the Design System Storybook: Grid, Link, and Theme documentations.

Update Grid, Link, and Theme documentation of the Design System

---

packages/strapi-design-system/src/Button/Button.js
packages/strapi-design-system/src/Loader/Loader.js
packages/strapi-design-system/src/TextButton/TextButton.js
packages/strapi-design-system/src/TextButton/TextButton.stories.mdx
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

Added missing loading state for TextButton
Used the same UI as Button

[Fix] TextButton loading state

---

lerna.json
packages/strapi-design-system/package.json
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
packages/strapi-icons/package.json

Releasing 1.2.4

---

packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.js
packages/strapi-design-system/src/v2/Breadcrumbs/__tests__/Breadcrumbs.spec.js

Flatten the breadcrumb children and add tests.
To avoid falsy values to be taken into account during the children.map

Fix Breadcrumb with conditional links

---

website/components/Navbar/index.js

Updates the Navbar and adds the missing forum link

Adds the missing forum link

---

packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js
packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.stories.mdx
packages/strapi-design-system/src/ToggleInput/ToggleInput.js
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap

* Sets the padding to be 12px (as per Design Team instruction)
* Ensures the component obeys it's containers layout properties (e.g grid)
On the content manager it crashes into other components if in a grid view at reasonable breakpoints (e.g. not extremes like 720px)
CONTENT-571

[fix][ToggleCheckbox]: responsive behaviour

---

packages/strapi-design-system/src/DatePicker/DatePickerCalendar.js
packages/strapi-design-system/src/Icon/Icon.stories.mdx
packages/strapi-design-system/src/Link/Link.stories.mdx
packages/strapi-design-system/src/SimpleMenu/SimpleMenu.stories.mdx
packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.stories.mdx
packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
website/.lintstagedrc.js
website/components/BottomNavigation/index.js
website/components/Navbar/index.js

What does it do?
It tries to remove all the warnings in the unit tests and e2e tests
Why is it needed?
to have proper logs when running the tests
How to test it?
you can run both the tests with these commands
Try to remove the warnings, prevent errors and warnings from the:
unit tests, you can run them with the command
`yarn test:watch`
E2E tests, you can run them with the command
`yarn test:e2e`
Related issue(s)/PR(s)
It is related to this ticket https://strapi-inc.atlassian.net/jira/software/c/projects/DX/boards/9?modal=detail&selectedIssue=DX-465

Cleaning and/or solving the frontend tests (warning/logs)

---

lerna.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json

Push the updated package versions 1.2.6

Releasing 1.2.6

---

lerna.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json

[release]: 1.2.8

---

packages/strapi-design-system/package.json
packages/strapi-icons/package.json

chore: remove side-effects from package.json

---

lerna.json
packages/strapi-design-system/package.json
packages/strapi-design-system/vite.config.js
packages/strapi-icons/package.json
packages/strapi-icons/vite.config.js

[release]: 1.3.1

---

lerna.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json

[release] 1.4.0

---

lerna.json
package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json

[release]: v1.4.1

---

LICENSE

It updates the license year
Because we are in 2023 now

Update the license to "present"

---

packages/strapi-design-system/src/Table/Cell.js
packages/strapi-design-system/src/Table/Table.stories.mdx
packages/strapi-design-system/src/Tooltip/Tooltip.js
packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.js

Reverts strapi/design-system#819

Revert "[fix] Tooltip misalignment "

---

.prettierignore
docs/package.json
lerna.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json

[Release]: 1.6.0

---

packages/strapi-design-system/src/Avatar/Avatar.tsx
packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.tsx
packages/strapi-design-system/src/Card/CardHeader.tsx
packages/strapi-design-system/src/Card/CardTimer.tsx
packages/strapi-design-system/src/Dialog/Dialog.js
packages/strapi-design-system/src/Layout/HeaderLayout.js
packages/strapi-design-system/src/Main/SkipToContent.js
packages/strapi-design-system/src/MainNav/MainNav.js
packages/strapi-design-system/src/MainNav/NavFooter.js
packages/strapi-design-system/src/ModalLayout/ModalLayout.js
packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
packages/strapi-design-system/src/Select/Option.js
packages/strapi-design-system/src/Select/SelectTags.js
packages/strapi-design-system/src/Select/__tests__/Select.spec.js
packages/strapi-design-system/src/Table/Table.js
packages/strapi-design-system/src/Tooltip/Tooltip.js
packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.js
packages/strapi-design-system/src/v2/MainNav/MainNav.js
packages/strapi-design-system/src/v2/MainNav/NavFooter.js

Box `position` props was defined but not documented and often not used when it could have been
- documented with proptypes
- used as prop instead of custom style in numerous components
- larger cleanup by using `Box` props instead of custom

[chore] Box position 

---

.github/workflows/bundle-size.yml
docs/.storybook/main.js
lerna.json
package.json
yarn.lock

* removes storybook from `develop` scope
* uses workspaces in `lerna`
* because deps were being confused
* the packages need to be built before `storybook` and with `parallel` (which is meant for long running tasks) it would fail – a lot.

[Lerna]: handle parallel with storybook

---

packages/strapi-design-system/src/Combobox/Combobox.js
packages/strapi-design-system/src/DateTimePicker/DateTimePicker.js
packages/strapi-design-system/src/DateTimePicker/__tests__/__snapshots__/DateTimePicker.spec.js.snap
packages/strapi-design-system/src/Field/FieldHint.js
packages/strapi-design-system/src/Select/Select.js
packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js

Following up on [this discussion](https://github.com/strapi/design-system/pull/815#pullrequestreview-1247872060) 
Ensure all inputs are displaying the right attributes to ensure the accessibility of hints 
Check inputs attributes when displaying hints or errors

[fix] Inputs hint accessibility

---

CONTRIBUTING.md

Since storybook was moved I think a few things have changed here
So it is clear for everyone how to start developing with storybook
Follow the steps

[chore] update contributing

---

CONTRIBUTING.md
docs/package.json
lerna.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json

[release]: v1.6.2

---

packages/strapi-design-system/src/Typography/Typography.tsx

Add `textDecoration` prop to `Typography` component

[enh] Typography textDecoration

---

docs/.storybook/main.js
docs/.storybook/preview.js
docs/package.json
docs/stories/primitives/Combobox.stories.mdx
docs/tsconfig.json
packages/primitives/README.md
packages/primitives/package.json
packages/primitives/src/Listbox/__tests__/index.test.ts
packages/primitives/src/Listbox/index.ts
packages/primitives/src/components/Combobox/Combobox.tsx
packages/primitives/src/components/Combobox/__tests__/index.test.tsx
packages/primitives/src/components/Combobox/index.ts
packages/primitives/src/hooks/useCollator.ts
packages/primitives/src/hooks/useFilter.ts
packages/primitives/src/index.ts
packages/primitives/vite.config.ts
yarn.lock

* Adds a new combobox primitive to be used in refactoring of the combobox made in a composable manor
* needed to abstract the accessibility logic of the DS combobox
* automated tests 🪄

Add combobox primitive

---

docs/components/DeprecationNotice.js
docs/stories/Breadcrumbs.stories.mdx
docs/stories/Link.stories.mdx
docs/stories/LinkButton.stories.mdx
docs/stories/MainNav.stories.mdx
docs/stories/Pagination.stories.mdx
docs/stories/SimpleMenu.stories.mdx
docs/stories/Stack.stories.mdx
docs/stories/SubNav.stories.mdx
docs/stories/v2/MainNav.stories.mdx

* Adds deprecation notice in storybook about V1 components
* We have V2 and supporting two of the same component is on overhead we don't need.

Add deprecate notice to v1 components

---

.github/workflows/experimental.yml

* changes repo name to `strapi/design-system`
* the experimental release action will be skipped otherwise

fix: release workflow (repo-name)

---

website/pages/_document.js

Update GTM container ID. This way, the cloud team will have its own container in GTM to manage events they want to track.

Update: GTM container ID

---

docs/stories/TextButton.stories.mdx
packages/strapi-design-system/src/TextButton/TextButton.tsx

- Replaces the inline-paddings with gap
- Splits out a separate icon story
- Simplify markup
The component was a bit messy.

TextButton: Cleanup component

---

website/components/MarkdownComponents/ColorShades.jsx
website/components/MarkdownComponents/ColorSummary.jsx
website/components/MarkdownComponents/Typography.jsx
website/components/MarkdownComponents/color.js
website/components/MarkdownComponents/index.js
website/data/pages/colors.mdx
website/package.json
website/yarn.lock

Transforming, from images to HTML/selectable content, the Colors page of Strapi DS Website.
Will help the community to select/use/copy the Strapi DS color tokens more easier.

Improve DS Website Colors page

---

packages/primitives/src/components/Combobox/Combobox.tsx
packages/primitives/src/components/Combobox/__tests__/index.test.tsx
packages/primitives/src/components/Select/Select.tsx
packages/strapi-design-system/src/Combobox/Combobox.tsx
packages/strapi-design-system/src/Select/MultiSelect.tsx
packages/strapi-design-system/src/Select/SelectParts.tsx

* clears selection range for firefox bug
* Fixes when we should apply on the onBlur callback on the Combobox input (hint it's not on blur)
* fix some pointer styles
* some bugs @gu-stav found

Select / Combobox refinements

---

.husky/pre-commit
docs/package.json
package.json
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-design-system/src/Select/SelectList.tsx
packages/strapi-icons/package.json
yarn.lock

* Updates some deps by major versions
* removes lint-staged to use NX
* Adds some additional helpful checks to the `pre-commit` hook
* removes using `rm -rf` because some people use windows
* codebase hygiene
* the CI will tell all
* Should be merged after #962

Update major deps

---

lerna.json
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-design-system/src/Combobox/Combobox.tsx
packages/strapi-design-system/src/Select/SelectParts.tsx
packages/strapi-icons/package.json
yarn.lock

[release]: 1.7.3

---

packages/strapi-design-system/src/DatePicker/DatePicker.tsx
packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.tsx

* When you type a value into the input, the calendar updates with what you're typing
* It would be weird otherwise
* Automated tests 🪄

Let the DateInput control the DateCalendar

---

packages/strapi-design-system/src/Combobox/Combobox.tsx
packages/strapi-design-system/src/Select/MultiSelect.tsx
packages/strapi-design-system/src/Select/SingleSelect.tsx

* Select / Combobox now handle null values
* this was a breaking change we didn't see

Select & Combobox in the DS should accept nullish values

---

docs/.storybook/components/Theme.js
packages/primitives/src/components/Combobox/Combobox.tsx
packages/strapi-design-system/src/DatePicker/DatePicker.tsx
packages/strapi-design-system/src/DateTimePicker/DateTimePicker.tsx
packages/strapi-design-system/src/TimePicker/TimePicker.tsx

* Sets min widths to ensure the inputs are always readable in DateTimePicker
* Sets default locale to `en` to match the CMS
* Ensures time is always 24H in TimePicker
* Uses event.preventDefault to stop forms from being submitted when hitting enter on DatePicker
* Blitz fixes
* resolves CONTENT-1449
* resolves CONTENT-1463
* resolves CONTENT-1464

Blitz Fixes

---

packages/strapi-design-system/src/v2/SimpleMenu/Menu.tsx
yarn.lock

* add overflow="auto" to Menu.SubContent
* Items broke out of container
* resolves #1142

fix: subcontent overflow

---

CONTRIBUTING.md

Adds additional instructions required for linking the strapi monorepo to the design system

chore: update design system contributing docs

---

lerna.json
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

[release]: 1.9.0

---

.eslintignore
.eslintrc
package.json
packages/primitives/.eslintrc
packages/primitives/jest.config.js
packages/primitives/src/components/Collection.tsx
packages/primitives/src/components/Collection/index.ts
packages/primitives/src/components/Combobox/Combobox.tsx
packages/primitives/src/components/Combobox/__tests__/Combobox.test.tsx
packages/primitives/src/components/Combobox/index.ts
packages/primitives/src/components/Select/Select.tsx
packages/primitives/src/components/Select/__tests__/Select.test.tsx
packages/primitives/src/components/Select/index.ts
packages/primitives/src/hooks/useCollator.ts
packages/primitives/src/hooks/useFilter.ts
packages/primitives/src/index.ts
packages/primitives/tsconfig.eslint.json
packages/primitives/vite.config.ts
packages/strapi-design-system/.eslintrc
yarn.lock

* uses `@strapi/eslint-config@0.2.0` for the FE typescript
* create unity across projects
* lint github action should pass

chore: use strapi/eslint config for ui-primitives

---

.changeset/config.json
.changeset/eighty-oranges-leave.md
.changeset/empty-lizards-tickle.md
.changeset/few-geese-occur.md
.changeset/green-cows-occur.md
.changeset/lemon-rats-talk.md
.changeset/light-shirts-crash.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

* tweaks changeset config due to some constraints when i was doing an alpha release
* removes changesets and versions packages ready for release

release: 1.10.0

---

.changeset/curly-ligers-yell.md
.changeset/forty-seals-tan.md
package.json
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.10.1

---

.changeset/rich-plants-clap.md
packages/primitives/src/components/Select/Select.tsx
packages/strapi-design-system/src/Popover/Popover.tsx
packages/strapi-design-system/src/Popover/index.tsx

* Exports some types that should have been previously
* working on the helper-plugin migration identified some un-exported types we missed.

fix: some types were not exported

---

.changeset/breezy-papayas-reply.md
.changeset/lovely-mangos-lick.md
.changeset/pink-hats-tie.md
.changeset/rich-plants-clap.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.11.0

---

.changeset/config.json
.changeset/few-fishes-sip.md
.changeset/happy-pants-ring.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.12.0

---

.changeset/breezy-jobs-agree.md
.changeset/fix-tab-group-types.md
.changeset/gold-mugs-brake.md
.changeset/long-buses-yawn.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.12.1

---

.changeset/tough-laws-pay.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

chore: release 1.12.2

---

.changeset/make-title-optional.md
packages/strapi-design-system/src/Alert/Alert.tsx

Adds changelog for strapi/design-system#1413

Add changelog for optional title

---

.changeset/forty-cycles-attend.md
.changeset/make-title-optional.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.13.0

---

.changeset/hot-starfishes-judge.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.13.1

---

.changeset/slimy-tables-explain.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.14.0

---

.changeset/brave-chefs-behave.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.14.1

---

.changeset/mighty-hats-complain.md
.changeset/tasty-cars-hide.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.15.0

---

.changeset/smart-buttons-do.md
.changeset/warm-weeks-matter.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.16.0

---

.changeset/brown-jars-sneeze.md
.changeset/slow-deers-confess.md
.changeset/spicy-items-wink.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.18.0

---

.github/workflows/chromatic.yml
README.md
docs/.storybook/main.ts
docs/.storybook/modes.ts
docs/.storybook/preview.tsx
docs/chromatic.config.json
docs/package.json
docs/stories/Inputs/Checkbox.stories.tsx
docs/stories/Inputs/Combobox.stories.tsx
docs/stories/Inputs/DatePicker.stories.tsx
docs/stories/Inputs/DateTimePicker.stories.tsx
docs/stories/Inputs/JSONInput.stories.tsx
docs/stories/Inputs/NumberInput.stories.tsx
docs/stories/Inputs/Select.stories.tsx
docs/stories/Inputs/TextInput.stories.tsx
docs/stories/Inputs/Textarea.stories.tsx
docs/stories/Inputs/TimePicker.stories.tsx
docs/stories/Inputs/Toggle.stories.tsx
docs/stories/foundations/icons/Icons.stories.tsx
docs/stories/foundations/icons/Symbols.stories.tsx
yarn.lock

* adds chromatic to the project (only runs on specified stories for now)
* visual regression testing is very valuable
* resolves DX-1402

chore: add chromatic workflow and some stories

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/issues_dailyCron.yml
.github/workflows/issues_handleLabel.yml

* adds issues workflow handling
* easier maintenance

chore: add workflows for issue handling

---

.changeset/two-weeks-protect.md
packages/primitives/package.json
packages/strapi-design-system/package.json
packages/strapi-icons/package.json
yarn.lock

release: 1.19.0

---

.changeset/quick-poems-kick.md
docs/stories/03-inputs/Combobox.mdx
docs/stories/03-inputs/Combobox.stories.tsx
docs/stories/03-inputs/DatePicker.mdx
docs/stories/03-inputs/DatePicker.stories.tsx
docs/stories/03-inputs/DateTimePicker.mdx
docs/stories/03-inputs/DateTimePicker.stories.tsx
docs/stories/03-inputs/NumberInput.mdx
docs/stories/03-inputs/NumberInput.stories.tsx
docs/stories/03-inputs/Select.mdx
docs/stories/03-inputs/Select.stories.tsx
docs/stories/03-inputs/TextInput.mdx
docs/stories/03-inputs/TextInput.stories.tsx
docs/stories/03-inputs/TimePicker.mdx
docs/stories/03-inputs/TimePicker.stories.tsx
packages/design-system/src/components/Combobox/Combobox.tsx
packages/design-system/src/components/DatePicker/DatePicker.tsx
packages/design-system/src/components/DateTimePicker/DateTimePicker.tsx
packages/design-system/src/components/Field/Field.tsx
packages/design-system/src/components/NumberInput/NumberInput.tsx
packages/design-system/src/components/Select/SelectParts.tsx
packages/design-system/src/components/Select/SingleSelect.tsx

* re-adds the size prop to inputs
* bit of confusion on the direction
* resolves DX-1296

feat: reimplement size prop

---

packages/design-system/src/components/Searchbar/Searchbar.tsx

Fixes SubNavHeader search clear action is not working, https://github.com/strapi/design-system/issues/1528

fix: subNavHeader search clear action is not working

---

.changeset/mean-cycles-nail.md
docs/stories/Badge.mdx
docs/stories/Badge.stories.tsx
packages/design-system/src/components/Badge/Badge.tsx

This allows badge to pass possible values for background and text color.
Fixes https://github.com/strapi/design-system/issues/1724

fix: badge background and text color

---

.changeset/hot-turkeys-cross.md
.changeset/itchy-rings-listen.md
.changeset/soft-zoos-marry.md
docs/stories/04-components/Field.mdx
docs/stories/04-components/Field.stories.tsx
packages/design-system/src/components/Button/utils.ts
packages/design-system/src/components/Field/Field.tsx
packages/design-system/src/components/Popover/Popover.tsx

1. Ghost button active border style removed
2. On popover default border radius added
3. Field input padding updated to show correct highlight in autocomplete
Fixes: https://github.com/strapi/design-system/issues/1768, https://github.com/strapi/design-system/issues/1767

fix: multiple UI styles fixes

---

packages/design-system/src/components/Button/Button.tsx

Fix the alignment of the start and end icons.
https://github.com/strapi/strapi/issues/20986

fix: button icons position and width

---

CONTRIBUTING.md

Add instruction to build project
Storybook won't be launched successfully without the build command
N/A
N/A

doc: add instruction to build project

---

.changeset/smooth-adults-jump.md
docs/stories/00-getting started/migration guides/migration-v1-v2.mdx
docs/stories/04-components/Avatar.mdx

https://github.com/strapi/design-system/issues/1809

Update migration guide & avatar doc

---

.changeset/rich-papayas-fry.md
packages/design-system/src/components/Combobox/Combobox.tsx

Added `ScrollArea`.
See https://github.com/strapi/design-system/issues/1858.
You'll need to check the preview.
https://github.com/strapi/design-system/issues/1858
https://github.com/strapi/design-system/issues/1859

fix: add scrollbar to combobox

---

.changeset/cool-mayflies-arrive.md
packages/design-system/src/utilities/ScrollArea/ScrollArea.tsx

- Added `margin`
- Removed `padding-inline`
- Added `border-radius`
See https://github.com/strapi/design-system/issues/1875.
You'll need to check the preview.
fixes https://github.com/strapi/design-system/issues/1875

fix: scrollbar ui

---

.changeset/honest-crabs-crash.md
packages/design-system/src/components/Searchbar/Searchbar.tsx

fix: searchbar clear button

---

.changeset/dull-ants-wash.md
packages/design-system/src/components/Searchbar/Searchbar.tsx

Searchbar clear button type

---

.changeset/metal-impalas-thank.md
packages/design-system/src/components/Modal/Modal.tsx

https://github.com/strapi/design-system/issues/1815

fix: modal component open and close animations

---

.changeset/tricky-pumpkins-impress.md
packages/design-system/src/components/Checkbox/Checkbox.tsx
packages/design-system/src/components/JSONInput/JSONInput.tsx
packages/design-system/src/components/Radio/Radio.tsx
packages/design-system/src/components/Textarea/Textarea.tsx
packages/design-system/src/styles/global.ts

https://github.com/strapi/design-system/issues/1823

fix: disabled input cursor

---

.changeset/orange-bulldogs-shake.md
docs/stories/03-inputs/Combobox.mdx
docs/stories/03-inputs/Combobox.stories.tsx
packages/design-system/src/components/Combobox/Combobox.test.tsx
packages/design-system/src/components/Combobox/Combobox.tsx
packages/primitives/src/components/Collection.tsx
packages/primitives/src/components/Combobox/Combobox.tsx
packages/primitives/src/hooks/useCallbackRef.ts

feat: creation item always visible and sticky

---

.changeset/witty-tips-kick.md
packages/design-system/src/components/Popover/Popover.tsx

Exports Popover.Arrow
We need the Arrow for the Guided Tour
Nothing to test just an export

feat: export popover arrow
