packages/strapi-design-system/src/Button/Button.js, packages/strapi-design-system/src/Button/Button.stories.mdx, packages/strapi-design-system/src/Button/__tests__/Button.e2e.js, packages/strapi-design-system/src/Button/__tests__/Button.spec.js, packages/strapi-design-system/src/Button/__tests__/utils.spec.js, packages/strapi-design-system/src/Button/constants.js, packages/strapi-design-system/src/Button/utils.js, packages/strapi-design-system/src/Loader/__tests__/Loader.spec.js
Add a button component
Example on: https://design-system-git-atom-button-strapijs.vercel.app/?path=/story/button--variants
Existing variants : `['default', 'tertiary', 'secondary', 'danger', 'success', 'success-light', 'danger-light'];`
Existing sizes : `S, L`
```jsx
<Button size="L" onClick={handler} aria-label="Create something">
Create
</Button>
```
With icon
```jsx
import { Plus, Trash } from '@strapi/icons';
 
<Button aria-label="New row" leftIcon={<Plus />} rightIcon={<Trash />}>
New row
</Button>
```
=> Button component

packages/strapi-design-system/.eslintrc.js, packages/strapi-design-system/src/BaseRadio/RadioGroup.js, packages/strapi-design-system/src/Box/Box.js, packages/strapi-design-system/src/Field/Field.js, packages/strapi-design-system/src/Grid/Grid.js, packages/strapi-design-system/src/Loader/__tests__/Loader.spec.js, packages/strapi-design-system/src/ProgressBar/ProgressBar.js, packages/strapi-design-system/src/ProgressBar/ProgressBar.stories.mdx, packages/strapi-design-system/src/ProgressBar/__tests__/ProgressBar.e2e.js, packages/strapi-design-system/src/ProgressBar/__tests__/ProgressBar.spec.js, packages/strapi-design-system/src/ProgressBar/index.js, packages/strapi-design-system/src/Radio/Radio.js
Add a Progress bar indicator
Example on: https://design-system-git-add-progressbar-strapijs.vercel.app/?path=/story/progressbar--m
```jsx
<ProgressBar value={100} size="S">
100/200 plugins loaded
</ProgressBar>
```
=> Add progressbar

packages/strapi-design-system/src/Pagination/Pagination.js, packages/strapi-design-system/src/Pagination/Pagination.stories.mdx, packages/strapi-design-system/src/Pagination/PaginationContext.js, packages/strapi-design-system/src/Pagination/__tests__/Pagination.e2e.js, packages/strapi-design-system/src/Pagination/__tests__/Pagination.spec.js, packages/strapi-design-system/src/Pagination/assets/next.svg, packages/strapi-design-system/src/Pagination/assets/previous.svg, packages/strapi-design-system/src/Pagination/components.js, packages/strapi-design-system/src/Pagination/index.js
This PR brings the Pagination component to the table.
https://design-system-git-add-pagination-strapijs.vercel.app/?path=/story/pagination--base
NOTE: since we can't rely on strong values for the size of the element (32x32) I've tried my best to make it work using padding. Also notice that the size of the content will depend on its value (multiple characters will take more space)
Example:
```jsx
<Pagination activePage={2}>
<PreviousLink href="/1">Go to previous page</PreviousLink>
<PageLink number={1} href="/1">
Page 1
</PageLink>
<PageLink number={2} href="/2">
Page 2
</PageLink>
<PageLink number={3} href="/3">
Page 3
</PageLink>
<Dots>There are pages in between</Dots>
<PageLink number={4} href="/4">
Page 4
</PageLink>
<NextLink href="/3">Go to next page</NextLink>
</Pagination>
```
=> Adding Pagination component

packages/strapi-design-system/src/AssetTag/AssetTag.js, packages/strapi-design-system/src/AssetTag/AssetTag.stories.mdx, packages/strapi-design-system/src/AssetTag/__tests__/AssetTag.e2e.js, packages/strapi-design-system/src/AssetTag/__tests__/AssetTag.spec.js, packages/strapi-design-system/src/AssetTag/index.js
Add AssetTag component
I've taken the freedom to use neutral600 instead of neutral500 for the text color since the color contrast was not sufficient
```jsx
<AssetTag>Doc</AssetTag>
```
=> Add AssetTag component

packages/strapi-design-system/jest.e2e.js, packages/strapi-design-system/src/Button/Button.js, packages/strapi-design-system/src/Button/__tests__/Button.spec.js, packages/strapi-design-system/src/FocusTrap/ExampleComponent.js, packages/strapi-design-system/src/FocusTrap/FocusTrap.js, packages/strapi-design-system/src/FocusTrap/FocusTrap.stories.mdx, packages/strapi-design-system/src/FocusTrap/__tests__/FocusTrap.e2e.js, packages/strapi-design-system/src/FocusTrap/__tests__/FocusTrap.spec.js, packages/strapi-design-system/src/FocusTrap/index.js, packages/strapi-design-system/src/helpers/getFocusableNodes.js, packages/strapi-design-system/src/helpers/keyboardKeys.js
The focus trap component aims to prevent focus from going outside the box. Practical for modals / dialogs. It also bring back the focus to the caller when unmounting
```jsx
<FocusTrap>
<button>I m done buddie</button>
</FocusTrap>
```
=> Add FocusTrap component

packages/strapi-design-system/src/Tooltip/Tooltip.js, packages/strapi-design-system/src/Tooltip/Tooltip.stories.mdx, packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.js
Tooltip can provide a primary label OR an aditional description.
[api details]
```jsx
<Tooltip description="This is the description">
<button>This is a label with a description in the tooltip</button>
</Tooltip>
<Tooltip label="This is the label">
<button>+</button>
</Tooltip>
```
=> Fixing tooltip for description

packages/strapi-design-system/.storybook/preview.js, packages/strapi-design-system/src/Main/Main.js, packages/strapi-design-system/src/Main/SkipToContent.js, packages/strapi-design-system/src/Main/__tests__/Main.spec.js, packages/strapi-design-system/src/Main/index.js
- Add a Main component with a strict id and a required labelledBy prop
- Add a SkipToContent component that is available when tabbing for the first time on a page to avoid having to tab through the whole menu to get access to the main content
Example on :https://design-system-git-main-skip-to-main-content-strapijs.vercel.app
```jsx
<AppRoot>
<SkipToContent>Skip to main content</SkipToContent>
<HeavyMenuWith200Links />
<Main labelledBy="main">
<h1 id="main">This is a storybook story</h1>
</Main>
</AppRoot>
```
=> Add Main and SkipToContent

packages/strapi-design-system/src/Pagination/__tests__/Pagination.spec.js, packages/strapi-design-system/src/Pagination/components.js, packages/strapi-design-system/src/Popover/Popover.js, packages/strapi-design-system/src/Searchbar/Searchbar.js, packages/strapi-design-system/src/Searchbar/__tests__/Searchbar.spec.js
=> Use theme shadows instead of raw box-shadow

packages/strapi-design-system/src/Link/Link.js, packages/strapi-design-system/src/Link/Link.stories.mdx, packages/strapi-design-system/src/Link/__tests__/Link.e2e.js, packages/strapi-design-system/src/Link/__tests__/Link.spec.js, packages/strapi-design-system/src/Link/index.js
Add a Link component.
⚠️ the neutral400 color and the neutral500 color were too light for the disabled state. I had to switch to neutral600 to fix the constrast error.
Example on :https://design-system-git-add-link-strapijs.vercel.app/?path=/story/link--base
Internal links
```jsx
<Link to="/somewhere-internal" disabled leftIcon={<BackIcon />} rightIcon={<NextIcon />}>
Internal disabled link
</Link>
```
External links
```jsx
<Link href="https://strapi.io" disabled leftIcon={<BackIcon />} rightIcon={<NextIcon />}>
External disabled link
</Link>
```
=> Add a link component

packages/strapi-design-system/src/Alert/Alert.js, packages/strapi-design-system/src/Alert/Alert.stories.mdx, packages/strapi-design-system/src/Alert/__tests__/Alert.e2e.js, packages/strapi-design-system/src/Alert/__tests__/Alert.spec.js, packages/strapi-design-system/src/Alert/index.js, packages/strapi-design-system/src/Alert/utils.js, packages/strapi-design-system/src/Link/Link.js, packages/strapi-design-system/src/Link/Link.stories.mdx, packages/strapi-design-system/src/Link/__tests__/Link.spec.js, packages/strapi-design-system/src/index.js
Example: https://design-system-git-add-alert-strapijs.vercel.app/
NOTE: I've moved the link color to 700 because there was a constrat issue with 600
```jsx
<Alert title="Success variant" variant="success" onClose={() => {}} closeLabel="Close notification">
Alert with title and longer description
</Alert>
```
=> Add Alert component

packages/strapi-design-system/src/TextButton/TextButton.js, packages/strapi-design-system/src/TextButton/TextButton.stories.mdx, packages/strapi-design-system/src/TextButton/__tests__/TextButton.e2e.js, packages/strapi-design-system/src/TextButton/__tests__/TextButton.spec.js, packages/strapi-design-system/src/TextButton/index.js
Add a TextButton component
Example on : https://design-system-git-add-text-button-strapijs.vercel.app/
```jsx
<TextButton disabled leftIcon={<BackIcon />} rightIcon={<NextIcon />}>
Disabled TextButton
</TextButton>
```
=> Add TextButton

packages/strapi-design-system/src/Alert/Alert.js
https://design-system-git-fix-link-alignment-strapijs.vercel.app/?path=/story/alert--base
=> Fixing vertical alignment in Alert

packages/strapi-design-system/src/FocusTrap/ExampleComponent.js, packages/strapi-design-system/src/FocusTrap/FocusTrap.js, packages/strapi-design-system/src/FocusTrap/__tests__/FocusTrap.e2e.js
Before this PR, when dynamically showing content in the three (using a boolean state for instance), the focus tree was never updated because the listener was registered only at "mount time".
=> Make the focus trap aware of dynamic content

packages/strapi-design-system/src/Breadcrumbs/Breadcrumbs.js, packages/strapi-design-system/src/Breadcrumbs/Breadcrumbs.stories.mdx, packages/strapi-design-system/src/Breadcrumbs/__tests__/Breadcrumbs.e2e.js, packages/strapi-design-system/src/Breadcrumbs/__tests__/Breadcrumbs.spec.js, packages/strapi-design-system/src/Breadcrumbs/index.js, packages/strapi-design-system/src/Row/Row.js, plop-templates/component.hbs, plop-templates/unit-test.hbs
This is a draft for the breadcrumbs component. Let's check the API before going forward 😄 
Example on : https://design-system-git-breadcrumbs-strapijs.vercel.app/?path=/story/breadcrumbs--base
```jsx
<Breadcrumbs label="Second page">
<BreadCrumbItem>Home</BreadCrumbItem>
<BreadCrumbItem>first</BreadCrumbItem>
<BreadCrumbItem>second</BreadCrumbItem>
</Breadcrumbs>
```
=> Add breadcrumbs

.github/workflows/playwright-ci.yml, example/src/ContentManager/EditViewPage.js, example/src/shared/GenericInput/GenericInput.js, example/src/shared/GenericInput/__tests__/GenericInput.spec.js, package.json, packages/strapi-design-system/src/Field/Field.js, packages/strapi-design-system/src/TextInput/TextInput.js, packages/strapi-design-system/src/Textarea/Textarea.js
This idea is to prepare the GenericInput component that @soupette is waiting for so long. It aims to be experimental and outside the @strapi/design-system package (it's in the cra-example for now) until we find a good place to put it.
```jsx
GenericInput.propTypes = {
type: PropTypes.oneOf(["text", "checkbox", "radio", "textarea"]).isRequired,
label: PropTypes.string,
name: PropTypes.string.isRequired,
onChange: PropTypes.func.isRequired,
options: PropTypes.arrayOf(
PropTypes.shape({
value: PropTypes.string.isRequired,
label: PropTypes.string.isRequired,
})
),
};
```
=> Preparing generic input

example/src/shared/GenericInput/__tests__/GenericInput.spec.js, packages/strapi-design-system/src/Avatar/Avatar.stories.mdx, packages/strapi-design-system/src/DatePicker/DatePicker.js, packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx, packages/strapi-design-system/src/DatePicker/DatePickerTd.js, packages/strapi-design-system/src/DatePicker/DatePickerTh.js, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.e2e.js, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.js, packages/strapi-design-system/src/DatePicker/__tests__/generateWeeks.spec.js, packages/strapi-design-system/src/DatePicker/compareDates.js, packages/strapi-design-system/src/DatePicker/generateWeeks.js, packages/strapi-design-system/src/DatePicker/getDayOfWeek.js, packages/strapi-design-system/src/DatePicker/index.js, packages/strapi-design-system/src/FocusTrap/FocusTrap.js, packages/strapi-design-system/src/Popover/Popover.js, packages/strapi-design-system/src/Popover/Popover.stories.mdx, packages/strapi-design-system/src/Popover/__tests__/Popover.spec.js, packages/strapi-design-system/src/Table/Cell.js, packages/strapi-design-system/src/Table/Table.js, packages/strapi-design-system/src/TextInput/TextInput.js, packages/strapi-design-system/src/helpers/getFocusableNodes.js
Add a first iteration of DatePicker
Example on : https://design-system-git-add-date-picker-strapijs.vercel.app/?path=/story/datepicker--base
```jsx
<DatePicker
// resolves a window.Date object
onChange={setDate}
selectedDate={date}
label="Date picker"
name="datepicker"
selectedDateLabel={(formattedDate) => `Date picker, current is ${formattedDate}`}
/>
```
=> Date picker (first iteration)

packages/strapi-design-system/src/Popover/Popover.js
The popover now receives a `fullWidth` boolean props that allows to match the size of the source element
=> Adjust popover for fullwidth

packages/strapi-design-system/src/Popover/Popover.js, packages/strapi-design-system/src/Popover/__tests__/Popover.spec.js, packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js, packages/strapi-design-system/src/SimpleMenu/SimpleMenu.stories.mdx, packages/strapi-design-system/src/SimpleMenu/__tests__/SimpleMenu.e2e.js, packages/strapi-design-system/src/SimpleMenu/__tests__/SimpleMenu.spec.js, packages/strapi-design-system/src/SimpleMenu/index.js, packages/strapi-design-system/src/SimpleMenu/utils.js
Add the simple menu dropdown.
Example on : https://design-system-git-simple-menu-strapijs.vercel.app/?path=/story/design-system-atoms-simplemenu--base
```jsx
<SimpleMenu label="January">
<MenuItem id="menuItem-January" onClick={() => setValue('January')}>
January
</MenuItem>
<MenuItem id="menuItem-February" onClick={() => setValue('February')}>
February
</MenuItem>
<MenuItem id="menuItem-Strapi" href="https://strapi.io">
Strapi website
</MenuItem>
</SimpleMenu>
```
=> Simple menu

packages/strapi-design-system/.eslintrc.js, packages/strapi-design-system/package.json, packages/strapi-design-system/src/Field/Field.js, packages/strapi-design-system/src/Field/FieldLabel.js, packages/strapi-design-system/src/Select/Option.js, packages/strapi-design-system/src/Select/Select.js, packages/strapi-design-system/src/Select/Select.stories.mdx, packages/strapi-design-system/src/Select/SelectButton.js, packages/strapi-design-system/src/Select/SelectList.js, packages/strapi-design-system/src/Select/__tests__/Select.e2e.js, packages/strapi-design-system/src/Select/__tests__/Select.spec.js, packages/strapi-design-system/src/Select/components.js, packages/strapi-design-system/src/Select/index.js, packages/strapi-design-system/yarn.lock
Add a `<Select>` component. For now, it's a single value selection (will become a multi in another PR)
Example on : https://design-system-git-add-select-strapijs.vercel.app/?path=/story/select--base
```jsx
<Select
id="select1"
label="Choose your meal"
placeholder="Your example"
hint="Description line"
clearLabel="Clear the meal"
error={error}
value={value}
onChange={setValue}
disabled={disabled}
>
<Option value={'pizza'}>Pizza</Option>
<Option value={'hamburger'}>Hamburger</Option>
<Option value={'bagel'}>Bagel</Option>
</Select>
```
=> Add a Select component

packages/strapi-design-system/src/Select/Option.js, packages/strapi-design-system/src/Select/Select.js, packages/strapi-design-system/src/Select/SelectButton.js, packages/strapi-design-system/src/Select/SelectList.js, packages/strapi-design-system/src/Select/__tests__/Select.e2e.js, packages/strapi-design-system/src/Select/__tests__/Select.spec.js, packages/strapi-design-system/src/Select/hooks/useButtonRef.js, packages/strapi-design-system/src/Select/hooks/useListRef.js, packages/strapi-design-system/src/Select/utils.js
Reworking the Select component using the `aria-activedescendant` property  https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html
It has a more appropriate semantic, and it will be easier to manager the multi select thing
API stays the same
https://design-system-git-rework-select-strapijs.vercel.app/?path=/story/select--base
=> Rework select

example/src/shared/GenericInput/__tests__/GenericInput.spec.js, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.js, packages/strapi-design-system/src/Field/FieldAction.js, packages/strapi-design-system/src/Field/FieldInput.js, packages/strapi-design-system/src/Field/__tests__/Field.spec.js, packages/strapi-design-system/src/Searchbar/__tests__/Searchbar.spec.js, packages/strapi-design-system/src/TextInput/__tests__/TextInput.spec.js
This PR removes the padding top / bottom of the field input and make it be `40/16 rem` high. The aim is to make the alignment of the select component and field input possible.
Another iteration will come for the select component
=> Homogeneize height of inputs

example/src/shared/GenericInput/__tests__/GenericInput.spec.js, packages/strapi-design-system/src/Popover/Popover.js, packages/strapi-design-system/src/Popover/__tests__/Popover.spec.js, packages/strapi-design-system/src/Select/Select.js, packages/strapi-design-system/src/Select/Select.stories.mdx, packages/strapi-design-system/src/Select/SelectButton.js, packages/strapi-design-system/src/Select/SelectList.js, packages/strapi-design-system/src/Select/SelectTags.js, packages/strapi-design-system/src/Select/__tests__/Select.e2e.js, packages/strapi-design-system/src/Select/__tests__/Select.spec.js, packages/strapi-design-system/src/Select/components.js, packages/strapi-design-system/src/Select/hooks/useListRef.js, packages/strapi-design-system/src/Tag/Tag.js, packages/strapi-design-system/src/Tag/__tests__/Tag.spec.js, packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
Add a `withTags` props to the component
Example on : https://design-system-git-select-multi-tags-strapijs.vercel.app/?path=/story/design-system-atoms-select--multi-with-tags
```diff
<Select
id="select1"
label="Choose your meal"
placeholder="Your example"
onClear={() => setValues([])}
hint="Description line"
clearLabel="Clear the meal"
error={error}
value={values}
onChange={onValueChange}
disabled={disabled}
customizeContent={(values) => `${values.length} currently selected`}
multi
+  withTags
>
<Option value={'pizza'}>Pizza</Option>
<Option value={'hamburger'}>Hamburger</Option>
<Option value={'bagel'}>Bagel</Option>
</Select>
```
=> Select multi tags

packages/strapi-design-system/src/Popover/Popover.js, packages/strapi-design-system/src/Select/__tests__/Select.spec.js, packages/strapi-design-system/test-bundler.js
Adds a ResizeObserver on Popover so that it can repositioned itself when the source container grows such as the Input in the Select multi tags example
Example on : https://design-system-git-resize-popover-strapijs.vercel.app/?path=/story/design-system-atoms-select--multi-with-tags
=> ResizeObserver on Popover

packages/strapi-design-system/src/Grid/Grid.js, packages/strapi-design-system/src/Grid/Grid.stories.mdx, packages/strapi-design-system/src/Grid/GridItem.js, packages/strapi-design-system/src/Grid/__tests__/Grid.spec.js, packages/strapi-design-system/src/Tooltip/Tooltip.stories.mdx, packages/strapi-design-system/src/themes/Theme.stories.mdx
https://design-system-git-light-theme-tokens-strapijs.vercel.app/?path=/story/design-system-subatomic-lighttheme--colors
=> Add stories for tokens and icons (and refacto grid)

packages/strapi-design-system/src/HeaderLayout/HeaderLayout.js, packages/strapi-design-system/src/HeaderLayout/HeaderLayout.stories.mdx, packages/strapi-design-system/src/HeaderLayout/__tests__/HeaderLayout.e2e.js, packages/strapi-design-system/src/HeaderLayout/__tests__/HeaderLayout.spec.js, packages/strapi-design-system/src/HeaderLayout/index.js, packages/strapi-design-system/src/index.js
```jsx
<HeaderLayout
sticky
navigationAction={
<Link startIcon={<BackIcon />} to="/">
<VisuallyHidden>Go back</VisuallyHidden>
</Link>
}
primaryAction={<Button startIcon={<AddIcon />}>Add an entry</Button>}
secondaryAction={
<Button variant="tertiary" startIcon={<EditIcon />}>
Edit
</Button>
}
title={<H2>Restaurants</H2>}
subtitle={
<Text small={true} textColor="neutral600">
36 entries found
</Text>
}
/>
```
=> Header layout

packages/strapi-design-system/src/Button/Button.js, packages/strapi-design-system/src/HeaderLayout/HeaderLayout.js, packages/strapi-design-system/src/HeaderLayout/HeaderLayout.stories.mdx, packages/strapi-design-system/src/HeaderLayout/__tests__/HeaderLayout.spec.js
- title and subtitle props are now string to enforce H1 tag on this header
- add a shadow on the button to create the effect wanted in figma for the tertiary button
UI doesn't change that much except for the shadow
=> Modify header layout for title and subtitle props

example/src/App.js, example/src/shared/SideNav/index.js, packages/strapi-design-system/package.json, packages/strapi-design-system/src/MainNav/MainNav.stories.mdx, packages/strapi-design-system/src/MainNav/NavLink.js, packages/strapi-design-system/src/MainNav/NavUser.js, packages/strapi-design-system/src/MainNav/__tests__/MainNav.spec.js, packages/strapi-design-system/webpack.config.js, packages/strapi-design-system/yarn.lock
(not managing linting diff in this PR)
Allows to make the MainNav component aware of react-router-dom and to highlight the selected link based on what react-router-dom provides (e.g: an `active` className instead of a react prop)
=> Making MainNav aware of react-router-dom

packages/strapi-design-system/src/ModalLayout/ModalBody.js, packages/strapi-design-system/src/ModalLayout/ModalContext.js, packages/strapi-design-system/src/ModalLayout/ModalFooter.js, packages/strapi-design-system/src/ModalLayout/ModalHeader.js, packages/strapi-design-system/src/ModalLayout/ModalLayout.js, packages/strapi-design-system/src/ModalLayout/ModalLayout.stories.mdx, packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.e2e.js, packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js, packages/strapi-design-system/src/ModalLayout/index.js, packages/strapi-design-system/src/index.js
Add a ModalLayout, ModalHeader, ModalBody, ModalFooter to compose dialogs
Example on : https://design-system-git-modal-layout-strapijs.vercel.app/?path=/story/design-system-layouts-modallayout--base
```jsx
<ModalLayout onClose={() => undefined} labelledBy="title">
<ModalHeader>
<TextButton textColor="neutral800" as="h2" id="title">
Title
</TextButton>
</ModalHeader>
<ModalBody>Hello world</ModalBody>
<ModalFooter
startActions={<Button variant="tertiary">Cancel</Button>}
endActions={
<>
<Button variant="secondary">Add new stuff</Button>
<Button>Finish</Button>
</>
}
/>
</ModalLayout>
```
=> Add Modal Layout

packages/strapi-design-system/src/Card/CardAsset.js, packages/strapi-design-system/src/Card/__tests__/Card.spec.js
Allow CardAsset to receive a size (S or M) in order to display it in the good context
```diff
<Card style={{ width: '240px' }} id="first">
<CardHeader>
<CardCheckbox value={true} />
<CardAction position="end">
<IconButton title="Edit the thing">
<EditIcon />
</IconButton>
</CardAction>
+    <CardAsset src={firstImgPath} size="S" /> {/* or M (default value) */}
<CardTimer>05:39</CardTimer>
</CardHeader>
<CardBody>
<CardContent>
<CardTitle>File name</CardTitle>
<CardSubtitle>PNG - 400✕400</CardSubtitle>
</CardContent>
<CardBadge>Doc</CardBadge>
</CardBody>
</Card>
```
=> Card asset size

packages/strapi-design-system/src/Avatar/Avatar.js, packages/strapi-design-system/src/Avatar/Avatar.stories.mdx, packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.js, packages/strapi-design-system/src/Table/__tests__/Table.spec.js
Add the possibility to display a "bigger" picture when hovering an avatar
Example on : https://design-system-git-avatar-zoom-strapijs.vercel.app/?path=/story/design-system-atoms-avatar--base
```diff
<Avatar
src="https://avatars.githubusercontent.com/u/3874873?v=4"
alt="marvin frachet"
+  preview="https://some-unknown-photo/x.png"
/>
```
or the following when the image is the same
```diff
<Avatar
src="https://avatars.githubusercontent.com/u/3874873?v=4"
alt="marvin frachet"
+  preview
/>
```
=> Add zoom to the Avatar component

packages/strapi-icons/package.json, packages/strapi-parts/src/OneBlockLayout/OneBlockLayout.js, packages/strapi-parts/src/OneBlockLayout/OneBlockLayout.stories.mdx, packages/strapi-parts/src/SubNav/SubNav.js, packages/strapi-parts/src/SubNav/__tests__/SubNav.spec.js
This PR introduces a `sideNav` props on the `OneBlockLayout` component in order for plugin creator to pass a custom side nav if they need one
```diff
+ sideNav={<SomeNav />}
```
=> One block layout with sidenav

packages/strapi-parts/src/GridLayout/GridLayout.js, packages/strapi-parts/src/GridLayout/GridLayout.stories.mdx, packages/strapi-parts/src/TwoColsLayout/TwoColsLayout.js, packages/strapi-parts/src/TwoColsLayout/TwoColsLayout.stories.mdx
Adds a `sideNav` prop to the `GridLayout` and `TwoColumnLayout`
```diff
+ sideNav={<SideNav />}
```
=> GridLayout and TwoColumnLayout aware of sideNav

example/src/layouts/AppLayout.js, packages/strapi-parts/src/Card/CardAsset.js, packages/strapi-parts/src/Card/__tests__/Card.spec.js, packages/strapi-parts/src/GridLayout/GridLayout.js, packages/strapi-parts/src/MainNav/MainNav.js, packages/strapi-parts/src/MainNav/__tests__/MainNav.spec.js, packages/strapi-parts/src/OneBlockLayout/OneBlockLayout.js, packages/strapi-parts/src/OneBlockLayout/OneBlockLayout.stories.mdx, packages/strapi-parts/src/SubNav/SubNav.js, packages/strapi-parts/src/SubNav/__tests__/SubNav.spec.js, packages/strapi-parts/src/TwoColsLayout/TwoColsLayout.js
- Fix the main nav position sticky issue
- Make sure the table is scrollable in the different layouts
- Fixing the card asset that was overflowing outside the card in the grid layout
To test, make sure to start the example app with the local version of parts and navigate in the different pages (settings and media libs)
=> Fix broken UI

example/package.json, example/yarn.lock, packages/strapi-parts/src/themes/__tests__/extendTheme.spec.js, packages/strapi-parts/src/themes/extendTheme.js, packages/strapi-parts/src/themes/index.js
This PR adds a function that aims to extend a theme
```js
const myTheme = extendTheme(lightTheme, {
colors: {
primary100: 'red',
},
});
```
will only override the "primary100" key and only this one
=> Add a function to extend a theme

packages/strapi-parts/src/Select/__tests__/Select.e2e.js, packages/strapi-parts/src/Select/hooks/useButtonRef.js
Ensure to restore the focus on the select button only when it's closed using a keyboard
=> Fix the focus when closing the select with a mouse

packages/strapi-parts/src/Popover/Popover.js, packages/strapi-parts/src/Popover/Popover.stories.mdx, packages/strapi-parts/src/Popover/__tests__/Popover.spec.js, packages/strapi-parts/src/helpers/useResizeObserver.js
Prevents the popover from overflowing when it's out of the screen on the right side
Example on : https://design-system-git-popover-overflow-strapijs.vercel.app/?path=/story/design-system-molecules-popover--overflow-right
=> Prevent popover from overflowing on the right side of the screen

packages/strapi-parts/src/MainNav/NavBrand.js, packages/strapi-parts/src/MainNav/__tests__/MainNav.spec.js
aria-hidden on the NavBrand is not necessary since passing an empty alt in the image would make it being ignored.
=> Removing aria-hidden from NavBrand

packages/strapi-parts/src/Tabs/TabGroup.js, packages/strapi-parts/src/Tabs/Tabs.js, packages/strapi-parts/src/Tabs/Tabs.stories.mdx, packages/strapi-parts/src/Tabs/__tests__/Tabs.e2e.js, packages/strapi-parts/src/Tabs/__tests__/Tabs.spec.js, packages/strapi-parts/src/Tabs/components.js
Add simple variant for the tabs component
Example on : https://design-system-git-tabs-simple-strapijs.vercel.app/?path=/story/design-system-molecules-tabs--simple
```diff
<TabGroup
label="Some stuff for the label"
+  variant="simple"
>
<Tabs>
<Tab>First</Tab>
<Tab>Second</Tab>
<Tab>Third</Tab>
</Tabs>
<TabPanels>
<TabPanel>First panel</TabPanel>
<TabPanel>Second panel</TabPanel>
<TabPanel>Third panel</TabPanel>
</TabPanels>
</TabGroup>
```
=> Add simple variant for tabs

packages/strapi-parts/src/ModalLayout/__tests__/ModalLayout.spec.js, packages/strapi-parts/src/Tooltip/Tooltip.js, packages/strapi-parts/src/Tooltip/Tooltip.stories.mdx, packages/strapi-parts/src/Tooltip/__tests__/Tooltip.spec.js, packages/strapi-parts/src/Tooltip/utils/__tests__/positionTooltip.spec.js, packages/strapi-parts/src/Tooltip/utils/positionTooltip.js
Update tooltip left, right and top position when they overflow out of then screen + tests
=> Handle viewport overflow top && left for tooltip

packages/strapi-parts/src/MainNav/NavBrand.js, packages/strapi-parts/src/MainNav/__tests__/MainNav.spec.js
Add a link to the NavBrand
Example on : https://design-system-git-fix-mainnav-link-strapijs.vercel.app/?path=/story/design-system-organisms-mainnav--base
Just added a "to" prop with default value of "/"
=> Add link to NavBrand

packages/strapi-parts/src/Popover/Popover.js, packages/strapi-parts/src/Popover/Popover.stories.mdx, packages/strapi-parts/src/Popover/__tests__/Popover.spec.js
- Centering calculations fixed (based on popover width and not source element width)
- Popover ref moved to PopoverWrapper, if not padding and border couldn't be part of positioning calculations
=> Fixed centering calculations && popover ref moved

example/src/CM/index.js
Replaced OneBlockLayout with Layout component in parts/example
=> Replaced OneBlockLayout with Layout component

packages/strapi-parts/src/Tooltip/utils/__tests__/positionTooltip.spec.js, packages/strapi-parts/src/Tooltip/utils/positionTooltip.js
Fixed bad calculations for top pos of tooltip when overflow top but not left or right
=> Fixed tooltip top pos when overflow top

packages/strapi-parts/src/Main/Main.js, packages/strapi-parts/src/Main/__tests__/Main.spec.js
When navigating to the a specific page using the keyboard, instead of leaving the keyboard on the selected link, it would great to send the focus to the main element of the new page to facilitate people navigation.
While the Main component has already a tabindex="-1" (meaning focusable programmatically), it has an outline and it's weird to see it on the screen. 
So as server-side rendered page, I would like to try, on page transition, to send the focus on the Main element of the page so that it's announced 😊 . There's no outline for server-rendered page, so I suggest that there's no outline neither on client side navigation 😊
=> Add outline none to main component

packages/strapi-parts/src/EmptyStateLayout/EmptyStateLayout.js, packages/strapi-parts/src/EmptyStateLayout/EmptyStateLayout.stories.mdx, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
When large content h3 in the EmptyStateLayout, there was no padding to prevent text to touch container borders
Added padding on the wrapper
Added text-align center when h3 multiple lines
=> Fixed EmptyStateLayout padding 

packages/strapi-parts/src/Field/FieldError.js, packages/strapi-parts/src/ModalLayout/ModalLayout.js, packages/strapi-parts/src/Tooltip/Tooltip.js, packages/strapi-parts/src/Tooltip/__tests__/Tooltip.spec.js, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
- `data-strapi-field-error` exist to easily target the form element that is in error. For now, when using a "Select" component in core, it's not possible to focus it since our implementation of the `<Form>` component relies on the "name" HTML attribute that is not set on the `<button>` element
- set a zIndex on ModalLayout because it goes under the left main nav and subnav. Also put a zIndex on the Tooltip so that it can go over the ModalLayout (for the closing button)
=> Aspecific data attribute on FieldError and zIndex

packages/strapi-parts/src/Table/Table.js, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
Updated table padding to 24px instead of 12px
To be aligned with DS mockup
=> Table padding left && right

packages/strapi-parts/src/helpers/useElementOnScreen.js
The observer was not disconnecting properly because the reference to the `.current` value does not exist anymore when cleaning the effect. The fix consists of capturing the `.current` variable
Before:
After:
=> Fix leak on observer not disconnecting

packages/strapi-parts/src/Table/Cell.js, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
height: ${4 / 16}rem => only for ActionWrapper 
To prevent every icon in Th to be forced to this size
=> Th's icon size only forced in ActionWrapper

packages/strapi-parts/src/TimePicker/TimePicker.stories.mdx, packages/strapi-parts/src/Tooltip/Tooltip.stories.mdx
Docs for the Tooltip and Time Picker components with props and imports
note: the tooltip `canvas` demo doesn't seems to work correctly though, there's a bunch of text. 
Edit: here's my proposition for documenting the different properties.
I'm not sure the Smaller example actually displays the tooltip as smaller.
I'm propose to use real buttons to make it more obvious that you can have a cta.
Example on :  See message below 👇
=> Docs - Tooltip & Timepicker

packages/strapi-parts/src/Layout/HeaderLayout.js
=> Prevent header from triggering state modif when undefined

package.json, packages/strapi-parts/createIndexFiles.js, packages/strapi-parts/package.json, packages/strapi-parts/webpack.config.js
This PR builds the lib in both development environment and production. It allows us to display errors in the console especially with the prop-types.
[api details]
```jsx
```
=> Add dev build

packages/strapi-parts/src/Main/Main.js, packages/strapi-parts/src/Text/H1.js, packages/strapi-parts/src/Text/index.js, packages/strapi-parts/src/Text/utils.js
Make main labelled by the default H1 id. main label and H1 id can both be overriden if necessary
Instead of:
```jsx
<Main labelledBy="title">
<H1 id="title"></H1>
</Main>
```
just do
```jsx
<Main>
<H1></H1>
</Main>
```
=> Binding main and h1, implicitly

packages/strapi-parts/src/IconButton/IconButton.js, packages/strapi-parts/src/IconButton/IconButton.stories.mdx, packages/strapi-parts/src/ModalLayout/ModalHeader.js, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
Allow an IconButton to not receive a label. This aims to prevent the closing button inside a modal to display the tooltip.
However, developers, when not relying on the label prop, should add an explicit `aria-label`
=> Allowing IconButton to not receive a label

packages/strapi-parts/src/Layout/HeaderLayout.js, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
Biggest fix of all time preventing Box from yelling because children is not undefined
=> Fix header layout console error

example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js, packages/strapi-parts/src/Text/H1.js, packages/strapi-parts/src/Text/Text.stories.mdx, packages/strapi-parts/src/Text/Typography.js, packages/strapi-parts/src/Text/index.js, packages/strapi-parts/src/themes/__tests__/extendTheme.spec.js, packages/strapi-parts/src/themes/light-theme.js, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
- Adding the Typography abstraction in order to make text customization easier
- Adding missing keys in theme for: fontWeights, lineHeights, fontSizes, transform
- `fontWeight` maps to the theme `fontWeights` key
- `fontSize` maps to the theme `fontSizes` key
- `lineHeight` maps to the theme `lineHeights` key
- `textTransform` is the regular CSS transform property (practical for upper / capitalize )
```jsx
<Typography fontWeight="bold" fontSize={0} lineHeight={5} textTransform="uppercase" {...props} />;
```
=> Typography abstraction

packages/strapi-parts/src/Select/SelectList.js, packages/strapi-parts/src/Select/hooks/useListRef.js
When the Select popover opens, the current behavior triggers a selection on the first option. Also, when navigating with the keyboard (Up and Down). Not understanding this choice, I created a draft PR to be able to discuss it with the team.
=> Remove item selection on Popover open in Select

example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js, packages/strapi-parts/src/SubNav/SubNavSection.js, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
Fixed subnav badge size
From:
To:
=> Subnav badge fix

packages/strapi-parts/src/Checkbox/Checkbox.js, packages/strapi-parts/tests/__snapshots__/storyshots.spec.js.snap
For Multiline checkbox, the checkmark is now stick to the top of the label instead of at the center
=> Checkbox align start

packages/strapi-parts/src/Popover/Popover.js
Fixed popover overflow bottom maths
Popover padding and border (10px) weren't returned by popoverRect.height which caused miscalculations
=> Popover overflow bottom fix

packages/strapi-design-system/src/Accordion/Accordion.js, packages/strapi-design-system/src/Accordion/Accordion.stories.mdx, packages/strapi-design-system/src/Accordion/AccordionGroup.js, packages/strapi-design-system/src/Accordion/AccordionToggle.js
Removed overflow hidden on Accordion causing issues when users add certain type of component inside AccordionContent needing to overflow the parent
Added the border radius with CSS selectors instead
=> Accordion overflow // TO MERGE AFTER ERROR STATE

packages/strapi-design-system/src/Select/__tests__/Select.e2e.js
The CI is failing because of theses tests resulting in us merging PRs that don't pass the CI. For the moment I prefer to comment them until we take some time to make a proper fix.
[api details]
```jsx
```
=> Disable e2e tests for select multi until we find a proper fix

packages/strapi-design-system/src/Main/Main.js
Fixed focus outline selector for Main to prevent 
```
*:focus-visible {
outline: 2px solid #4945ff;
}
```
to override Main outline: none
=> [QA] Fixed outline Main focus

packages/strapi-design-system/src/Grid/GridItem.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
In it's current state `GridItems` can break out the grid, if their content exceeds their width, as seen in the last column here:
Adding a `max-width: 100%` to each column ensures it's size in the grid. With that the columns falls in line with the others:
=> GridItem: prevent column blowout

packages/strapi-design-system/src/Layout/GridLayout.stories.mdx, packages/strapi-design-system/src/Layout/Layout.stories.mdx, packages/strapi-design-system/src/Layout/TwoColsLayout.stories.mdx
Some component documentation claimed that components should use default imports. All of them are using named exports and therefore should use named imports too.
Fixes: #504
=> Docs: Replace default export with named imports everywhere

packages/strapi-design-system/src/CarouselInput/CarouselInput.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Currently `CarouselInput` components don't align well with other inputs, because they are missing space between the label and the asset box:
This PR unifies the stacking of label, input, hint and error messages with other `TextInput` components.
Refs: https://strapi-inc.atlassian.net/browse/CONTENT-96
Refs: https://github.com/strapi/strapi/pull/12398
=> CarouselInput: Unify stacking with other inputs

packages/strapi-design-system/src/Link/Link.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Improves the styles of the `Link` component:
- remove text-transform
- update typography size
Refs: https://strapi-inc.atlassian.net/browse/DS-1
=> Link: remove uppercase, improve typography size

packages/strapi-design-system/src/Tag/Tag.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This PR fixes the text color of the `Tag` component. The proper color was already set on the container, but not passed onto the text.
Disabled
Enabled
Refs: https://strapi-inc.atlassian.net/browse/DS-2
=> Tag: fix text color

packages/strapi-design-system/src/SimpleMenu/SimpleMenu.stories.mdx, packages/strapi-design-system/src/SimpleMenu/utils.js
When `aria-disabled` is passed into `MenuItem` hover styles should be disabled. The issue was discovered in https://github.com/strapi/strapi/pull/12213#discussion_r803889633.
=> MenuItem: Disable hover styles when aria-disabled is set

packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js, packages/strapi-design-system/src/SimpleMenu/SimpleMenu.stories.mdx, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
In https://github.com/strapi/strapi/pull/12213/files#diff-945b0ae1436ead2b4ac56d7921a076ac866efcd77ed5985466444d07b1751d78R30-R56 I'd like to create a custom label for the `SimpleMenu`. It works already, by the prop-types don't allow elements yet. This PR adds `element`s next to `string` and `number` as valid types.
An example was added too.
Refs: https://github.com/strapi/strapi/pull/12213
=> SimpleMenu: Allow elments to be passed as prop-types

packages/strapi-design-system/src/Accordion/Accordion.js, packages/strapi-design-system/src/Accordion/Accordion.stories.mdx, packages/strapi-design-system/src/Accordion/AccordionGroup.js, packages/strapi-design-system/src/Accordion/AccordionToggle.js, packages/strapi-design-system/src/Alert/Alert.js, packages/strapi-design-system/src/Alert/Alert.stories.mdx, packages/strapi-design-system/src/Avatar/Avatar.js, packages/strapi-design-system/src/Badge/Badge.js, packages/strapi-design-system/src/BaseButton/BaseButton.stories.mdx, packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.js, packages/strapi-design-system/src/Box/BoxProps.js
Add props details to component documentation
- Accordion
- Alert
- Avatar
- Badge
- BaseButton
- BaseCheckbox
- Box
The proptypes comments adds a description column to the `ArgTable` storybook component.
=> Add docs to the first set of components

packages/strapi-design-system/src/CarouselInput/CarouselInput.js, packages/strapi-design-system/src/Field/Field.stories.mdx, packages/strapi-design-system/src/Field/FieldLabel.js, packages/strapi-design-system/src/NumberInput/NumberInput.js, packages/strapi-design-system/src/Select/Select.js, packages/strapi-design-system/src/Select/Select.stories.mdx, packages/strapi-design-system/src/Select/__tests__/Select.spec.js, packages/strapi-design-system/src/TextInput/TextInput.js, packages/strapi-design-system/src/Textarea/Textarea.js, packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js, packages/strapi-design-system/src/ToggleInput/ToggleInput.js
Before this PR each Field component used it's own way to render the action for a label. This PR moves it into the `FieldLabel` component, so that: 1) no component is forgotten 2) it is rendered visually consistent and 3) we are not duplicating the code in multiple places.
~The positioning of the icon is not great at the moment. It's not perfectly centered, because if interferes with the line-height of the label. It would help to push it down a little. What do you think about it?~
Refs: https://strapi-inc.atlassian.net/browse/CONTENT-131
=> Move labelAction into the FieldLabel component

packages/strapi-design-system/src/DatePicker/DatePicker.js, packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx, packages/strapi-design-system/src/DatePicker/DatePickerCalendar.js, packages/strapi-design-system/src/DatePicker/utils/getYears.js, packages/strapi-design-system/src/DatePicker/utils/tests/getYears.spec.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This PR adds two new props the the `DatePicker` component:
- `minDate`: minimum date which is used by the year select
- `maxDate`: maximum date which is used by the year select
It also extends the default range of the `DatePicker` component to minus 200 years and plus 15 years and replaces the default placeholder with the current date instead of 1970.
💡 I didn't name the prop `minYear` or `maxYear` because these could also be used at some point to validate the input for a max/ min value.
- https://design-system-git-content-132-min-max-date-strapijs.vercel.app/?path=/story/design-system-components-datepicker--min-max-date
Refs: https://github.com/strapi/strapi/issues/12441
Refs: https://strapi-inc.atlassian.net/browse/CONTENT-132
=> Datepicker: make min/ max date configurable and extend default range

packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js, packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.stories.mdx, packages/strapi-design-system/src/ToggleCheckbox/__tests__/ToggleCheckbox.e2e.js, packages/strapi-design-system/src/ToggleInput/ToggleInput.js, packages/strapi-design-system/src/ToggleInput/ToggleInput.stories.mdx, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This PR implements the first batch of the `ToggleCheckbox` refresh:
The content squad hopes to clarify the state the checkbox is in.
- https://design-system-git-content-73-toggle-checkbox-refresh-strapijs.vercel.app/?path=/story/design-system-components-toggleinput--base
Refs: https://www.figma.com/file/PICiE8O4NLrHO1lhJftLdE/Strapi---UI-Kit-%F0%9F%A7%A9?node-id=10500%3A120443
Refs: https://strapi-inc.atlassian.net/browse/CONTENT-73
Refs: https://github.com/strapi/strapi/issues/12372
=> ToggleCheckbox: Improve styles to clarify the components state

packages/strapi-design-system/src/DatePicker/DatePicker.js, packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Restores behavior from before https://github.com/strapi/design-system/pull/554, but allows to pass in a placeholder attribute manually.
=> DatePicker: allow passing in a placeholder, to fix a flaky test

packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
In https://github.com/strapi/design-system/pull/558 I removed the label from the `SimpleMenu`, but I missed the case, that the prop is used by the underlying `Button` component to render a tooltip.
This PR passes the prop down to the `Button` again and adds a check: in case `label` is a custom component, it won't render it as a tooltip. In case it' anything else (string, number) it works as before.
=> SimpleMenu: only render label in case it isn't a custom component

packages/strapi-design-system/src/DatePicker/DatePicker.js, packages/strapi-design-system/src/DatePicker/DatePickerCalendar.js
Fixes the `onEscape` callback of the `DatePickerCalendar` component. Before, it wasn't possible (anymore) to escape the focus trap.
https://user-images.githubusercontent.com/2244375/156546491-0136f981-bb76-41aa-94f1-966f60f1fc35.mp4
Demo: https://design-system-git-fix-datepicker-escape-strapijs.vercel.app/?path=/story/design-system-components-datepicker--base
=> DatePicker: fix onSelect event

packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js, packages/strapi-design-system/src/ToggleInput/ToggleInput.js
In https://github.com/strapi/design-system/pull/538 I accidentally forwarded the `onClear` prop to `ToggleCheckbox` which is not handled nor needed there.
Refs: https://github.com/strapi/strapi/pull/12791
=> ToggleInput: stop forwarding onClear to ToggleCheckbox

packages/strapi-design-system/src/Field/FieldInput.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Before this PR the actual `input` element didn't cover the full height of it's wrapper. This leads to the problem that you can not click everywhere since the click might end up in the wrapper.
This PR removes height from the wrapper and bumps to a height of the input elements to the same as the container by using padding. It is not possible to use `height` on input fields - therefore I had to use some magic numbers.
| Before  | After  |
|---|---|
| <img width="1172" alt="Screenshot 2022-03-16 at 14 18 00" src="https://user-images.githubusercontent.com/2244375/158598694-341a117a-95ce-4d46-bd57-8d66d877deed.png">  | <img width="1172" alt="Screenshot 2022-03-16 at 14 18 13" src="https://user-images.githubusercontent.com/2244375/158598689-0b8f37e4-e337-4168-a1f7-3647619fa7a0.png">  |
- …
=> FieldInput: Make input element cover the whole box

packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
With the latest refactoring in https://github.com/strapi/design-system/pull/538 it is not possible anymore:
- to visually distinguish the disabled `ToggleCheckbox`: this PR lightens the styles, in this case, a bit (contrast is still accessible)
- to show the default value, if the component is disabled: I didn't think about this case - this PR restores the previous behavior
---
- Fixes https://github.com/strapi/design-system/issues/584
- Example https://design-system-git-fix-toggle-disabled-strapijs.vercel.app/?path=/story/design-system-components-togglecheckbox--disabled
=> ToggleCheckbox: improve disabled state styles and show default value

packages/strapi-design-system/src/MainNav/NavBrand.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Updated BrandIconWrapper inside NavBrand component to allow other image format than squared one
Prevent image being stretched
Radius will only be applied on squared images
=> [Logo customization] Logo dimensions contained

packages/strapi-design-system/src/BaseRadio/BaseRadio.js, packages/strapi-design-system/src/Radio/__tests__/Radio.spec.js, packages/strapi-design-system/yarn.lock
Fixes #607 
passes `checked` prop to `RadioInput` component in `BaseRadio.js`
To fix implementation of `RadioGroup`/`Radio`
Tested by automation tests
#607
=> Fixes radio button not being checked when mounting radio group with a value passed in

packages/strapi-design-system/src/Box/BoxProps.js, packages/strapi-design-system/src/Flex/FlexProps.js, packages/strapi-design-system/src/Portal/Portal.stories.mdx, packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js, packages/strapi-design-system/src/Typography/TypographyProps.js, packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.js
Prevent default on mouse down event of the SimpleMenu component.
Prevent a bug on React 18.
Should work the same way
=> Fix simple menu click and fix some stories props

packages/strapi-design-system/src/themes/Theme.stories.mdx, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This PR replaces regular text with the Typography component in Theme stories. It fixes the dark text color on a dark background while switching between the Storybook themes.
The text is almost impossible to read right now.
-
=> fix(theme): use Typography to avoid color issue while switching theme

packages/strapi-design-system/package.json
Strapi design system requires an alpha version of strapi. This change just fixes that
Updated version for @strapi/icons to 1.1.1 in @strapi/design-system
To keep dependencies accurate and explicit
=> Fixing @strapi/icons peer dependency in design system

packages/strapi-design-system/src/ModalLayout/ModalBody.js, packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
During the tests for media library folders Maeva discovered the paddings of all modals should look different.
Refs: https://github.com/strapi/strapi/pull/13499
Consistent and beautiful styles.
=> ModalBody: Decrease horizontal paddings

packages/strapi-design-system/src/Card/Card.js, packages/strapi-design-system/src/Card/CardAsset.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
- Added a border to improve the accessibility of the Card component with Dark mode
- Fixed CardAsset not applying top `border-radius` on the `repeating-conic-gradient` background (see images below)
CardAsset background overflowing Card `border-radius` (not visible on the right side because `repeating-conic-gradient` property uses `neutral100` and transparent:
Fix by adding `border-top-left-radius` and right (overflow hidden on Card component could also be a solution):
=> [CONTENT-233] Card component border

packages/strapi-design-system/src/ThemeProvider/ThemeProvider.js
Fixes https://github.com/strapi/design-system/issues/629. On MacOS we are currently using the wrong system-font notation. Github uses the same notion (`-apple-system` instead of `--apple-system`).
| Before  | After  | 
|---|---|
| ![Screen Shot 2022-06-21 at 17 45 19-fullpage](https://user-images.githubusercontent.com/2244375/174842174-3b96531b-cbc3-4314-b756-17a5b18e2476.png)  | ![Screen Shot 2022-06-21 at 17 45 13-fullpage](https://user-images.githubusercontent.com/2244375/174842185-36fb3327-b288-4238-8246-7b1aded9a7c9.png)  |
| ![Screen Shot 2022-06-21 at 17 46 08-fullpage](https://user-images.githubusercontent.com/2244375/174842298-bd69033e-7657-4426-9e28-453cac8fb0f6.png)  | ![Screen Shot 2022-06-21 at 17 46 15-fullpage](https://user-images.githubusercontent.com/2244375/174842278-b96f …
=> DS: Fix global apple system font-family

LICENSE, packages/strapi-design-system/LICENSE, packages/strapi-icons/LICENSE
Adds a license file. The license is already mentioned in the [`package.json`](https://github.com/strapi/design-system/blob/main/package.json), but the file was missing from the repo.
To avoid users confusion, under which license the project is published.
- Fixes #619
=> Add MIT license file

packages/strapi-design-system/src/Layout/HeaderLayout.js, packages/strapi-design-system/src/Layout/HeaderLayout.stories.mdx, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
- Extending HeaderLayout subtitle type support needed for ML folders
=> [Breadcrumbs update] HeaderLayout subtitle node support

packages/strapi-design-system/src/Accordion/AccordionToggle.js, packages/strapi-design-system/src/Flex/Flex.js, packages/strapi-design-system/src/Flex/FlexProps.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This PR does a couple of things:
- it ellipsizes the title
-  to fix a bug mentioned in https://github.com/strapi/strapi/pull/12500#discussion_r817439733 and allows us to pass any string into the title without breaking the component
- to fix a bug we currently have on repeatable components <img width="800" alt="Screenshot 2022-07-14 at 18 34 42" src="https://user-images.githubusercontent.com/2244375/179032744-2039e4fe-27a6-45ca-b88d-0ad97c04383a.png">
- it refactors the component, to reduce it's size, since most of the component code was duplicated
- it reduces the explicit `height` and makes it a `min-height` to allow text to flow more naturally
Housekeeping and fixes a bug.
|Before|After|
|-|-|
| ![Screen Shot 2022-07-14 at 18 27 …
=> Accordion: Make height of AccordionToggle flexbile and add title ellipsis

package.json, packages/strapi-design-system/package.json, yarn.lock
Fixes the `test:e2e:watch` command. It was broken since the migration to the playwright test runner and is a very convenient tool, when having to work with the e2e tests. The solution has been mentioned in https://github.com/microsoft/playwright/issues/7035#issuecomment-858430649
Developer experience.
1. Run `yarn test:e2e:watch`
2. Change something in an e2e test file
3. Watch only the tests from that file being re-run
=> Fix e2e:watch command using chokidar-cli

packages/strapi-design-system/package.json, packages/strapi-design-system/src/NumberInput/NumberInput.js, packages/strapi-design-system/src/NumberInput/NumberInput.stories.mdx, packages/strapi-design-system/src/NumberInput/__tests__/NumberInput.e2e.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Fixes issue https://github.com/strapi/strapi/issues/11821: currently we don't display the appropriate number of digits after the comma for float values. This PR ensures, we display up to 21 digits after the comma instead of 3 by default.
To properly display float values across the UI.
1. Navigate to https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-components-numberinput--base
2. Enter `3.14159265359`
3. Blur the field
1. Navigate to https://design-system-git-fix-number-significant-digits-strapijs.vercel.app/?path=/story/design-system-components-numberinput--base
2. Blur the field
- Refs https://github.com/strapi/strapi/issues/11821
- Fixes https://github.com/strapi/design-system/issues/581
- Fixes https://strapi-inc.atlassian.net/browse/DS-69
- Fixes …
=> NumberInput: Fix maximum significant digits which are displayed

packages/strapi-design-system/src/Breadcrumbs/Breadcrumbs.js, packages/strapi-design-system/src/Layout/HeaderLayout.js, packages/strapi-design-system/src/Layout/HeaderLayout.stories.mdx, packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.js, packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.stories.mdx, packages/strapi-design-system/src/v2/Breadcrumbs/Crumb.js, packages/strapi-design-system/src/v2/Breadcrumbs/CrumbLink.js, packages/strapi-design-system/src/v2/Breadcrumbs/CrumbSimpleMenu.js, packages/strapi-design-system/src/v2/Breadcrumbs/Divider.js, packages/strapi-design-system/src/v2/Breadcrumbs/__tests__/Breadcrumbs.e2e.js, packages/strapi-design-system/src/v2/Breadcrumbs/index.js, packages/strapi-design-system/src/v2/index.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This is an alternative solution & implementation of https://github.com/strapi/design-system/pull/646 and https://github.com/strapi/design-system/pull/651 with a few advantages:
- the single `Crumb*` components are much simpler, because
- the `Divider` logic was abstracted at the `Breadcrumbs` level
- it works with much less style overwrites
I didn't fully understand the API for the other PR - this one follows the idea of:
- `CrumbLink`: is used to render a link
- `Crumb`: is used to render a non-link and can receive an `aria-current` prop, if it is the last one
- `CrumbSimpleMenu`: acts as an alias for `SimpleMenu` with meaningful defaults
[Preview](https://design-system-git-enhancement-breadcrumbs-simplified-strapijs.vercel.app/?path=/story/design-system-components-v2-breadcrumbs--with-me …
=> Breadcrumbs: Implement v2 version

packages/strapi-design-system/src/SubNav/SubNav.stories.mdx, packages/strapi-design-system/src/SubNav/SubNavLink.js, packages/strapi-design-system/src/SubNav/SubNavLinkSection.js, packages/strapi-design-system/src/SubNav/SubNavSection.js, packages/strapi-design-system/src/SubNav/SubNavSectionLabel.js, packages/strapi-design-system/src/SubNav/SubNavSections.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Improves visual hierarchy of sub nav panel by adjusting indentation of `<SubNavLinkSection>` child elements, and reducing overall `<SubNavLink>` top and bottom padding. 
WIP, but I believe it's complete, pending review.
Related to https://github.com/strapi/design-system/issues/637
*Before*
*After*
=> Add indentation styling to SubNavLinkSection child elements

CONTRIBUTING.md
I wasn't able to run the e2e tests locally and reverse engineered them from the CI. Especially the pinned playwright version should be in the setup instructions :)
For users to be able to run the e2e tests.
=> Docs: Update e2e test setup

packages/strapi-design-system/src/v2/Breadcrumbs/CrumbLink.js, packages/strapi-design-system/src/v2/Breadcrumbs/CrumbSimpleMenu.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This PR updates the interaction colors for `CrumbLink`s and `CrumbSimpleMenu`s from `neutral100` to `neutral200`.
These components are used on a background which is already `neutral100` and therefore the state won't be visible.
Validate the `hover/ focus` background colors on https://design-system-git-fix-breadcrumbs-interaction-strapijs.vercel.app/?path=/story/design-system-components-v2-breadcrumbs--with-menu
- https://github.com/strapi/strapi/pull/13788
- https://github.com/strapi/design-system/pull/653
=> Breadcrumbs: Update interaction colors

packages/strapi-design-system/src/DatePicker/DatePicker.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This removes the default `placeholder` attribute value for the `DatePicker` component. As has been discussed with @maevalienard and suggested in #663. It also removes some explicit props and passes them through `props` instead.
1. we don't have it on other input fields (consistency)
2. editors can not type into the field (yet) and therefore can not make a mistake
3. the format would need to be localized to be clear in every timezone
Validate the default placeholder is gone in [the component preview](https://design-system-git-fix-datepicker-placeholder-strapijs.vercel.app/?path=/story/design-system-components-datepicker--base)
- Fixes #663
=> DatePicker: remove default placeholder value

packages/strapi-design-system/src/Avatar/Avatar.js, packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Fixed image in Avatar component being stretched
=> [Fix] Avatar img resizing

packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js, packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.js, packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.stories.mdx, packages/strapi-design-system/src/v2/Breadcrumbs/Crumb.js, packages/strapi-design-system/src/v2/Breadcrumbs/CrumbLink.js, packages/strapi-design-system/src/v2/Breadcrumbs/CrumbSimpleMenu.js, packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
- Fixed some proptypes errors:
- Breadcrumbs did not accept a component that returns CrumbSimpleMenu (ex: CrumbSimpleMenuAsync for ML Breadcrumbs) + same issue for SimpleMenu components. Opened children Proptypes to `PropTypes.node`
- CrumbLink Proptypes pattern same as other DS components based on BaseLink
- SimpleMenu v1 & v2 + Breadcrumbs children proptypes
- Fixed Crumb not aligned because of different padding than `CrumbLink` and `CrumbSimpleMenu` and first child `margin-left`
Before
After
=> [Breadcrumbs] PropTypes & Crumb padding

packages/strapi-design-system/src/Link/Link.js, packages/strapi-design-system/src/v2/Link/Link.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Update Links font from `pi` to `omega` variant
Before:
After:
=> [Fix] Link font

packages/strapi-design-system/src/Combobox/__tests__/utils.spec.js, packages/strapi-design-system/src/Combobox/utils.js
Updates the filtering rule for the `Combobox` component.
Before, just showing options which starts with the typed term.
Now, displays options containing any part of the typed term.
Will help out to search for User Repositories at the Strapi Cloud Dashboard.
Unit tests.
E2E existent tests.
=> Combobox filtering behavior

packages/strapi-design-system/src/Alert/Alert.js, packages/strapi-design-system/src/Avatar/Avatar.js, packages/strapi-design-system/src/Breadcrumbs/Breadcrumbs.js, packages/strapi-design-system/src/Card/CardTimer.js, packages/strapi-design-system/src/Checkbox/Checkbox.js, packages/strapi-design-system/src/LinkButton/LinkButton.js, packages/strapi-design-system/src/Loader/Loader.js, packages/strapi-design-system/src/MainNav/NavLink.js, packages/strapi-design-system/src/ProgressBar/ProgressBar.js, packages/strapi-design-system/src/Radio/Radio.js, packages/strapi-design-system/src/Searchbar/Searchbar.js, packages/strapi-design-system/src/Tag/Tag.js, packages/strapi-design-system/src/v2/Breadcrumbs/Crumb.js, packages/strapi-design-system/src/v2/Breadcrumbs/CrumbLink.js, packages/strapi-design-system/src/v2/LinkButton/LinkButton.js
In the tests of the core repo we see a couple of prop-type errors, because some components can only render `string` for `children` props. This PR opens many of these to be able to receive `node` instead.
While `string` might work, it sometimes might not, if `formatMessage()` renders sub-components as replacements. I think opening `children` doesn't do any harm, because using a node instead of pure text isn't harmful in most cases, such as:
```js
<Checkbox>
<span>Label</span>
</Checkbox>
```
I think it avoids some frustration in the future and I think `string` is too strict in most cases.
=> chore: Update many children prop-types from string to node

packages/strapi-design-system/src/NumberInput/NumberInput.js, packages/strapi-design-system/src/NumberInput/__tests__/NumberInput.e2e.js
Fixes `NumberInput`, if scientific values were entered. 
Currently, if you enter a scientific number into the `NumberInput` the following happens:
- enter `0.00000001`
- blur
- focus
- values switches to `1e-8` and can not be edited any longer
This PR makes sure, we display `0.00000001` even after the focus event.
I've added an automated test.
- Fixes https://github.com/strapi/design-system/issues/671
=> NumberInput: Keep scientific numbers after blur/ focus as value

packages/strapi-design-system/src/Popover/Popover.js, packages/strapi-design-system/src/helpers/useIntersection.js
Fixes the `onReachEnd` callback on `Popover` components. It is currently broken due to 2 reasons: 1) the element that is being checked for intersection has a width/ height of 9 2) the element is never fully intersecting (threshold).
Fixes a bug, where the callback was not called.
1. Add `hasMoreItems` to the `base` `Combobox` example
2. Add a `onReachEnd` callback
3. Scroll to the end
- Fixes https://github.com/strapi/design-system/issues/672
=> Popover: Fix onReachEnd callback

packages/strapi-design-system/src/ToggleInput/ToggleInput.js, packages/strapi-design-system/src/ToggleInput/ToggleInput.stories.mdx, packages/strapi-design-system/src/ToggleInput/__tests__/ToggleInput.e2e.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Does not display the "clear" button if the field is disabled.
To disallow clearing a field, if it is disabled.
Use the disabled story of "ToggleInput"
- Fixes https://github.com/strapi/design-system/issues/670
=> ToggleInput: Remove clear button, if the field is disabled

packages/strapi-design-system/src/CarouselInput/Carousel.js, packages/strapi-design-system/src/CarouselInput/CarouselInput.js, packages/strapi-design-system/src/Checkbox/Checkbox.js, packages/strapi-design-system/src/Combobox/Combobox.js, packages/strapi-design-system/src/Field/Field.js, packages/strapi-design-system/src/NumberInput/NumberInput.js, packages/strapi-design-system/src/Select/Select.js, packages/strapi-design-system/src/TextInput/TextInput.js, packages/strapi-design-system/src/Textarea/Textarea.js, packages/strapi-design-system/src/TimePicker/TimePicker.js, packages/strapi-design-system/src/ToggleInput/ToggleInput.js
Allows `node` prop-types to be passed in as `hint` for `TextInput` components.
I think it makes sense to open that prop, so that users can add e.g. multiline-text.
- Fixes https://github.com/strapi/design-system/issues/667
=> Relax hint prop-types from string to node

packages/strapi-design-system/src/Combobox/Combobox.js
Allow the combobox to display the required state.
=> Pass the required prop to the combobox FieldLabel

packages/strapi-design-system/src/NumberInput/NumberInput.js
It fixes the `NumberInput` field:
- `maximumSignificantDigits` -> `maximumFractionDigits`: The maximum number of fraction digits to use: this is what I wanted in the first place, to fix scientific numbers.
- `numberParserRef` does not have a `.format()` method. I broke that in https://github.com/strapi/design-system/pull/683 and have no idea why the tests worked.
Fixes https://github.com/strapi/design-system/issues/693
=> NumberInput: Fix value assignment during focus

packages/strapi-design-system/src/themes/Theme.stories.mdx, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
`buttonNeutral0`, `buttonPrimary500` and `buttonPrimary600` were excluded from the documentation which makes it hard to customize theme in Strapi
=> [Fix] Document button color tokens to sroy

packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.js, packages/strapi-design-system/src/v2/Breadcrumbs/Breadcrumbs.stories.mdx, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Fix the breadcrumb when only one link is displayed.
To avoid rendering the `/` when the breadcrumb contains only one link
=> Fix Breadcrumb with one Crumb

packages/strapi-design-system/src/DatePicker/DatePicker.js, packages/strapi-design-system/src/DatePicker/DatePicker.stories.mdx, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.js, packages/strapi-design-system/src/DatePicker/utils/formatDate.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Similar to https://github.com/strapi/design-system/pull/687: it allows us to pass in a locale (e.g. from users choice in strapi core), which overrides the one from `navigator`.
To locale fields to the selected locale of a users instead of the one from the browser.
* I've added some snapshot testing of the input value for EN & DE
* Added a new story to illustrate the locale in DE
=> DatePicker: Allow to pass in a locale

packages/strapi-design-system/src/Accordion/Accordion.stories.mdx, packages/strapi-design-system/src/KeyboardNavigable/KeyboardNavigable.js, packages/strapi-design-system/src/RawTable/RawCell.js, packages/strapi-design-system/src/RawTable/RawTable.js, packages/strapi-design-system/src/RawTable/RawTable.stories.mdx, packages/strapi-design-system/src/RawTable/RawTableContext.js, packages/strapi-design-system/src/RawTable/RawTbody.js, packages/strapi-design-system/src/RawTable/RawThead.js, packages/strapi-design-system/src/RawTable/RawTr.js, packages/strapi-design-system/src/RawTable/__tests__/RawTable.e2e.js, packages/strapi-design-system/src/Table/Table.stories.mdx, packages/strapi-design-system/src/helpers/getFocusableNodes.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
This PR does two things –
* removes the immediate call of `preventDefault()` in `KeyboardNavigable` which hijacks all keyboard events from inputs wrapped inside e.g. `Accordion` (issues https://github.com/strapi/design-system/issues/614 & https://github.com/strapi/strapi/issues/12432)
* Reworks `RawTable` because the aria-pattern implementation was missing handle cases for when cells had fields within that have their own keyboard navigation / more than one focussable field (issue https://github.com/strapi/design-system/issues/642)
* Also sets up so if you click on a focusable child of a `RawTable Cell` then the focussing starts at that point
Users were unable to do a couple of things:
* Were unable to use keyboard navigation in fields within Accordions (e.g. to move the caret)
* Were …
=> [KeyboardNavigable & RawTable]: fix keyboard navigation on child elements

packages/strapi-design-system/src/Popover/Popover.js, packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js, packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.js
Since the Popover is handled by `floating-ui`, we are now able to choose where the popover will be handled. This update will be helpful for the Strapi Cloud app
=> Add placement props to Popover component

packages/strapi-design-system/src/Link/Link.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Specifically targets the `Typography` class nested in the `Link` component
Styles applied for `hover` and `active` were not affecting the text color accurately.
CONTENT-477
=> fix: link active & hover not affecting Typography

packages/strapi-design-system/src/ToggleCheckbox/ToggleCheckbox.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Set `z-index` to `0` on the `Label` of ToggleCheckbox.
it's absolute children break out of the parent currently and will therefore show on top of popovers
CONTENT-572
=> fix: set z-index on Label to avoid z-index breaking out of parent

packages/strapi-design-system/src/Box/Box.js, packages/strapi-design-system/src/CarouselInput/Carousel.js, packages/strapi-design-system/src/CarouselInput/Carousel.stories.mdx, packages/strapi-design-system/src/CarouselInput/CarouselImage.js, packages/strapi-design-system/src/CarouselInput/__tests__/CarouselImage.e2e.js, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
Added ImageBase styled for Box if Box has as("img") attribute to show alt text (ellipsis for long texts) & added tooltip over carousel image for alt text.
When a CarouselInput's slide image src can't be found, long alt text overflow out of the image.
In CarouselInput replace src with an empty string and place long alt text.
Design-System #692
=> [Fix]: unbroken carousel image alt text overflows out of carousel input

packages/strapi-design-system/src/Typography/Typography.js, packages/strapi-design-system/src/Typography/TypographyProps.js, packages/strapi-design-system/src/Typography/__tests__/Typography.spec.js, packages/strapi-design-system/src/Typography/__tests__/__snapshots__/Typography.spec.js.snap
Implements `textAlign` as alias for `text-align` on the `Typography` component.
To support more properties that control the text-rendering.
- Closes https://github.com/strapi/design-system/issues/718
=> Typography: Add textAlign property

packages/strapi-design-system/src/themes/ColorButton.js, packages/strapi-design-system/src/themes/Theme.stories.mdx, packages/strapi-design-system/tests/__snapshots__/storyshots.spec.js.snap
New way to display theme color palettes.
In order to show the `warningXXX` colors (this color is currently hidden), I had to add a white box to avoid color contrast warning.
Screenshots
=> Fix theme colors stories

packages/strapi-design-system/tests/check-exports.spec.js, packages/strapi-design-system/tests/filesToKeep.js
Adds an exception for `.DS_Store` files, when comparing exports.
I often have one failing test, which stems from the fact that my os creates a file called `.DS_Store`. I'd like the test to ignore that file when checking for export equality.
Believe in jest.
=> Jest: Respect os specific files for the check-exports test

packages/strapi-design-system/src/Status/Status.js, packages/strapi-design-system/src/Status/__tests__/Status.spec.js
It makes the preceding bullet of the [`Status`](https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-components-status--base) component configurable through a prop called `showBullet`.
The bullet is not part of any `Status` component any longer. To stay visually consistent, I've added a new prop, which allows disabling the bullet and renders only `children` instead.
I think we could approach this differently if we'd want:
1. We could argue the bullet is decoration and, therefore, we can change it right away. This way, we'd have to keep the child `Flex` around.
2. We could create a new v2 version of the component which does not know about `Bullet` or `Flex`, but I feel like it adds too much unnecessary overhead.
In the spirit of composability, I think getting rid …
=> Status: Make preceding bullet configurable

packages/strapi-design-system/src/Status/Status.js, packages/strapi-design-system/src/Status/Status.stories.mdx
Adds a new `size` prop (possible values are `S` and `M`) to the `Status` component.
➡️ [Preview](https://design-system-git-enhancement-status-strapijs.vercel.app/?path=/story/design-system-components-status--size-s)
The current UI Kit styles know two states for `Status`: the one we have (M) and small (S):
- Refs https://github.com/strapi/strapi/pull/14761
=> Status: Add small variant

packages/strapi-design-system/src/DismissibleLayer/DismissibleLayer.js
* checks the closest react-portal to avoid other portalled elements closing the layer
* because it breaks the CMS
* #752
=> fix: dismissible layer closing prematurely

packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.js
Wraps the component into a `div` so that styles don't interfere with parent styles.
`CheckboxInput` overwrites `margin`. In case of the settings pages for example, this creates a problem because it would overwrite spacing defined by `Stack`:
With this fix the `margin` reset is properly isolated:
- Refs https://github.com/strapi/strapi/issues/14763
=> BaseCheckbox: Wrap component into Box to isolate style resets

packages/strapi-design-system/.eslintrc.js, packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.stories.mdx, packages/strapi-design-system/src/Checkbox/Checkbox.stories.mdx, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.js, packages/strapi-design-system/src/DismissibleLayer/__test__/DimissibleLayer.spec.js, packages/strapi-design-system/src/IconButton/IconButton.js, packages/strapi-design-system/src/IconButton/IconButton.stories.mdx, packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js, packages/strapi-design-system/src/Status/Status.stories.mdx, packages/strapi-design-system/src/Switch/Switch.stories.mdx
* Allows passing children as opposed to icon (although PropTypes aims to enforce we should pass one or the other)
* Ensure if you don't pass a label you pass an `aria-label` cause there's no excuse for no accessibility
* Set no-undef in `eslint` to `error` cause it's a better DX imo
* Adds extra accessibility flags to the `icon`/`children` via `cloneElement`
* Use's `VisuallyHidden` spans because iirc translators are more likely to translate those than aria-labels and it's clearer from a code POV
* Because I'm adding drag and drop to relation items and the drag icon _needs_ to be accessible.
=> [enhancement]: IconButton

packages/strapi-design-system/src/IconButton/IconButton.js
* if `icon` is present we use that over `children`
* for backwards compatibility 
* raised internally
=> [fix][IconButton]: use `icon` if it's passed over children

packages/strapi-design-system/src/Button/Button.js, packages/strapi-design-system/src/Button/Button.stories.mdx, packages/strapi-design-system/src/Button/constants.js, packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js, packages/strapi-design-system/src/themes/sizes.js
Updates the buttons to use the heights defined in the [UI Kit](https://www.figma.com/file/PICiE8O4NLrHO1lhJftLdE/Strapi---UI-Kit-%F0%9F%A7%A9?node-id=9974%3A117504):
- `S`: 32px
- `M`: 36px
- `L`: 40px
1. Currently the different sizes look messed up:
| Before | After |
|-|-|
| <img width="316" alt="Screenshot 2022-11-08 at 17 05 29" src="https://user-images.githubusercontent.com/2244375/200616417-44974f91-6de2-433c-855f-066b985f322e.png"> | <img width="316" alt="Screenshot 2022-11-08 at 17 20 57" src="https://user-images.githubusercontent.com/2244375/200619343-78db43ea-6807-404f-88f9-d0eecc3318b4.png"> |
➡️ [Preview](https://design-system-git-fix-button-height-strapijs.vercel.app/?path=/story/design-system-components-button--sizes)
I did my best to compose the height out of `line-height` …
=> Button: Unify component height with the UI Kit

packages/strapi-design-system/src/ProgressBar/ProgressBar.js, packages/strapi-design-system/src/ProgressBar/ProgressBar.stories.mdx
- Refactors the component to use `Box` as base component
- Update progress-color from `neutral150` to `neutral0`
➡️ [Preview](https://design-system-git-enhancement-progressbar-strapijs.vercel.app/?path=/story/design-system-components-progressbar--m)
- Follow the UI Kit
- https://strapi-inc.atlassian.net/browse/CONTENT-220
=> ProgressBar: Refactor component to use Box as base

packages/strapi-design-system/src/Badge/Badge.js, packages/strapi-design-system/src/Badge/Badge.stories.mdx, packages/strapi-design-system/src/themes/sizes.js
- Updates the height of the `Badge` to match the UI Kit
| Before | After |
|-|-|
| <img width="89" alt="Screenshot 2022-11-14 at 12 08 29" src="https://user-images.githubusercontent.com/2244375/201645342-0ff30c6f-1f9f-4d69-9018-9ba82f4b3dd0.png"> | <img width="89" alt="Screenshot 2022-11-14 at 12 08 35" src="https://user-images.githubusercontent.com/2244375/201645350-349e10d4-68d6-4c5d-b7b4-c92f7dcd28d2.png"> |
- Updates the colors
- Updates the `border-radius` from `4px` to `2px`
Match the UI Kit
- https://strapi-inc.atlassian.net/browse/CONTENT-220
=> Badge: Update colors and height according to the UI kit

packages/strapi-design-system/src/SimpleMenu/SimpleMenu.js
Add the prop `onReachEnd` to the SimpleMenu popover
Needed to append additional items when items are retrieved from a server.
consume the prop from any `<SimpleMenu />` component in storybook
```
<SimpleMenu id="label" label={val} onReachEnd={() => console.log('END')}>
```
if enough items there should be a log in the console
=> chore: Improve SimpleMenu component

packages/strapi-design-system/src/index.js
* Removes `v2` from the exports list
* Doesn't export RadioGroup twice as well
* As discussed in the DS sync we're removing the `v2` exports from the `index` as it breaks the package, they'll only be exported from `@strapi/design-system/v2`
* resolves #781
=> [imports]: don't use duplicate imports as the application breaks

packages/strapi-design-system/src/themes/Theme.stories.mdx
Fix the issue we have with the Theme storybook
Because we can't see the theme storybook
check https://design-system-aw9pd8kew-strapijs.vercel.app/?path=/story/design-system-components-theme--light-colors
=> Restore theme storybook

packages/strapi-design-system/LICENSE, packages/strapi-icons/LICENSE
In https://github.com/strapi/design-system/pull/636 I've made a mistake a added a standard MIT license instead of the Strapi MIT license. This PR reverts the changes in 5e54a86a08f1ce37409eac0ed990afcaae7a30a6 and bacc8686653e95fb116d9119f01fb52976772c50. 
Legal requirements.
=> Update LICENSE from MIT to Strapi MIT

packages/strapi-design-system/src/Alert/Alert.js, packages/strapi-design-system/src/Alert/Alert.stories.mdx, packages/strapi-design-system/src/Alert/utils.js
This PR adds `Warning` variant to the `Alert` component.
Needed for product licensing business logic. 
Pass the `warning` variant to the `Alert` component
=> Add 'Warning' variant to the 'Alert' component

packages/strapi-icons/assets/icons/Bold.svg, packages/strapi-icons/assets/icons/BulletList.svg
`Bold` and `BulletList` svgs had broken `viewBox` 
| before  | after  |  
|---|---|
| <img width="103" alt="image" src="https://user-images.githubusercontent.com/71838159/209797212-841f3f32-aaa6-46dc-93e9-a902325a398a.png"> | <img width="100" alt="image" src="https://user-images.githubusercontent.com/71838159/209797268-a588484e-a8ac-42f9-9da0-cc1a2ad7c5e1.png"> |
=> [fix] Bold & BulletList svg viewbox

packages/strapi-design-system/src/Table/Cell.js, packages/strapi-design-system/src/Table/Table.stories.mdx, packages/strapi-design-system/src/Tooltip/Tooltip.js, packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.js
Adding a `Tooltip` to one of the Table header would break the alignment 
Replacing the `span` ref wrapper with `Flex` seems to fix this issue
Open to suggestion for a better fix
Remove unnecessary `div` if no `action` was passed
|  before | after |  
|---|---|
| <img width="480" alt="Screenshot 2022-12-27 at 09 41 56" src="https://user-images.githubusercontent.com/71838159/209639438-44af8c2b-cccc-409d-bf0b-a2c632fb987f.png">  | <img width="494" alt="Screenshot 2022-12-27 at 09 42 07" src="https://user-images.githubusercontent.com/71838159/209639481-f2757b81-e111-45bc-a31d-dbe202eeee85.png">  |
=> [fix] Tooltip misalignment 

packages/strapi-design-system/src/DatePicker/DatePicker.js, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.e2e.js
Revert back the minDate and maxDate props in the DatePicker
Because it is not still possible to add some limits to the DatePicker component.
Run the storybook and check the minDate and maxDate component to see if it is possible to select value minor than 2000 and bigger than 2040
Fix [#822](https://github.com/strapi/design-system/issues/822)
=> [fix] minDate not working for DatePicker component

LICENSE
Updates the license of the monorepo from MIT to Strapi MIT.
In https://github.com/strapi/design-system/pull/799 I forgot to update the license in the monorepo.
=> Update LICENSE from MIT to Strapi MIT for the monorepo

CONTRIBUTING.md, package.json, yarn.lock
Removes @specifyapp/cli from our dependencies.
We aren't using the sync between Figma and the design-system any longer. It was useful at the beginning but now tokens and icons are quite stable and we rarely have to change them. If so, these can be done manually. Also: not all icons are in sync with Figma anymore and the integration causes more harm/ questions than it does good for us.
Also: apparently this cleans up the lockfile quite a bit. 🚀 
I'll wait for @Aurelsicoko s approval before merging.
- Closes https://github.com/strapi/design-system/pull/830
=> Chore: Remove @specifyapp/cli as a dependency

packages/strapi-design-system/src/Avatar/Avatar.js, packages/strapi-design-system/src/Avatar/Avatar.stories.mdx
Allow background and textColor customization for `Initials` component
=> [enh] Initials customization

packages/strapi-design-system/vite.config.js, packages/strapi-icons/vite.config.js
* changes the target to `esnext`
* Originally i had it at this or es2020 but then webpack caused issues in the admin app when trying to convert it down to 2015 🤔 Now this – https://github.com/strapi/strapi/pull/15369 is open, we can go back to being _super flexible_
* `esnext` performs as little transpilation as possible, this is perfect for a library because some people may want to support 2018 but if we compile to 2015, we're making life difficult for them – https://vitejs.dev/config/build-options.html#build-target
=> chore: use esnext

packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.js, packages/strapi-design-system/src/Avatar/constants.js
CONTENT-960
fixes #844
As discussed, Avatar size will now be `32px` / `theme.spaces[7]`
=> [enh] Update Avatar size 

packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.js
Add the prop onReachEnd to the SimpleMenu popover
This are the exact same edits I did for v1 component: [prev PR](https://github.com/strapi/design-system/pull/782)
Needed to append additional items when items are retrieved from a server.
consume the prop from any <SimpleMenu /> component in storybook
```
<SimpleMenu id="label" label={val} onReachEnd={() => console.log('END')}>
```
if enough items there should be a log in the console
=> chore: add onReachEnd popover callback to SimpleMenu v2 component

packages/strapi-design-system/src/MainNav/NavSections.js, packages/strapi-design-system/src/v2/MainNav/NavSections.js
Replace `overflow: scroll` with `overflow: auto` for `NavSections` as it would force scrollbar being displayed even when not needed
=> [Fix] MainNav overflow auto

packages/strapi-design-system/src/Accordion/Accordion.tsx
It forwards the `shadow` prop on the `Accordion` component to the underlying `Box`.
It allows us to render the Accordion with a shadow:
This is a design-requirement for review workflows. We can make use out of this for dynamic-zones too, which are currently using a style override:
```js
const StyledBox = styled(Box)`
> div:first-child {
box-shadow: ${({ theme }) => theme.shadows.tableShadow};
}
`;
```
=> Accordion: forward shadow prop

packages/strapi-design-system/src/DateTimePicker/__tests__/__snapshots__/DateTimePicker.spec.js.snap, packages/strapi-design-system/src/Select/__tests__/Select.spec.js, packages/strapi-design-system/src/Stack/Stack.tsx, packages/strapi-design-system/src/TimePicker/__tests__/TimePicker.spec.js
Prevents the `spacing` prop of the `Stack` component to be rendered as attribute on DOM nodes.
It is not a valid HTML attribute nor expected the attribute is rendered.
Check the generated HTML for https://design-system-git-chore-stack-dom-attrs-spacing-strapijs.vercel.app/iframe.html?args=&id=design-system-technical-components-stack--base&viewMode=story
- Fixes https://github.com/strapi/design-system/issues/846
=> Stack: Prevent `spacing` prop to be rendered on DOM nodes as attribute

.github/workflows/tests.yml
* removes the path filtering for PR workflows
* tests are "required" but then they don't run so PRs are left in limbo
* #836
=> workflows not running but are required

packages/strapi-design-system/src/JSONInput/JSONInputContainer.js
- Fixes a small gap between the editor and the border
before
after
Check if there is a gap
=> [fix] borderRadius on json input

packages/strapi-design-system/src/JSONInput/JSONInput.js
Focuses the JSONInput when clicking the label and it is not disabled
- Go to the editable input and click the label, it should focus the editor and apply the focus styles, you should be able to type
- Go to a disabled input and add a label, click the label, it shouldn't do anything
resolves https://github.com/strapi/design-system/issues/862
=> [fix] Focus the editor when clicking the label

packages/strapi-design-system/src/Avatar/__tests__/Avatar.spec.tsx, packages/strapi-design-system/src/Box/Box.tsx, packages/strapi-design-system/src/Box/__tests__/Box.spec.tsx
Ensures the `Box` component does not render the following props as HTML attributes:
- `width`
- `height`
- `cursor`
- `color`
Became evident in https://github.com/strapi/design-system/pull/878.
Follow the 🐇 automated tests.
=> Box: Extend transient props

packages/strapi-design-system/src/Field/Field.js, packages/strapi-design-system/src/Select/Select.js, packages/strapi-design-system/src/TextInput/TextInput.js, packages/strapi-design-system/src/TimePicker/TimePicker.js
Fixes a missing boolean proptype validation
It throws an error in the console and is breaking tests in the CMS
The only way I found was to:
vite build this branch then copy the dist folder to replace the one in the node_modules in Strapi on this branch https://github.com/strapi/strapi/pull/15706#pullrequestreview-1283236627, run the tests over there for DateTimePicker:
```
yarn test:front packages/core/helper-plugin/lib/src/components/DateTimePicker/tests/index.test.js --updateSnapshot
```
or run all the tests
- https://github.com/strapi/design-system/pull/864
- https://github.com/strapi/strapi/pull/15706#pullrequestreview-1283236627
=> Fix missing proptype validation

.github/workflows/bundle-size.yml
Enables the bundle-size action on all PRs.
With the introduction of release branches it is not sufficient any longer to run the bundle-size action when merging into main.
=> GitHub: Run bundle-size reporter on every PR

packages/strapi-design-system/src/Box/Box.tsx, packages/strapi-design-system/src/IconButton/IconButton.tsx
fixing no border application on `IconButton` 
| Before | After |
|-|-|
| <img width="577" alt="Screenshot 2023-02-14 at 10 05 15" src="https://user-images.githubusercontent.com/71838159/218689749-081e1015-15ce-4dc8-89d8-03671d878d81.png">  | <img width="535" alt="Screenshot 2023-02-14 at 10 04 29" src="https://user-images.githubusercontent.com/71838159/218689801-63392797-6cbc-41cc-969e-0b16f923c68e.png"> |
=> [fix] IconButton no border

packages/strapi-design-system/src/Layout/HeaderLayout.js
As a developer managing transfer tokens of API tokens, I want to have a limit on the maximum number of characters per tone name.
Because we have some UI issues with long names
The activity must not be breaking change and so it must only affect the frontend validation
- As a developer with the permissions useful to create or edit a API tokens and transfer tokens
- when I create an existing API token
- then I want the validation on the Name field to limit the length of the field up to 100 characters
- when I access the API tokens list
- then I want the name trimmed as the description field
- when I create an existing transfer token
- then I want the validation on the Name field to limit the length of the field up to 100 characters
- when I access the transfer tokens list
- then I want the …
=> No length limit on the name for the API token or transfer token 

package.json
* Passes lint-staged arguments to the lint commands
* Adds prettier check to lint-staged too
* You can't commit without using `--no-verify`
* @simotae14 reported this to me.
=> Forward arguments to individual lint commands

.github/workflows/experimental.yml, package.json, scripts/pre-publish.sh
* Adds Github action for people to make their own experimental releases exactly the same as Strapi
* Will give more autonomy to squads
@alexandrebodin what's the best way to handle the NPM token? Should I add my own or would it make more sense to add a more generic user? I'm not sure what we use for the main Strapi repo.
=> Add experimental release workflow

packages/strapi-design-system/src/Field/FieldHint.tsx, packages/strapi-design-system/src/Field/__tests__/Field.spec.tsx
Removed `typeof hint !== 'string'` check in `FieldHint.tsx`
ReactNodes won't go through the check. This input
```javascript
<TextInput
label="Key"
hint={
<>
Do this{" "}
<Link href="https://strapi.io/" isExternal>
here
</Link>
</>
}
required
/>
```
wouldn't display a hint due to it not being a string.
Not sure, whether additional tests are needed.
—
=> Remove field hint type check for string

docs/stories/IconButton.stories.mdx, packages/strapi-design-system/src/BaseButton/BaseButton.tsx, packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.js
- Updates the `IconButton` stories to use a background-color, which is never used in the button itself to make the background-color of the button itself visible. Before they were the same which made me miss they are now transparent instead of white.
- Merges the `background` prop in `BaseButton`
Components inheriting from `BaseButton` may set `background=undefined` if they don't want to set a background-color explicitly (e.g. for a ternary). Merging props with `background=undefined` leads to the original value being overwritten. This PR prevents that by checking for a fasly value.
- Broke in https://github.com/strapi/design-system/pull/878
=> BaseButton: Merge background prop with falsy values

packages/strapi-design-system/src/DatePicker/DatePicker.tsx
Fixes issue with date picker icon not being visible in dark mode
The icon for date picker was only visible in light mode
1. Go to storybook for design system and go to DatePicker or DateTimePicker components. 
2. Toggle between light and dark mode
3. The icon on date picker should be visible on both modes and should be the same colour as the icon for time picker
Haven't created an issue for this. Let me know if I should create one
=> Fixes issue with date picker icon not being visible in dark mode

CONTRIBUTING.md
Updates the contributing docs for linking the DS to a react application
Yarn link works differently with yarn 3
Follow the steps to link a local copy of the DS to a react app
=> Update yarn link docs

packages/strapi-design-system/src/Layout/HeaderLayout.js, packages/strapi-design-system/src/Popover/Popover.tsx, packages/strapi-design-system/src/Popover/__tests__/Popover.spec.tsx
Removes the z-index which is apparently unnecessary.
The z-index causes the popover to overlap a navbar in the CMS
Berfore:
After:
Run yarn build in the DS
Head to the CMS and from the root run
```
yarn link -r ../<relative-path-to-strapi-design-system>
```
In examples getstarted yarn build && yarn develop
Go to the CM or Audit Logs or the Marketplace, make sure you have enough content to be scrollable, and scroll down the page.
(I'll update the strapi docs since it seem yarn link works differently now)
=> Remove z-index causing navbar overlap in the CMS

packages/primitives/src/components/Select/Select.tsx
* wraps only the placeholder in a span
* ensure styling is used and the placeholder re-renders after portals
=> fix: only use a span on the placeholder text

docs/package.json, package.json, packages/primitives/package.json, packages/primitives/src/components/Select/Select.tsx, packages/strapi-design-system/package.json, packages/strapi-design-system/src/Combobox/Combobox.tsx, packages/strapi-design-system/src/Popover/Popover.tsx, packages/strapi-design-system/src/Select/MultiSelect.tsx, packages/strapi-design-system/src/Select/SelectParts.tsx, packages/strapi-design-system/src/Select/SingleSelect.tsx, packages/strapi-design-system/src/Tooltip/__tests__/Tooltip.spec.tsx, packages/strapi-design-system/src/hooks/__tests__/useId.spec.tsx, packages/strapi-design-system/src/hooks/useIntersection.ts, packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.tsx, packages/strapi-icons/package.json, yarn.lock
* Moves the repo to use `react@18` for local development and allows it as a peer-dep
* Fixes some types that needed better narrowing with react@18
* escapes the ID used in `useIntersection` so `useId` can be used.
* We know react18 works fine with this library and as we move to make the CMS use `react@18` this is a part of that migration
* Should be merged after #962
=> Update to react18 internally & allow in peer-deps

packages/strapi-design-system/src/Select/Option.tsx, packages/strapi-design-system/src/Select/Select.tsx, packages/strapi-design-system/src/Select/__tests__/Select.spec.tsx
* Uses a small context to enable multi inference for the `Option` component
* because cloneElement is evil and must be stopped
=> Infer the `multi` prop on `Option` based on the value passed to `Select`

packages/strapi-design-system/src/Combobox/Combobox.tsx
* uses `useControllableState` to manage the open state of the combobox
* Need it to call search for relations in the CMS
=> Add the ability to manage the open state of the combobox externally

packages/primitives/src/components/Combobox/Combobox.tsx, packages/strapi-design-system/src/Combobox/Combobox.tsx, packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx
* Lets you hit `Enter` to submit the value IF the textValue matches that of an Option.
* Lets you control the filterValue externally
* enables you to add onChange to the `textValue`
* fully controls the `open` state
* Handles some timeouts a bit better
* Working with the RelationInput exposed a couple of edge cases
=> Combobox tweaks

packages/strapi-design-system/src/Combobox/Combobox.tsx, packages/strapi-design-system/src/Popover/Popover.tsx, packages/strapi-design-system/src/Select/MultiSelect.tsx, packages/strapi-design-system/src/Select/SingleSelect.tsx, packages/strapi-design-system/src/Select/__tests__/Select.spec.tsx, packages/strapi-design-system/src/helpers/__tests__/strings.test.ts, packages/strapi-design-system/src/helpers/escapeSelector.ts, packages/strapi-design-system/src/helpers/strings.ts, packages/strapi-design-system/src/v2/SimpleMenu/SimpleMenu.tsx
* generate a unique intersection id instead of trying to use part of the input's id
* r18's id hook generates `:r18` which is invalid so you need to escape the CSS, this becomes an issue in instances where we pass strange ids e.g. the RelationInput where the input name is the id. It's easier just to generate an id we know will be a number or `:r18:` so we can just strip `:`.
=> Use specific intersection ids

packages/primitives/src/components/Combobox/Combobox.tsx, packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx
* adds a check to see if there are any items, if there are no items we show "create" by default
* The "create component" combobox has no items by default but right now you can't create anything either
* I added an automated test 🪄 
* resolves https://github.com/strapi/strapi/issues/16677
=> When combobox has no items show the creatable option

docs/stories/Select.stories.mdx, packages/primitives/src/components/Combobox/Combobox.tsx, packages/primitives/src/components/Combobox/__tests__/index.test.tsx
* Uses `FocusScope` to capture the focus for the input and popover of the Primitive/Combobox
* Removes the `handleDismiss` callback to "sort out" the value on blur and moves it to the input to make it more predictable
* Adds `useFocusGuards` similarly to be inline with the Select primitive
* The popover wouldn't close when you tabbed away from it to another focussable element and if you added the expected callbacks we wanted when you leave the combobox it would cause other issues. It was simpler and perhaps more predictable to match the behaviour of the Select enforcing a user to close the popover first before tabbing away. It also means the aria-scoping makes more sense because you are in fact locked to what you can focus.
* Automated testing! Turns out my tests weren't that great but …
=> Bring primitive/Combobox popover behaviour to be in line with Select

packages/strapi-design-system/src/Layout/ActionLayout.tsx
Flattens the DOM structure of the `Layout` component.
It was bloated unnecessarily (bundle-size and DOM depth)
Follow up of https://github.com/strapi/design-system/pull/1043
=> Chore: Flatten Layout component

packages/strapi-design-system/src/Layout/ActionLayout.tsx
Fixes rendering of the `ActionLayout`.
In https://github.com/strapi/design-system/pull/1043 I've made a mistake and converted:
```
startActions || endActions ? (<Component />) : null
```
to
```
if (!startActions || !endActions) {
return null;
}
```
which is not the same. The operator should be AND.
This will help to fix the broken tests for Audit Logs in https://github.com/strapi/strapi/pull/16843
=> Chore: ActionLayout - fix actions condition

packages/strapi-design-system/src/Button/Button.tsx, packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.tsx
Fixes the size of icons in `Button` components.
It lead to alignment issues and doesn't follow the UI Kit.
|Before|After|
|-|-|
| <img width="580" alt="Screenshot 2023-05-26 at 15 50 30" src="https://github.com/strapi/design-system/assets/2244375/dfaad6aa-3a3e-43f8-948c-e7f0a9511035"> | <img width="580" alt="Screenshot 2023-05-26 at 15 50 13" src="https://github.com/strapi/design-system/assets/2244375/e3d7cc2a-7a48-40c8-bba5-d35360bf4d09"> |
- Broke in https://github.com/strapi/design-system/pull/878
- Fixes https://github.com/strapi/design-system/issues/1079
=> Fix: Button start and end icon size

packages/primitives/src/components/Combobox/Combobox.tsx, packages/primitives/src/components/Combobox/__tests__/index.test.tsx
* uses filterValue or textValue depending on autocomplete mode to show the NoValueFound element 
* Does not show NoValueFound when autocomplete is `none` because nothing is being filtered
* solves race condition between opening list and trying to focus an item causing the wrong items to fill autocomplete because they're no being rendered
* refactors code to ensure we always have the slot data so we can avoid rendering no value in split seconds (bad flashes are caused) – this is mainly just a quick shuffle to avoid duplication unnecessarily
* Combobox very nitty bugs that we've found battle testing it in Strapi CMS 
* realistically you want to connect it to the CMS & use the react-select branch
=> fix: combobox filtering / race-condition and flash rendering

packages/strapi-design-system/src/Alert/Alert.tsx, packages/strapi-design-system/src/Alert/utils.ts
Optimizes the `Alert` component:
- reduces the DOM depth
- moves custom CSS into styled props
- aligns the component better with the UI Kit: icon was too small, close was too big, gap's did not match
Request from design.
They should look almost identical to before.
=> Fix: Optimize Alert component for size and align styles with UI Kit

lerna.json, packages/primitives/package.json, packages/strapi-design-system/package.json, packages/strapi-icons/package.json, yarn.lock
Updates package versions to 1.7.10.
Should have been done in https://github.com/strapi/design-system/pull/1098
=> Release 1.7.10

packages/strapi-design-system/package.json, packages/strapi-design-system/test/utils.tsx
- Fixes the `generate:types` tsc command; `--declarationDir` requires `--declaration`
- Fixes the return type of the test util; before it failed with "The inferred type of 'render' cannot be named without a reference to '@testing-library/dom/node_modules/pretty-format'. This is likely not portable. A type annotation is necessary."
Paves the path towards published types and allows me to learn.
Run `yarn generate:types` in the design-system package.
=> Chore: Fix type generation

package.json, packages/primitives/package.json, packages/primitives/src/components/Collection/Collection.tsx, packages/primitives/src/components/Combobox/Combobox.tsx, packages/primitives/src/components/Select/Select.tsx, packages/strapi-design-system/package.json, packages/strapi-design-system/src/Grid/Grid.tsx, yarn.lock
It standardizes the types declaration for the components removing the `React.FC` and replacing it with the types inside function parameters as explained here: https://www.notion.so/strapi/Props-inside-Function-Parameters-7a221947771f48db815dba5ba3cf4410?pvs=4
To have a standard types declaration for components in the design system
Search globally in the project for React.FC and there shouldn't be any result.
=> chore: Standardize types inside the function params

packages/strapi-design-system/src/DatePicker/DatePicker.tsx, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.tsx, packages/strapi-design-system/src/DateTimePicker/DateTimePicker.tsx, yarn.lock
* shims a fix for a regression brought about in 1.8.0 where the DatePicker could not handle strings
* reverts an accidental regression
* automated testing 🪄 
* resolves #1149 
* resolves CONTENT-1518
=> fix: allow passing a string to DatePicker

packages/strapi-design-system/src/DatePicker/DatePicker.tsx, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.tsx
* Allows the typing of the date in any given locale
* Sets the correct placeholder text based on the locale
* Always updates the text value by the `formatter.format` to ensure the locale is respected
* Locales like japanese where not correctly respected.
* Automated tests added 🪄 
* resolves #1162
=> fix: date picker typing localisation 

packages/primitives/src/components/Combobox/Combobox.tsx, packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx
* Stops the onBlur calls if the menu is not open
* It would call when the menu was open so therefore if you clicked an item in the menu it would not register.
* Added automated testing
* I did a hard `return` always from `onBlur` and found several tests failed surrounding the `onBlur` functionality, so even though this seems _very_ simple, it seems to be the solution
* resolves #1074
=> fix: only call onBlur if the menu is not open

packages/strapi-design-system/src/Button/Button.tsx, packages/strapi-design-system/src/ModalLayout/__tests__/ModalLayout.spec.tsx, packages/strapi-design-system/src/v2/Breadcrumbs/CrumbSimpleMenu.tsx, packages/strapi-design-system/src/v2/SimpleMenu/Menu.tsx
It fixes the problem we had inside the Breadcrumb v2 
The CarretDown icon is an error based on the Mockups
You can find them here
https://www.figma.com/file/doUJzYdMJTjpgtw6Lyaa7D/%5B%E2%9C%85Done%5D-Content-squad---Media-folders?type=design&node-id=1741-30931&t=6Xu5lry10tCSaxRB-0
Because in prod the actual implementation is not the desired one
You can just check the storybook generated (v2 Breadcrumb with menu) 
https://github.com/strapi/design-system/issues/1090
=> fix: Breadcrumbs (v2) abbrevation menu is broken

package.json, packages/strapi-design-system/src/DatePicker/DatePicker.tsx, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.tsx, test/env-setup.js, yarn.lock
* removes `intl` polyfill (not needed anymore, JSDOM has it)
* uses `getLocalTimeZone` for the timezone context
* uses timzone to format the date correctly to a UTC format
* because the time was always `00:00` any timezone -GMT would go to the day before on update
* resolves #1171
=> fix: date picker with some timezones would change date automatically

packages/strapi-design-system/src/Combobox/Combobox.tsx, packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx, packages/strapi-design-system/src/Select/MultiSelect.tsx, packages/strapi-design-system/src/Select/MultiSelectNested.tsx, packages/strapi-design-system/src/Select/SingleSelect.tsx, packages/strapi-design-system/src/Select/__tests__/MultiSelect.spec.tsx, packages/strapi-design-system/src/Select/__tests__/MultiSelectNested.spec.tsx, packages/strapi-design-system/src/Select/__tests__/SingleSelect.spec.tsx
* Makes it so you must pass either `label` or `aria-label` as a prop
* no longer renders the label element if `label` is not included
* There are a lot of places where we don't have a visible label in the UI and because of how we want our components it still tries to render the `label` element which causes the flex gap to still be there, no we don't render that element – re-aligning a lot of the UI.
* Automated testing to make sure it's still accessible with just an `aria-label` prop.
* resolves CONTENT-1557
=> fix: make label an optional prop

.github/dependabot.yml
- Changes the dependabot schedule to only update dependencies on Sunday evening (in sync with the monorepo)
- Setup dependency groups for dependencies that should be updated together
- Less PRs.
=> Chore: Setup dependabot dependency grouping

package.json, website/package.json
Adds a node engine definition to the package.json files. Right now it is in sync with the monorepo.
Otherwise the vercel website deployment fails, because it attempts to use node@14 as seen [here](https://vercel.com/strapijs/design-system-website/5zpBbRSFKnBZndnz8YZRoGfnLnnw).
=> Chore: Add engines configuration to package.json files

.github/dependabot.yml
Extends the dependabot groups with storybook and eslint.
More dependency grouping - less PRs.
=> Chore: Extend dependabot groups with storybook and eslint

.github/dependabot.yml
Adds `storybook` as dependency to update along the storybook dependabot group.
It was missing.
Refs https://github.com/strapi/design-system/pull/1286
=> chore: Add storybook to dependabot storybook group

CONTRIBUTING.md, package.json, packages/primitives/package.json, packages/strapi-design-system/vite.config.ts, packages/strapi-icons/package.json, packages/strapi-icons/vite.config.ts, yarn.lock
Passing a env var we can publish types in the DS
We want to convert the helper-plugin and to do it we need the types from the design-system.
We can’t publish a version of this because it will be a breaking change, instead we can use an ENV flag to produce the types on demand and use yarn link to connect the design-system to the monorepo.
Run the yarn build with a env var 
`DTS=true yarn build`
Then, as said, with yarn link you can connect your local DS with the CMS
=> Add a flag to the build config of the design-system to publish types

packages/strapi-design-system/src/IconButton/IconButton.tsx
Exporting IconButton props
We are migrating helper-plugin/icons folder to TS, we need IconButtonProps to be exported from DS alongwith the component
https://strapi-inc.atlassian.net/browse/CS-158
=> fix: export IconButtonProps to be used in helper-plugin migration

.changeset/forty-seals-tan.md, packages/strapi-design-system/src/IconButton/IconButton.tsx, packages/strapi-design-system/src/ModalLayout/__tests__/__snapshots__/ModalLayout.spec.tsx.snap
Apply only border-color to `IconButton`s, bceause they also receive `borderWidth` and `noBorder` to set the border width. This bug has been introduced in https://github.com/strapi/design-system/pull/1319 and leads to too many borders being rendered.
Fixes a bug.
Add `noBorder` or `borderWidth={0}` attributes to `variants`.
- https://github.com/strapi/design-system/pull/1319
=> fix(IconButton): respect `borderWidth`

.changeset/pink-hats-tie.md, packages/strapi-design-system/src/Accordion/AccordionGroup.tsx, packages/strapi-design-system/src/Combobox/Combobox.tsx, packages/strapi-design-system/src/DateTimePicker/DateTimePicker.tsx, packages/strapi-design-system/src/JSONInput/JSONInput.tsx, packages/strapi-design-system/src/Select/MultiSelect.tsx, packages/strapi-design-system/src/Select/SingleSelect.tsx, packages/strapi-design-system/src/Textarea/Textarea.tsx, packages/strapi-design-system/src/TimePicker/TimePicker.tsx, packages/strapi-design-system/src/ToggleInput/ToggleInput.tsx
* changes all instances of `labelAction` to use the type `FieldLableProps['labelAction']`
* through strapi/strapi#17746 there were some inconsistencies with the meaning of `labelAction` even though it's always passed to the same place
=> fix(design-system): use FieldLabelProps['action'] to define labelAction

turbo.json
* writes a specific turbo config for the build command for `strapi-icons` due to unique pipeline
* the action was being cached incorrectly in vercel where it assumed `src` was the input, not the output
=> fix: turbo cache for strapi-icons

.changeset/lovely-mangos-lick.md, packages/strapi-design-system/src/v2/LinkButton/LinkButton.tsx
Export the v2 LinkButton to start using it in other packages.
=> fix: export LinkButton type

.changeset/happy-pants-ring.md, packages/strapi-design-system/src/DateTimePicker/DateTimePicker.tsx
Increases the time picker min-width to accommodate the content when in smaller desktop screens. 
Currently the time picker min-width is set too low that in smaller screens the content exceeds the min-width causing the content to be "cropped/masked" off.
Open the DateTimePicker `controlled` component in Storyboard and set browser to a width of 600px using your favorite responsive web tool. Set time to 05:45. Resize the browser width to see in various widths.
Fixes https://github.com/strapi/strapi/issues/18159
=> fix: date time picker value from being masked in small screens

.changeset/few-fishes-sip.md, packages/strapi-design-system/src/Select/MultiSelect.tsx, packages/strapi-design-system/src/Select/SingleSelect.tsx
Adds the onCloseAutoFocus to single select
We need to be able to prevent the default behavior for the Rich Text Editor in the CMS
You can test it in the CMS with this PR https://github.com/strapi/strapi/pull/18193
=> feat(design-system): add onCloseAutoFocus

.changeset/long-buses-yawn.md, packages/strapi-design-system/src/Combobox/Combobox.tsx, packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx
Updates the Combobox rendered value if the corresponding prop changes "externally" (without clicking an option)
Because if the prop changes, the "internal" value is actually updated but the rendered text not
I tested this manually, let me know if I should update UT
```
// docs/stories/Combobox.stories.tsx
export const Depending = {
render: () => {
const [value, setValue] = useState('');
const options = ['apple', 'avocado', 'banana', 'kiwi', 'mango', 'orange', 'strawberry'];
const handleChange = (index) => {
setValue(options[index]);
};
return (
<Flex direction="column" alignItems="stretch" gap={11}>
{options.map((option, index) => (
<Button key={index} onClick={() => handleChange(index)}>
{index}
</Button>
))}
<span style={{ color: 'white' }}>{value}</span>
<Combobox
placeholder="My …
```
=> fix: Combobox rendered text when value prop changes

.changeset/breezy-jobs-agree.md, packages/strapi-design-system/src/Layout/HeaderLayout.tsx, packages/strapi-design-system/src/Main/Main.tsx
1. makes `labelledBy` optional because there is default value assignment inside component. I used `| undefined` by design so it's compatible with https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes.
2. removed `string` type because it's already part of `React.ReactNode` type
Better developer experience.
=> make labelledBy prop optional for Main component and remove redundant type

.changeset/gold-mugs-brake.md, packages/strapi-design-system/src/Link/Link.tsx, packages/strapi-design-system/src/LinkButton/LinkButton.tsx
* some properties in types are `never` which want to be optional not required, because you can never make them pass
* Issues using links with `href` vs `to`
* discovered in #18209
=> fix(design-system): never types should be optional

.changeset/tough-laws-pay.md, .gitignore, packages/strapi-design-system/src/Box/Box.tsx, packages/strapi-design-system/src/helpers/handleResponsiveValues.ts, packages/strapi-design-system/src/types.ts
* changes `ResponsiveValue` to be union including `DefaultThemeOrCSSProp` because you can do `marginLeft="auto"` and that should be fine.
* TS didn't reflect code power
* found converting `NpsSurvey` to TS
=> fix(design-system): add CSS properties as a value for responsive values

packages/strapi-design-system/src/Field/FieldLabel.tsx, packages/strapi-design-system/src/Typography/Typography.tsx, packages/strapi-design-system/src/types.ts, packages/strapi-design-system/src/v2/SimpleMenu/Menu.tsx
* change `TypographyProps` to extend `ComponentProps`
* better than `HTMLAttributes`
* you couldn't pass `htmlFor` in this circumstance (where FieldLabel extends Typography):
```ts
interface FieldLabel extends TypographyProps<HTMLLabelElement> {
// blah
}
<FieldLabel htmlFor="test" />
```
=> fix(design-system): typography props should extend ComponentProps

packages/strapi-design-system/src/Combobox/Combobox.tsx, packages/strapi-design-system/src/Combobox/__tests__/Combobox.spec.tsx
Manually revert changes done in [#1381](https://github.com/strapi/design-system/pull/1381)
Becaus [#1381](https://github.com/strapi/design-system/pull/1381) fixes the behavior explained there but also introduces a new issue:
- When the value and the rendered text are not the same (e.g. `{ value: 'FR', label: 'France'}`) and the option "France" is clicked, the rendered value is `FR` instead of `France` until the input is focus out
=> chore: remove combobox useEffect used to trigger handleTextValueChange

packages/strapi-design-system/src/Alert/Alert.tsx
Make the title property of the Alert component optional
Because on the Strapi codebase is already being used without specifying the title. And during the migration from JS to TS the errors are starting to appear
Use the Alert component and check that no title is required
=> fix: make title optional

.changeset/hot-starfishes-judge.md, package.json, yarn.lock
* changes _one_ dependency in the yarn.lock
* radix packages had an issue with version 1.0.0 where they weren't set up correctly causing issues for certain bundlers e.g. vite
* potentially resolves #1431
=> fix(deps): ensure there's no 1.0.0 version of radix packages

.changeset/cool-turkeys-judge.md, packages/strapi-design-system/src/Accordion/Accordion.tsx, packages/strapi-design-system/src/Link/Link.tsx, packages/strapi-design-system/src/LinkButton/LinkButton.tsx
* exports some of the missing prop types for components e.g. `link`
* need them for TS building in the admin
=> fix(design-system): export some missing prop types

.changeset/slimy-tables-explain.md, docs/stories/FocusTrap.stories.tsx, packages/strapi-design-system/src/FocusTrap/FocusTrap.tsx
Added **skipAutoFocus** on focusTrap to set focus manually
To edit blocks input in fullscreen/expanded mode, user need focus on the blocks-input instead of the default first element of editor toolbar
Added a story without auto focus to test
=> fix: Added skipAutoFocus on focusTrap

.changeset/brave-chefs-behave.md, packages/strapi-design-system/src/BaseCheckbox/BaseCheckbox.tsx, packages/strapi-design-system/src/Select/MultiSelect.tsx
* adds quote marks to where we inline the string from the checkbox asset import
* the CSS comes out incorrectly resulting in no checks in the CMS
* mentioned in https://github.com/strapi/strapi/pull/19136#issuecomment-1881242950
=> fix(design-system): checkbox svg need quotes to work correctly

.changeset/tasty-cars-hide.md, docs/stories/Combobox.mdx, docs/stories/Combobox.stories.tsx, docs/stories/primitives/Combobox.mdx, docs/stories/primitives/Combobox.stories.tsx, packages/primitives/src/components/Combobox/Combobox.tsx, packages/primitives/src/components/Combobox/__tests__/Combobox.test.tsx
Till now we were filtering by default matching starting character and autocomplete accepted values were: "none", "list", "both". Now we have added a new option `contains` to filter by substring. 
However `filter:'contains'` option is only available on `autocomplete='list'` as having for `autocomplete="both"` would not work as expected. Also to have backward compatibility and for consistency across all supported filter types, we are introducing object counterparts of existing types.
Filtering by substring is required in timezone dropdown in scheduling releases as TZ starts with UTC and not actual TZ value.
You can test newly added filter option in storybook under `primitives/combobox` as well as `DS/combobox` component
=> Feat: new filter "contains" is added on combobox for autocomplete type:list

.changeset/mighty-hats-complain.md, packages/strapi-design-system/src/DatePicker/DatePicker.tsx, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.tsx
Disables datepicker selection for given min and max date, unit tests added.
Please check respective story.
=> Fix: Disable datepicker selection for min and max date

.changeset/smart-buttons-do.md, packages/primitives/README.md, packages/primitives/src/index.ts, packages/strapi-design-system/src/index.ts
* exports useCallbackRef, useCollator & useFilter from primitives
* exports useDateFormatter & useComposedRefs from design-system
* we're gonna remove these from the helper-plugin and it makes sense to have a single source of truth, it feels appropriate that they're here.
=> feat: export hooks from primitives & DS

.changeset/brave-trainers-tell.md, .github/workflows/bundle-size.yml, .github/workflows/experimental.yml, .github/workflows/tests.yml, packages/strapi-design-system/src/DatePicker/__tests__/DatePicker.spec.tsx, packages/strapi-design-system/src/DateTimePicker/__tests__/DateTimePicker.spec.tsx, packages/strapi-design-system/src/Tabs/TabGroup.tsx
Makes the tab components controllable so we can set the selected index from outside the component
D&P tab navigation in the monorepo
CONTENT-2298
=> feat: Controlled tabs

.changeset/slow-deers-confess.md, packages/strapi-design-system/src/Accordion/AccordionToggle.tsx
Accordian complete header is made clickable.
The padding of the "header" of the Accordion is not included in the click area
=> Fix:  accordian complete header clickable issue

.changeset/spicy-items-wink.md, packages/strapi-design-system/src/Dialog/Dialog.tsx
- add a zIndex prop with default 4 
- to give more controll
- pass the prop and make sure the value comes through
=> feat: add zIndex prop to Dialog

.changeset/quick-buckets-grab.md, packages/strapi-design-system/src/MainNav/NavLink.tsx
* changes the icon size in `MainNav/NavLink` to be `1.6rem` instead of `1rem`
* visual issue
* related https://github.com/strapi/strapi/pull/20151
=> fix(design-system): main nav icons should be 1.6rem

.changeset/afraid-crews-dream.md, packages/strapi-design-system/src/ModalLayout/__tests__/__snapshots__/ModalLayout.test.tsx.snap, packages/strapi-design-system/src/Tag/__tests__/Tag.test.tsx, packages/strapi-icons/svgr.icons.config.js, packages/strapi-icons/svgr.symbols.config.js, turbo.json
* icons by default at 16 as a number not in rem.
* resolves #1707
=> fix(icons): dont use rem sizes on width and height properties

.changeset/large-tigers-hope.md, CONTRIBUTING.md, packages/strapi-design-system/packup.config.ts, packages/strapi-design-system/src/JSONInput/JSONInput.tsx, packages/strapi-design-system/src/JSONInput/utils/decorationExtension.ts
* finds the codemirror deps we access but aren't declared in the package.json and make them external to avoid being bundled
* JSON fields crash the strapi app because we load more than one version of codemirror state
* resolves #1706
=> fix(design-system): codemirror packages that aren't in package.json are declared as external

.changeset/swift-cycles-type.md, docs/stories/Tag.mdx, docs/stories/Tag.stories.tsx, packages/design-system/src/components/Tag/Tag.test.tsx, packages/design-system/src/components/Tag/Tag.tsx
Filter click action passed on icon instead of tag itself, adjusted styles to show cursor pointer on hover
filters shouldn't be removed after clicking on filter tag
Fixes https://github.com/strapi/design-system/issues/679
=> fix: filters shouldn't be removed after clicking on filter tag

.changeset/rotten-eagles-matter.md, packages/design-system/src/components/Breadcrumbs/Breadcrumbs.tsx, packages/design-system/src/components/Breadcrumbs/Crumb.tsx, packages/design-system/src/components/Breadcrumbs/CrumbLink.tsx, packages/design-system/src/components/Breadcrumbs/CrumbSimpleMenu.tsx, packages/design-system/src/components/Card/Card.tsx, packages/design-system/src/components/Card/CardAction.tsx, packages/design-system/src/components/Card/CardCheckbox.tsx, packages/design-system/src/components/EmptyStateLayout/EmptyStateLayout.tsx, packages/design-system/src/components/Popover/Popover.tsx, packages/design-system/src/components/RawTable/RawCell.tsx, packages/design-system/src/components/RawTable/RawTable.tsx, packages/design-system/src/components/SimpleMenu/SimpleMenu.tsx, packages/design-system/src/components/Table/Cell.tsx, packages/design-system/src/components/Table/Table.tsx
Standardising forwardRefs across components, so added forward refs to interactive and actionable components.
Currently, a lot of components don’t have forwardRef some do, and it applies to the input field of that component, some edge cases use imperativeHandle e.g. TextInput, realistically we should add forwardRef to all the components in some capacity, [Ref](https://strapi-inc.atlassian.net/browse/DX-1182).
=> chore: standardise forwardRefs across components

.changeset/few-cameras-joke.md, packages/design-system/src/components/Link/Link.tsx
Fixed: Link doesn't show the hover color
fixes https://github.com/strapi/design-system/issues/1525
=> fix: typography hover style

.changeset/short-pets-attack.md, packages/design-system/src/components/Modal/Modal.tsx
It fixes the wrong behaviour in the Modal Content component, the children components are not scrollable, I moved the ContentImpl as a child of the Overlay component and I changed the background rule in the Overlay style to don't affect the opacity of the Overlay children
Because otherwise scrolling is not working for example in dropdown used in the Modal body.
Here an example of the issue
https://github.com/strapi/design-system/assets/2589748/f6177b1d-1de9-459b-be63-5e46fcba7c26
and here the solution
https://github.com/strapi/design-system/assets/2589748/b47e2a95-1624-4195-b844-dc7f22a9583d
You can test the solution directly in the Modal DS storybook https://64f9707bb212b1f1332bfd97-ehiswajggi.chromatic.com/?path=/story/components-modal--base
fixes …
=> fix: move the Modal Content inside the Overlay component and change the background rule of the Overlay

.changeset/six-pans-sip.md, packages/design-system/src/components/SubNav/SubNavHeader.tsx
Adds a gap between the SubNavHeader label and search icon
Because it looked like this:
The space-between was ignored because the element itself was shrunk by the parent flex, and there was no gap defined
=> fix: add gap inside SubNavHeader

.changeset/config.json, .changeset/slimy-shirts-cover.md, .github/workflows/release.yml
Changesets github action has been failing with a 403 using the env var:
GITHUB_TOKEN: ${{ secrets.CHANGESETS_GITHUB_TOKEN }}
This PR changes the release yaml to use the repository default so the github actions runner can create the commits, branches and pull requests that it needs
=> chore: use the default github secret for changeset

.changeset/lazy-kiwis-protect.md, packages/design-system/src/components/Modal/Modal.tsx
Change some height rules (height and min-height in the Modal.Content) to solve issues with some browser or some modals truncated for example for DZ
For some browsers or some views the footer part is hidden or truncated, for example
This happens in the Create Collection/Component modal in Safari and other browsers
and this one in the DZ modal
link this branch to your version of the CMS by following these instructions https://github.com/strapi/design-system/blob/main/CONTRIBUTING.md#example-steps
fixes https://github.com/strapi/strapi/issues/20574
=> fix: modal footer issues

.changeset/chatty-jokes-grow.md, packages/design-system/src/components/SimpleMenu/Menu.tsx
Extends the CSS rule in the Menu.Item in case the aria-disabled attribute has just a true value, otherwise the disabled state is applied even if the menu item is not disabled
Otherwise for example when we use a NavLink in the Menu.Item the aria-disabled attribute is present even if it is false and with the old css rule the style is applied in both cases, true or false
An example in the CMS is this one
link this branch to your version of the CMS by following these instructions https://github.com/strapi/design-system/blob/main/CONTRIBUTING.md#example-steps
fixes https://github.com/strapi/strapi/issues/20774
=> fix: menu item disabled style wrongly applied

.changeset/quick-pans-occur.md, docs/stories/04-components/IconButton.mdx, docs/stories/04-components/IconButton.stories.tsx, packages/design-system/src/components/Field/Field.tsx, packages/design-system/src/components/IconButton/IconButton.tsx
- Default Icon button size updated to small.
- Field label supports ellipsis now, fixes https://github.com/strapi/design-system/issues/1627
=> fix: styling for icon button and field label 

.changeset/metal-poems-type.md, packages/design-system/src/components/Link/Link.tsx
Apply link hover color to its label and not to children
In CMS, where we are using `Link` component as a wrapper with children inside it, its causing hover style to apply to all its span elements unnecessarily.
=> fix: link hover color 

.changeset/small-zebras-explain.md, packages/design-system/src/components/SubNav/SubNavHeader.tsx
User can pass a placeholder prop to SubNavHeader now.
Fixes https://github.com/strapi/design-system/issues/1201
=> fix: remove static placeholder from SubNavHeader

.changeset/cool-carrots-explode.md, .changeset/gorgeous-zoos-unite.md, docs/stories/04-components/Field.stories.tsx, packages/design-system/src/components/Combobox/Combobox.test.tsx, packages/design-system/src/components/Combobox/Combobox.tsx, packages/design-system/src/components/Field/Field.tsx, packages/design-system/src/components/IconButton/IconButton.tsx, packages/design-system/src/components/Select/SelectParts.tsx, packages/design-system/src/components/SimpleMenu/Menu.tsx, packages/primitives/src/components/Combobox/Combobox.tsx
1. Field label style fixed
2. Tertiary Icon button `color: neutral500` and `hover-color: neutral600` updated as per design
3. Simple menu with `tag: IconButton` should have `tertiary` style applied
4. Select carret down `color: neutral500` fixed.
5. Combobox with no options provided should show default "No results found" value.
Fixes: https://github.com/strapi/design-system/issues/1626
=> fix: multiple UI styling changes

.changeset/weak-eels-jump.md, docs/stories/Box.mdx, packages/design-system/src/helpers/__tests__/handleResponsiveValues.test.ts, packages/design-system/src/primitives/Grid/Grid.tsx, packages/design-system/src/themes/common-theme.ts
With current breakpoint for large screen with `min-width:1280px`, its breaking CMS for the resolution 1280-1080px that is too soon than expected. After discussing with design its now updated to `min-width:1080px` for large screen.
https://github.com/strapi/strapi/pull/20936#issuecomment-2285827184
=> fix: responsive breakpoint change for large screen

.changeset/smart-cheetahs-complain.md, packages/design-system/src/components/CarouselInput/Carousel.tsx, packages/design-system/src/components/CarouselInput/CarouselActions.tsx
Changes on the carousel input:
- Makes the chevron icons bigger
- Adds a gap in between the floating icons
https://strapi-inc.atlassian.net/browse/CS-1071
=> fix: carousel input ui

.changeset/swift-garlics-cross.md, docs/stories/03-inputs/Select.mdx, docs/stories/03-inputs/Select.stories.tsx, packages/design-system/src/components/Select/SingleSelect.tsx
Fix small bugs on Select to match styles on Locale Picker from CMS
https://github.com/strapi/strapi/issues/19960
=> fix: select flex and start icon inline bug

.changeset/stale-apes-approve.md, packages/design-system/src/components/Accordion/Accordion.tsx
Adds an optional prop 'iconProps' to the Accordion component
So we can modify the icon, e.g. add a fill color to it
This came up when converting the SEO plugin to v5 through https://github.com/strapi/strapi-plugin-seo/pull/76
DX-1693
=> Optional iconProps can be passed to Accordions

.changeset/sweet-timers-help.md, packages/design-system/src/components/Checkbox/Checkbox.tsx, packages/design-system/src/components/Select/SelectParts.tsx
What does it do?
Fixed the Media Library's missing cursor pointers issue on the filters
Why is it needed?
To fix issue https://github.com/strapi/design-system/issues/1791: Media Library missing cursor pointers on the filters
How to test it?
- Open the Media Library
- Hover over the filters, it should show the cursor pointers.
Related issue(s)/PR(s)
https://github.com/strapi/design-system/issues/1791
=> fix: added cursor pointer for checkbox and pre-filled list

.changeset/chilly-trains-push.md, docs/stories/Status.mdx, docs/stories/Status.stories.tsx, packages/design-system/src/components/Status/Status.tsx
Adds a smaller XS variant to the Status component, in addition to the existing S and M versions
We need this size to apply the designs of the document status, for both history and preview features in the CMS
storybook link
=> enhancement: add xs size to status component

docs/stories/Status.stories.tsx, packages/design-system/src/components/Status/Status.test.tsx, packages/design-system/src/components/Status/Status.tsx
Remove the showBullet option from the Status component. It was a leftover from the CMS v4 designs that is not in use anymore. This v2 RC is our chance to get rid of it (see the comment that was in the code)
Cleaning up dead code
=> chore: remove Status showBullet option

.changeset/blue-humans-sin.md, packages/primitives/src/components/Combobox/Combobox.test.tsx, packages/primitives/src/components/Combobox/Combobox.tsx
This PR fixes the existing issue that always renders the `No result found` (empty state) of the combobox when autocomplete is set to off.
Avoid rendering the `No result found` at the end of the option list (when `autocomplete = none`) which is the case in all Strapi Cloud combobox.
Added new unit tests to handle this use case
https://github.com/strapi/design-system/issues/1803
=> fix: combobox primitive empty state when autocomplete is none

.changeset/grumpy-peaches-design.md, packages/design-system/src/components/SimpleMenu/Menu.test.tsx, packages/design-system/src/components/SimpleMenu/Menu.tsx
- Pass the disabled prop to the Radix dropdown 
- The prop is not passed through with `asChild` as expected. Currently no Menu.Trigger can be disabled.
- Test it in the CMS with yarn link (there is no Storybook for this component)
=> fix(Menu): add disabled prop to menu trigger not applied through asChild

.changeset/three-eels-clap.md, packages/design-system/src/components/Tooltip/Tooltip.test.tsx, packages/design-system/src/components/Tooltip/Tooltip.tsx
The `label` prop for the `<Tooltip />` component is optional, but it doesn't prevent the tooltip from rendering when it's missing.
Create a tooltip with an empty `label` prop
=> Prevent tooltip from rendering with empty label

.changeset/hungry-adults-promise.md, packages/design-system/src/components/Searchbar/Searchbar.tsx
This PR updates the search bar component to match the design system specifications by:
- Adjusted the search icon size to 16px and color to Neutral500
- Set input height to 32px with 8px padding
- Updated placeholder text color to Neutral500
- Refined the border and focus states for better consistency
- Removed excess shadow for cleaner appearance
- Fixed layout shift issues between collapsed and expanded states
As reported in issue #1832, the current search bar implementation had several visual inconsistencies:
- The search bar caused layout shifts when opened due to mismatched sizes with surrounding 32px elements
- Visual appearance didn't match the design system (icon colors, shadow, borders)
- Dark mode colors were incorrect
- The transition between states wasn't smooth
Describe the …
=> bug: clean search bar

.changeset/new-cobras-flash.md, docs/stories/01-foundations/typography.mdx, docs/stories/03-inputs/Toggle.mdx, docs/stories/04-components/LinkButton.mdx, docs/stories/Alert.mdx, docs/stories/Badge.mdx, docs/stories/Box.mdx, docs/stories/Breadcrumbs.mdx, docs/stories/Card.mdx, docs/stories/Carousel.mdx, docs/stories/Divider.mdx, docs/stories/EmptyStateLayout.mdx, docs/stories/Flex.mdx, docs/stories/Grid.mdx, docs/stories/Link.mdx, docs/stories/LiveRegions.mdx, docs/stories/Loader.mdx, docs/stories/Pagination.mdx, docs/stories/RawTable.mdx, docs/stories/Searchbar.mdx, docs/stories/SimpleMenu.mdx, docs/stories/Status.mdx, docs/stories/SubNav.mdx, docs/stories/Table.mdx, docs/stories/Tag.mdx
sync view source to the correct path
to redirect to the correct path when the user clicked the "ViewSource"
=> doc: sync view source to the correct path

.changeset/bright-grapes-juggle.md, docs/stories/SimpleMenu.mdx, docs/stories/SimpleMenu.stories.tsx, packages/design-system/src/components/SimpleMenu/Menu.tsx
Exports a styled version of Radix's DropdownMenu.Separator component.
It's needed in the designs:
See the example in the nested menu storybook
=> feat: add menu separator component

.changeset/little-turtles-wait.md, packages/design-system/src/components/SimpleMenu/Menu.tsx
Exposes Radix's onCloseAutoFocus prop on the Menu.Content component.
It's necessary to bring the focus back to the blocks editor in the CMS after a menu item is selected in the toolbar. 
We did the same thing for Select in #1371, it worked nicely.
=> feat: add onCloseAutoFocus to Menu.Content

.changeset/popular-terms-remain.md, packages/design-system/src/components/SimpleMenu/Menu.tsx
Attaches forwardRef's ref in simple menu separator
Forward ref wasn't doing anything, and more importantly it was breaking the unit tests of the CMS because of this error:
>Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
was missing in #1846
=> fix: pass menu separator ref

.changeset/stale-clouds-divide.md, docs/stories/SimpleMenu.stories.tsx, packages/design-system/src/components/SimpleMenu/Menu.test.tsx, packages/design-system/src/components/SimpleMenu/Menu.tsx
Add start and end icons to Menu.Item
The CMS uses icons in Menu.Item's often
There are unit tests
Otherwise it can be tested locally in the SimpleMenu.stories.tsx file
=> feat(Menu): add start and end icons to MenuItem

.changeset/tiny-melons-help.md, packages/design-system/src/components/Select/SelectParts.tsx
As described in https://github.com/strapi/design-system/pull/1841, this PR fixes the missing scroll wrapper of the `Select` component.
[Before](https://design-system-git-main-strapijs.vercel.app/?path=/story/inputs-select--base):
[After](https://design-system-git-main-strapijs.vercel.app/?path=/story/inputs-select--base):
MUCH better user experience!
=> fix: add missing scroll wrapper to `Select` element

.changeset/fifty-hats-itch.md, packages/design-system/src/components/Select/SelectParts.tsx
- Removed the background of the `Select.Item` when it's selected.
- Added a cursor change to pointer when `Select.Item` is hovered.
See https://github.com/strapi/design-system/issues/1808.
You can check the multiple `Select` [here](https://design-system.strapi.io/?path=/story/inputs-select--multiple).
fixes https://github.com/strapi/design-system/issues/1808
=> fix: remove selected item background

docs/components/Typography.tsx
h3 tags were rendered with the same font-size of the h2 tags
Readability of the documentation is much better.
Navigate to any documentation page containing a h3
=> fixing h3 font size

.changeset/tiny-cups-reflect.md, packages/design-system/src/components/SimpleMenu/Menu.tsx
Menu didn't have any zIndex configured, so it was being displayed behind modals, popovers, selects, ...
So its visible in the right z layer.
Create a Menu inside a modal, and ensure it's visible.
=> fix: menu zindex

.changeset/famous-dryers-float.md, packages/design-system/src/components/Accordion/Accordion.tsx
Prevents title string from overflowing
When the title of Accordion is too long, it pushes away the icons on the right out of the screen. 
See: https://github.com/strapi/strapi/issues/23051
https://github.com/strapi/strapi/issues/23051
=> fix: accordion title overflow issue

.changeset/famous-elephants-confess.md, packages/design-system/src/components/Combobox/Combobox.test.tsx, packages/design-system/src/components/Combobox/Combobox.tsx, packages/design-system/src/components/DatePicker/DatePicker.tsx, packages/design-system/src/components/Field/Field.tsx, packages/design-system/src/components/Searchbar/Searchbar.tsx
- Capitalized the first letter of the value of `clearLabel` 
- Replaced `IconBox` by `IconButton`
- Replaced `IconBox` by `IconButton`
- Wrapped `Cross` icon inside of `IconButton`
- Changed the `right` property of `EndAction`
See https://github.com/strapi/design-system/issues/1837, https://github.com/strapi/design-system/issues/1876 and https://github.com/strapi/design-system/issues/1849.
You'll need to chec the preview.
https://github.com/strapi/design-system/issues/1837
https://github.com/strapi/design-system/issues/1876
https://github.com/strapi/design-system/issues/1849
=> feat: use xs iconbutton for combobox, datepicker and searchbar

.changeset/proud-doors-knock.md, packages/design-system/src/components/Combobox/Combobox.test.tsx, packages/design-system/src/components/Combobox/Combobox.tsx, packages/primitives/src/components/Combobox/Combobox.tsx
It fixes some small errors we introduced with the refactoring of the Combobox
it doesn't close the combobox when the creatable button is clicked with creatable="visible"
Try to click on the creatable button in the Creatable Visible scenario in the storybook (with mouse and keyboard) and check if the combobox is then closed
=> fix: Combobox creatable visible button needs to close the combobox when clicked

.changeset/famous-starfishes-marry.md, packages/design-system/src/components/Combobox/Combobox.tsx
Fix an issue when you hover the creatable button with different options in the Combobox
To solve this issue
Check the Combobox creatable option in the storybook and scroll the different options and hover the creatable button to check if the issue is gone
CS-1409
=> fix: Combobox fix background issue in the creatable button on hover

.changeset/many-countries-look.md, packages/design-system/src/components/CarouselInput/CarouselSlide.tsx
it fixes the display property in case a slide is selected, because we had a conflict with the display none and display flex in the CarouselSlide element
Because before CarouselInput shows all slides at once
Go to the storybook and select the CarouselInput component and check the base case where we have three images to slide
fixes https://github.com/strapi/design-system/issues/1909
=> fix: fix the bug CarouselInput shows all slides at once

.changeset/quiet-wolves-move.md, packages/design-system/src/components/Modal/Modal.tsx, packages/design-system/src/themes/utils.ts
Fix the issue we had on the left and right of focused input elements inside modals
the left and right shadows of input elements where sometimes cropped
Try to test the issue in the Storybook in the Modal component
fixes https://github.com/strapi/design-system/issues/1902
=> Fix: input box shadows cropped

.changeset/wild-geese-lay.md, packages/design-system/src/components/Modal/Modal.tsx
fix: scroll body modal that contains a form
fix: decrease body padding of modal
Fixes various issues with modals.
- The scroll in a combobox is not working inside a modal
- The scroll inside the modal is not working when a form wraps the Modal.Body
- The padding of the body is too big (should be 32px instead of 40px, see strapi/strapi issue [#20821](https://github.com/strapi/strapi/issues/20821))
First tab showed is current behaviour and second tab is the design system fixed:
https://github.com/user-attachments/assets/2aee564e-7351-404f-9b75-37e2d6645ba9
The user has some trouble using the modals correctly (especially the scroll of the combobox) making it very difficult to perform actions.
In Storybook:
- Go to Components > Modal and choose the story you want
- Resize the window and try …
=> fix: scroll in combobox inside modal

.changeset/proud-rivers-cross.md, .github/workflows/experimental.yml
I added a step in the experimental gh action to exit the changeset pre release mode to allow snapshot releases
Because otherwise we have this error
We need to try an experimental and see if it solve the issue
=> chore: enable experimental release for the DS

.changeset/thirty-wasps-explode.md, packages/design-system/src/components/DateTimePicker/DateTimePicker.tsx
Improve the responsive of the datetime picker fields on small containers.
https://github.com/user-attachments/assets/e4816e78-ceaf-484d-bb1d-473d817e01f3
_I also took the liberty to unify the size between the two elements (most of the time it's 50/50 in the admin interface)_
Improve the experience on smaller screens or when including a datetime field inside a modal / small container.
- Go to storybook > Inputs > DateTimePicker
- Try to resize the window
Resolves [#1853](https://github.com/strapi/design-system/issues/1853)
🚀
=> fix: datetime fields responsive

.changeset/wise-doors-hope.md, docs/stories/03-inputs/Checkbox.stories.tsx, packages/design-system/src/components/Checkbox/Checkbox.tsx
Fix the border color of checked disabled checboxes. They are supposed to be grey but currently they are blue due to a little CSS condition missing in the target rule.
Screenshot of the issue:
It's not very intuitive for the user and he couldn't understand if the checkbox is focused, active or not.
- Go to the admin interface > Settings > Roles
- Click on Super Admin role to display the disabled checboxes
Resolves https://github.com/strapi/strapi/issues/22032
🚀
=> fix: disabled checked checkboxes border

.changeset/good-badgers-brush.md, packages/design-system/src/components/Select/SelectParts.tsx
- Removes additional style for the checked state of `StyledSelectItem`
- Replaces `IconBox` by `IconButton`
See https://github.com/strapi/design-system/issues/1807 and https://github.com/strapi/design-system/issues/1926.
You'll need to check the preview.
https://github.com/strapi/design-system/issues/1807
https://github.com/strapi/design-system/issues/1926
=> fix: multi-select items style and clear button

.changeset/thick-chefs-return.md, packages/design-system/src/components/Combobox/Combobox.tsx
Fixes the UI for the creatable button in the combobox
Because it doesn't follow the style we adopted for the Options in the Combobox menu
Open the storybook for the Combobox Creatable Visible and Creatable Disabled to check the ui
fixes https://github.com/strapi/design-system/issues/1936
=> fix: modify the creatable ui
